cloudfoundry/cf-deployment

cf-deployment.yml

*Note*: Old `db_connection_string` is still supported for backward
compatability but will later be removed
[#133715603]

Add more granular bbs sql database connection parameters

---

cf-filler/recipe-cf-deployment.yml

Most components seem ok without having a 'commonname' set
but flanneld (part of netman-release) fails to connect to etcd
when the commonname is not present.
/cc @rosenhouse @markstgodard

Fix typo for 'commonname' field in recipe

---

cf-deployment.yml

The default in the garden release is `-1` which means garden's disk usage will indefinitely grow. @jfmyers9 informed me that `0` was the default in the diego manifest generation.

Configure garden to clean up on each container destroy

---

cf-deployment.yml

We noticed recently that the router_ssl certificate alternative_names were not being set.
Also taking the opportunity to add `*.((system_domain))` so that the certificate is valid for subdomains.
Thanks,
Andrew && Stu

Set router_ssl alternative names

---

cf-deployment.yml

We'd like these add these BOSH properties.
It requires that this [story](https://www.pivotaltracker.com/story/show/138835189) be accepted before it is merged. This way we don't introduced unused properties before they are consumed.

Configure syslog drain binder-CC mutual TLS

---

opsfiles/enable-local-route-emitters-windows-cell.yml
opsfiles/enable-local-route-emitters.yml
opsfiles/use-only-local-route-emitters-windows-cell.yml
opsfiles/use-only-local-route-emitters.yml

- There is an opsfile for enabling local route emitters on diego cells
*and* removing global route emitters.
- There is an opsfile for enabling local route emitters on diego cells.
There is duplicate code between these opsfiles. We debated some sort of assertion logic that would validate that the local route emitters were enabled if global route emitters were to be disabled. This seemed rather brittle. After discussion with RelInt, we figured the duplicate code would eventually be refactored in favor of some sort of assertion in the opsfile.
cc @genevievelesperance

Add opsfiles for local-route-emitter mode

---

cf-deployment.yml
operations/bosh-lite.yml
operations/static-ips.yml

routing-release 0.144.0 can consume it via links
Signed-off-by: Dan Wendorf <dwendorf@pivotal.io>

Remove nats config from routing-release components

---

cf-deployment.yml
operations/windows-cell.yml

This change requires TLS between the rep and the consul agent on Windows. Note that this can't be merged until https://github.com/cloudfoundry/diego-release/pull/253 is merged, but we're sending it now so that it can be merged when everything is in place.

Require mutual TLS for Windows consul agent API

---

cf-deployment.yml

The PR makes cfdot available to diego cells, making it easier to interact with diego components.
Signed-off-by: Brandon Shroyer <bshroyer@pivotal.io>

add the cfdot job to diego-cells

---

cf-deployment.yml

* Diego is also a client to Cloud Controller when handling callbacks (such as Task
completion).
[#133804829]
Signed-off-by: Chunyi Lyu <clyu@pivotal.io>

Extend diego bbs server cert to be a client

---

cf-deployment.yml
operations/bosh-lite.yml
operations/static-ips.yml
operations/tcp-routing-gcp.yml
operations/test/add-persistent-isolation-segment-diego-cell.yml
operations/windows-cell.yml

Consul can be run in two modes, server or client. We only want the
server-mode consul jobs to provide a link, but due to the nature of bosh
links, all consul jobs provide the link. Therefore, we need to select
the correct link.
Note: This PR should not be merged until cf-deployment is consuming a consul-release that includes cloudfoundry-incubator/consul-release#64, which will presumably be consul-release v153.

Allow consul to consume its own link

---

cf-deployment.yml
operations/postgres.yml

- WARNING: We also changed variable names for the cc, diego, and uaa
databases from `cf_mysql_mysql_seeded_databases_cc_password` to
`cc_database_password`. This will cause bosh to roll that secret and
the next deploy might be a bit bumpy.
[#139907835]
Signed-off-by: Lyle Franklin <lfranklin@pivotal.io>

Add override file to swap mysql for postgres

---

operations/windows-cell.yml

The `ca_certs_for_downloads` property was missing from the `rep_windows` job. It is needed to be able to set `diego.ssl.skip_cert_verify` to `false` and have the rep be able to talk to the file server. 
This PR also sets `diego.ssl.skip_cert_verify` to the default (false) so it verifies by default.

Allow secure communication between rep_windows and the file server by default

---

operations/windows-cell.yml

The hwc-buildpack is now on bosh.io and can be used with windows deployments. The release can be found here: https://bosh.io/releases/github.com/cloudfoundry-incubator/hwc-buildpack-release?version=2.1.0

add hwc-buildpack to windows-cell ops file

---

operations/windows-cell.yml

We cut a new release of garden-windows, this PR reflects the version bump.
Can we automate the bump of this release in CI?

Update garden-windows-bosh-release to the latest

---

cf-deployment.yml

As of capi-release 0.121.0, cloud_controller jobs can consume nats links.

Remove nats config from cloud_controller jobs

---

cf-deployment.yml

Rely instead on capi-release's default. This changes the system_domain_organization from default_org to system.
[finishes #138068601]

Remove system_domain_organization_config

---

cf-deployment.yml

The following properties will be required for CC-Uploader as of the next
CAPI release:
* capi.cc_uploader.cc.ca_cert
* capi.cc_uploader.cc.client_cert
* capi.cc_uploader.cc.client_key
https://www.pivotaltracker.com/story/show/139996781
Signed-off-by: Aakash Shah <ashah@pivotal.io>

Add mtls certs for CC uploader <-> CC

---

cf-deployment.yml
operations/test/add-persistent-isolation-segment-diego-cell.yml
operations/windows-cell.yml

This change configures the rep to serve only its administrative
endpoints (/ping, /evacuate) over plain HTTP. This change also
configures this plain-HTTP server to listen only on localhost
and not a remotely routable IP.
[#140322915]

Disable legacy unsecured endpoints on the rep API

---

cf-deployment.yml

Currently gives access to system_domain and app_domains
[finishes #138069149, #138069165]

Provide cloud_controller link for other deployments

---

cf-deployment.yml

This matches the number of reservable ports in operations/tcp-routing-gcp.yml.
If this is not set the default is 0 and you need cf update-quota to allow
routes to be created with ports.

Set default quota route ports to 100

---

cf-deployment.yml

Currently `diego-bbs` and `diego-brain` are being deployed along with the cells, that can (and likely will) cause downtime.
This commit fixes that issue.
Source: https://github.com/cloudfoundry/diego-release/blob/develop/docs/deployment-constraints.md#diego-manifest-jobs

Implement diego-deployment constraints

---

operations/bosh-lite.yml

This is what the cf-release bosh-lite manifest templates use.

Set default app memory to 256M on bosh-lite

---

operations/tcp-routing-gcp.yml

Hi, 
Currently TCP health check port is set to ephemeral port( `8080`) by default but it is recommended for operators to use reserved port(`80`). If port `8080` is used for health check it could potentially be a clash with router groups. 
Story: https://www.pivotaltracker.com/story/show/141653531
Regards
Shash

Use port 80 for TCP health check

---

cf-deployment.yml

Add TLS credentials for Diego rep's asset download/upload.
* Creates a new credential variable `diego-rep-agent` that gets used by the rep server and its internal asset uploader/downloader.
[finishes #141164981]

 Add TLS credentials for Diego Rep asset management.

---

cf-deployment.yml

This adds the server certs required to mTLS communication between Diego's Reps and CC-Uploader. The Rep is already configured with certs of the same CA (the client cert is `diego_rep_client`).
The added properties will be required in an upcoming CAPI release.
https://www.pivotaltracker.com/story/show/142166993
Side note:
- We were unsure what conventions have been set for `common_name`

Add more certs for cc-uploader <-> diego mTLS

---

cf-deployment.yml

This is a fix to Pr #110 
@anEXPer Turns out, your intuition was right, and the properties were really added one layer deeper (such that the `ca_cert` was not a sibling to `cc`). Our cf-deployment pipeline fortunately caught this mistake. See your comment on the PR: https://github.com/cloudfoundry/cf-deployment/pull/110#issuecomment-291249620

Fix location of cc_uploader server certs

---

cf-deployment.yml

Hi,
This is the first of a pair of PRs to add support for links in the etcd-release.
This PR ignores the link from etcd-release, which will allow us to cut a new release without breaking users of cf-deployment. We ran it through our CI using my fork and were able to get a successful deployment + CATs run.
Please note that we are blocked on cutting said new release of etcd-release until this PR is merged.
Thanks!
Dave

Ignore etcd-release links (for now).

---

bosh-lite/cloud-config.yml
cf-deployment.yml
operations/bosh-lite.yml
operations/scale-to-one-az.yml
operations/tcp-routing-gcp.yml
operations/test/add-persistent-isolation-segment-diego-cell.yml
operations/windows-cell.yml

I've sanity tested this change by upgrading my cloud-config + deploying: all ok.

consistent 'default' name for all things: 'private' network now 'default'

---

cf-deployment.yml
operations/experimental/locket-postgres.yml
operations/experimental/locket.yml

- Defaults database to mysql
- Uses diego_database_password for DB permissions
- Includes locket-postgres.yml file to work with postgres job
- Moves diego-bbs instance up in deployment order
[#143336051]
Signed-off-by: Stephen Carter <scarter@pivotal.io>

add experimental ops files for deploying locket component

---

operations/tcp-routing-gcp.yml

Signed-off-by: Edwin Xie <exie@pivotal.io>
Necessary going forward for the next routing release. TCP Router will fail to deploy without this key. For isolation segments.

Default tcp_router to use the 'default-tcp' router_group [#142640697]

---

operations/tcp-routing-gcp.yml

When I am deploying with tcp routing, I want the cc worker to be able to speak to the routing api.  This commit adds the necessary properties to the cc-worker job.
Story:
https://www.pivotaltracker.com/story/show/143322377

cc-worker has properties to use routing api

---

cf-deployment.yml

We will need this change as part of this story: [#143355551](https://www.pivotaltracker.com/story/show/143355551) in order to support isolation segments with Gorouter.
@aaronshurley && @flawedmatrix

Add routing.router_groups.read scope to gorouter UAA client

---

operations/test/add-persistent-isolation-segment-diego-cell.yml
operations/windows-cell.yml

Related to [cf-deployment/113](https://github.com/cloudfoundry/cf-deployment/pull/113), this applies the new asset upload/download credentials to a couple of ops-files that move the Diego rep job to a different location.
[finishes #141164981]
Signed-off-by: Danny Cao <dcao@us.ibm.com>

Add asset TLS credentials to Diego ops-files.

---

cf-deployment.yml

Enabling the server allows the operator to collect profiling data
from the Golang runtime and to change the lager log-level dynamically.
The port (17019) is in the conventional 170xx range and will not
collide with an existing known port.

Enable garden debug server

---

cf-deployment.yml

Update uaa configuration to pass new configuration validations
These changes follow those previously submitted for cf-release 
https://github.com/cf-identity/cf-release/commit/de6f6f0612dfe8a77333bc422167e6dc25db166c
[#141162355] https://www.pivotaltracker.com/story/show/141162355
Signed-off-by: bsekar <bharath.sekar@ge.com>

Fix clients that failed uaa manifest validation

---

cf-deployment.yml

* Otherwise `rq` fails to parse the yaml
Signed-off-by: Emily Casey <ecasey@pivotal.io>

Defines yml anchor diego_bbs_client_properties before using it

---

README.md

Before this change, the README referenced `$PWD` without mentioning which directory the user should be in when running that comand.

Be more precise on where to find bosh-lite CA cert

---

cf-deployment.yml
operations/bosh-lite.yml
operations/enable-local-route-emitters-windows-cell.yml
operations/enable-local-route-emitters.yml
operations/use-only-local-route-emitters-windows-cell.yml
operations/use-only-local-route-emitters.yml
operations/windows-cell.yml

* empty out existing operations files for backwards compatibility
[#142672579]
Signed-off-by: James Myers <jfmyers9@gmail.com>

deploy route-emitters in local mode by default

---

operations/experimental/enable-local-route-emitter-tcp-windows.yml
operations/experimental/enable-local-route-emitter-tcp.yml

There are a number of dependencies for these ops files.
- Both depend on operations/tcp-routing-gcp.yml
- operations/enable-local-route-emitters.yml for
enable-local-route-emitters-tcp.yml
- windows-cell.yml and local-route-emitter-windows ops files for windows
tcp ops file.
[This PR](https://github.com/cloudfoundry/cf-deployment/pull/130) should take care of the local-route-emitter dependencies.
This also does not currently work on bosh-lite out of the box, since the
bosh-lite cloud config does not have the VM extension
`internet-required`
[#142583351]
Signed-off-by: Chris Piraino <cpiraino@pivotal.io>

add experimental ops files for local route emitter emitting TCP routes

---

cf-deployment.yml

This is no longer needed due to the new way of doing routing isolation segments.
See story at:
https://www.pivotaltracker.com/story/show/143925653
Signed-off-by: Jonathan Berkhahn <jaberkha@us.ibm.com>

Remove read scope from gorouter & tcp-router

---

operations/bypass-cc-bridge.yml

add ops file to bypass CC bridge
- this enables the temporary flags that enable mTLS communication between
CC and Diego
- as a result, the stager, nsync, and tps-listener functionalities are now handled by
CC, so we can remove these jobs from the cc-bridge template
- these flags are turned on in the api, cc-worker, and cc-clock vms
[#139962927]

Add ops file to bypass CC bridge

---

operations/experimental/enable-local-route-emitter-tcp-windows.yml

* we don't expect users to deploy windows cells without linux cells
* this change allows users to apply both local tcp emitter ops files
with no error
[#142583351]
Signed-off-by: James Myers <jfmyers9@gmail.com>

only remove global tcp emitter in linux operations file

---

cf-deployment.yml

Hi,
This is the first of a pair of PRs to add support for new split-links in the consul-release.
This PR ignores the new links from consul-release, which will allow us to cut a new release without breaking users of cf-deployment. We ran it through our CI using my fork and were able to get a successful deployment + CATs run.
Please note that we are blocked on cutting said new release of consul-release until this PR is merged.
Thanks!
Dave && Gen

Ignore split consul-release links (for now).

---

cf-deployment.yml

Hi,
Sorry to do this to y'all, but apparently our local testing of our last PR wasn't thorough enough to catch a problem with a collision between the alias we had used for the old consul link and the name of one of the new consul links. This PR changes the alias used for the old single link from consul-release. We have carefully tested a deployment with this change and confirmed that it works as desired.
Thanks!
Dave

Rename the alias for the old consul link

---

cf-deployment.yml
operations/tcp-routing-gcp.yml
operations/test/add-persistent-isolation-segment-diego-cell.yml
operations/windows-cell.yml

Hi,
This is the follow-up PR to this [PR](https://github.com/cloudfoundry/cf-deployment/pull/149) to use the new split consul links from consul-release and ignore the old consul link.
Thanks!
Gen & Christian
cc @christianang

Use new consul links instead of monolithic link.

---

cf-deployment.yml
operations/experimental/use-cf-networking.yml
operations/tcp-routing-gcp.yml
operations/test/add-persistent-isolation-segment-diego-cell.yml
operations/windows-cell.yml

Following up this PR: https://github.com/cloudfoundry/cf-deployment/pull/151
[Consul-release v167](https://github.com/cloudfoundry-incubator/consul-release/releases/tag/v167) no longer provides/consumes monolithic `consul` link. We can now remove the `consul` link from the manifest.
Thanks,
Christian

Remove reference to monolthic consul link

---

operations/experimental/use-cf-networking.yml

CF networking no longer uses flannel or etcd
We will not be supporting flannel going forward.
This now matches [the opsfile in our repo](https://github.com/cloudfoundry-incubator/cf-networking-release/blob/develop/manifest-generation/opsfiles/cf-networking.yml), except that this one has the release version pinned to `0.24.0`, where as ours uses `latest`.

Update use-cf-networking opsfile to use silk

---

operations/experimental/use-cf-networking-postgres.yml

Useful for BOSH-lite in particular.
This ops file should be used in combination with the
use-cf-networking.yml ops file, and applied after it.
[#145777061]
Signed-off-by: David McClure <dmcclure@pivotal.io>

Add ops file for cf-networking with postgres

---

cf-deployment.yml

- the cc-clock needs to be able to hit the Routing API whenever it is
enabled for the CC api
[#147064255](https://www.pivotaltracker.com/story/show/147064255)
Signed-off-by: Tim Downey <tdowney@pivotal.io>

Enable routing_api on cc-clock job

---

cf-deployment.yml

Works around metron instances consuming excessive CPU awaiting a doppler instance
[#147348607]
Signed-off-by: Andrew Poydence <apoydence@pivotal.io>

Deploy doppler earlier

---

operations/windows-cell.yml

Now that Window stemcells are available on bosh.io the Windows opsfile can be versioned with a specific stemcell version that is known to work
This update should probably correspond to bumping the opsfile stemcell automatically when there are new releases of the stemcell
(GCP stemcell can be found [here](http://bosh.io/stemcells/bosh-google-kvm-windows2012R2-go_agent))

Use specific windows stemcell version

---

operations/community/use-haproxy.yml

Fixes wrong credentials when running smoke-tests errand
```
[2017-07-20 13:26:01.74 (UTC)]> cf auth admin [REDACTED]
API endpoint: https://api.xxx
Authenticating...
FAILED
Credentials were rejected, please try again.
```

Fix invalid admin password in use-haproxy ops file

---

operations/experimental/secure-service-credentials.yml

This PR adds an ops file, which enables secure service credentials delivery with CredHub.

Add secure-service-credentials ops file

---

operations/experimental/backup-restore.yml

When the release is uploaded to bosh.io this will be updated to use that instead of the github release url.

Adding backup-restore opsfile using github release

---

cf-deployment.yml

- tls_pem replaces ssl_cert and ssl_key
- tls_pem is a list of cert and key pairs in pem format.
The first element is the default cert which allows gorouter
to preserve the existing behaviour.
Note: merging this PR requires coordination with routing-release including the following commit in a final release:
https://github.com/cloudfoundry-incubator/routing-release/commit/73d4773b30c0a8a0bc6102e9c7e7a0ba3a8c8211 
Signed-off-by: Aaron Hurley <ahurley@pivotal.io>

Add tls_pem to support SNI for gorouter

---

cf-deployment.yml

This depends on the next version of CAPI Release (1.39.0).

Add api route emitter health check

---

operations/experimental/deploy-bosh-backup-restore.yml

As mentioned in https://github.com/cloudfoundry/cf-deployment/pull/193

Updating backup-restore opsfile to use bosh.io url

---

operations/scale-to-one-az.yml

When cc-clock job was added it was left out of the `scale-to-one-az` operation file, because of that our CI, which has only one az, broke. This should fix it.

Add cc-clock in the scale-to-one-az operation file

---

operations/experimental/enable-locket-postgres.yml
operations/experimental/enable-locket.yml
operations/experimental/use-external-locket-db.yml

This allows us to define custom error messages. I'm hoping we can use this to guide deployers towards applying ops-files in the right order.

Add error messages to locket-related ops-files

---

cf-deployment.yml
operations/test/add-persistent-isolation-segment-router.yml

- Now cert_chain and private_key must be specified when providing tls_pem
- This PR must be bumped with corresponding change in routing release
[#150267695]
Signed-off-by: Edwin Xie <exie@pivotal.io>

Update tls_pem to support new format

---

README.md
operations/experimental/bits-service-local.yml
operations/experimental/bits-service-s3.yml
operations/experimental/bits-service-webdav.yml
operations/experimental/bits-service.yml

Here is the first attempt to add bits-service to cf-deployment.
We could not find a way to make sure bits-service job is available before cloud controller is updated with the new config. In spruce we would just insert it somewhere before api job, but ops files syntax only supports appending to arrays for now. As a workaround, we used a two step deployment process: first time we add bits-service job without changing CC config. After bits-service VM is up and running, we update CC config with the second deployment.
As a side note, when changing from one blobstore type to another, we had to manually kick off `rake buildpacks:install` in order to re-create them immediately.
Signed-off-by: Alexander Egurnov <egurnov@de.ibm.com>
Signed-off-by: Steffen Uhlig <Steffen.Uhlig@de.ibm.com> …

Add bits-service operations

---

cf-deployment.yml

The order in this file is the same as the detection order, which matters
since some apps contain files that would match multiple buildpacks.
An example would be a rails 5.1 app. Rails51 will have both a Gemfile
and a package.json. This means both ruby and nodejs would answer 'true'
for 'bin/detect', but we know that such apps should use the ruby
buildpack.
Signed-off-by: Dave Goddard <dave@goddard.id.au>

Re-order buildpacks

---

operations/bosh-lite.yml

Hi @dsabeti, thanks for taking a look at my last PR (#236). Totally see what you're saying - it looks like I'd missed the bosh-lite ops file completely. I was also looking at your master branch instead of develop - seems like things are almost fixed on develop. I just found one small typo in the bosh-lite ops file that prevents the deployment from proceeding - it results in an extra leading `-` ahead of the `diego-ssh-proxy-network-properties` vm_extension. This had me scratching my head for a while since the error message you get back from bosh is to the effect that 'diego-ssh-proxy-network-properties was not found in the cloud-config', which is confusing since it's clearly there. Using `bosh interpolate` to dump out the generated manifest made it clear what was going on though. Anyway, …

Fix replacement of vm_extensions on bosh lite

---

bosh-lite/cloud-config.yml

- Any traffic received by the bosh-lite VM on port 8844 will be routed
to the container with the credhub-lb vm_extension
- This will allow us to test runtime credhub integrations on a bosh-lite
[#150753759](https://www.pivotaltracker.com/story/show/150753759)
Thanks!
Tim && @ljfranklin

Add credhub-lb vm_extension to bosh-lite cloud-config

---

cf-deployment.yml
operations/bosh-lite.yml
operations/test/add-persistent-isolation-segment-router.yml

We've recently completed some work on CAPI ([#136759317](https://www.pivotaltracker.com/story/show/136759317)) to remove unused properties from our component spec files.  This made the following properties in the various Cloud Controller jobs unnecessary.
🚫  **WARNING** 🚫 
Please wait until the CAPI release that contains the necessary spec file changes has made it into `cf-deployment` before merging this.
We expect this will be in `capi-release` **1.42.0**, but please double check with us first.  Thanks!

Remove unused cc properties from worker and clock

---

cf-deployment.yml
operations/aws.yml
operations/bosh-lite.yml
operations/bypass-cc-bridge.yml
operations/change-logging-port-for-aws-elb.yml
operations/community/change-metron-agent-deployment.yml
operations/community/enable-volume-service-nfs.yml
operations/enable-privileged-container-support.yml
operations/experimental/bits-service.yml
operations/experimental/disable-consul-service-registrations-bosh-lite.yml
operations/experimental/disable-consul-service-registrations.yml
operations/experimental/enable-locket.yml
operations/experimental/skip-consul-locks.yml
operations/rename-deployment.yml
operations/rename-network.yml
operations/scale-to-one-az.yml
operations/test/add-persistent-isolation-segment-router.yml
operations/test/use-bosh-dns.yml
operations/use-azure-storage-blobstore.yml
operations/use-blobstore-cdn.yml
operations/use-external-dbs.yml
operations/use-postgres.yml
operations/use-s3-blobstore.yml

- Moves ssh_proxy job to router instance-group
- Moves cc_uploader job to api instance-group
- Moves file_server job to api instance-group
- Consolidates remaining jobs from cc-bridge, cc-clock, and diego-brain instance-groups (cloud_controller_clock; nsync and tps; auctioneer) on new scheduler instance-group

Consolidate VMs (implements #173)

---

operations/experimental/deploy-bosh-backup-restore.yml

Hello from London,
The BBR team has cut a new release. Since the release is not automatically bumped in ci, here is the PR to update it 😸
Chunyi && @gcapizzi

Bump back-and-restore-sdk-release to 1.2.0

---

operations/experimental/secure-service-credentials.yml

[#151230556] CredHub should register a consul address for local communication
Signed-off-by: Kelly Gerritz <kgerritz@pivotal.io>

Add consul configuration to credhub

---

operations/test/add-datadog-firehose-nozzle.yml

PR https://github.com/cloudfoundry/cf-deployment/pull/109 changed the BOSH Lite network name to `default`.

Update network name in Datadog ops-file

---

cf-deployment.yml
operations/experimental/enable-locket-windows2016.yml
operations/experimental/enable-loggregator-v2-windows2016-cell.yml
operations/experimental/enable-prefer-declarative-healthchecks-windows2016.yml
operations/experimental/windows2016-cell.yml
scripts/test

- modifies main manifest to include cflinuxfs2 as a default value for
cc.stacks to make adding stacks in opsfiles easier
- windows-cell opsfile still refers to windows2012R2
[#149927686]
Signed-off-by: Sunjay Bhatia <sbhatia@pivotal.io>
Signed-off-by: Sam Smith <sesmith177@gmail.com>

Add windows2016-cell opsfile

---

operations/experimental/bits-service.yml

Although https://bosh.io/docs/manifest-v2.html#releases says that this is optional, it looks like with BOSH CLI v1 this breaks (no data about BOSH CLI v2). To be safe, adding it here.

Add missing sha1 for bits-service

---

operations/scale-to-one-az.yml

the tcp-router is enabled by default as part of 0.28.0 but the ops file scale-to-one-az doesn't take this into account.

tcp-router is scaled down to a single instance when using one az

---

iaas-support/openstack/README.md
iaas-support/openstack/flavors.yml

due to deploy error:
`Error: CPI error 'Bosh::Clouds::CloudError' with message 'Flavor 'small' should have at least 14Gb of ephemeral disk' in 'create_vm' CPI method`

Increase of small flavor ephemeral disk size to 14GB

---

operations/README.md
operations/experimental/README.md
operations/experimental/use-latest-windows2016-stemcell.yml
operations/use-latest-windows-stemcell.yml
scripts/test

Mirrors the existing `use-latest-stemcell` opsfile for the `default` stemcell
Signed-off-by: Sunjay Bhatia <sbhatia@pivotal.io>

Add use-latest-stemcell opsfiles for windows

---

operations/experimental/windows2016-cell.yml

This is necessary due to a PR to diego-release: https://github.com/cloudfoundry/diego-release/pull/366
Also remove a `version: latest` in the winc section that never should
have made it there
[#151704899]

Add open_bindmounts_acl to windows2016-cell

---

operations/experimental/enable-bpm.yml

The enable-bpm.yml file was not working since it referred to both nsync and stager jobs which have been removed from the cf-deployment.yml
[#152080813] 
- Anoop & Andrew

Remove nsync and stager to mirror cf-deployment

---

runtime-configs/enable-component-syslog.yml

If we want to store these variables in a shared var store, it is helpful for them to be less generically named.
https://www.pivotaltracker.com/story/show/151811590
[#151811590]

Make variable names more specific

---

operations/experimental/use-bosh-dns.yml

- This adds a DNS alias so diego can talk to the iso-seg cell
- Won't hurt anything in non-iso seg environments
[#152045213]
Signed-off-by: Eric Promislow <eric.promislow@suse.com>

Include iso-seg cell DNS record in use-bosh-dns.yml

---

operations/experimental/README.md
operations/experimental/windows2016-cell.yml

This release downloads the required rootfs (`cloudfoundry/windows2016fs` on Docker hub) and installs it on the `windows2016` cell (previously the image was provided in the stemcell). It requires a CF foundation with internet access.
**Note:** There will be a subsequent PR with support for an *offline* release and we will specify the manual steps required to deploy that in the experimental opsfile `README`

Use windows2016fs-online-release for windows 2016 rootfs

---

operations/experimental/README.md
operations/experimental/enable-oci-phase-1.yml
scripts/test-experimental-ops.sh

Deploying with this operation switches garden to creating images in the OCI compatible format.
[#151724164]

Ops file for deploying garden-runc in oci-phase-1

---

cf-deployment.yml

The property `external_host` was removed from cf-mysql release in v35 - https://github.com/cloudfoundry/cf-mysql-release/releases/tag/v35
The MySQL team recommends using this ops file if you require a route for the proxy - https://github.com/cloudfoundry/cf-mysql-deployment/blob/develop/operations/register-proxy-route.yml

Remove unused property

---

operations/use-postgres.yml

`databases.address` is not a property anywhere in the postgres spec: https://github.com/cloudfoundry/postgres-release/blob/develop/jobs/postgres/spec

Remove superfluous property from postgres ops-file

---

operations/experimental/README.md
operations/experimental/use-offline-windows2016fs.yml
scripts/test

Note that the release cannot be hosted on bosh.io. In order to use this
opsfile, a copy of the release must already be uploaded to the director

Add opsfile to use offline windows2016fs-release

---

operations/experimental/windows2016-cell.yml
operations/windows-cell.yml

Uses the [windows-utilities-release](https://github.com/cloudfoundry-incubator/windows-utilities-release) to enable the experimental BOSH ssh feature on windows cells (2012R2 and 2016 separately).

Add enable bosh-ssh to windows2016 opsfile

---

cf-deployment.yml

this property override is no longer necessary for CATS or RATS to pass.
[#152444671]

router does not need to skip ssl validation

---

cf-deployment.yml

From conversations with @zrob we would like bosh deploy/bosh run-errand
to have its own user so as to help CF auditors know who/where to look
for who did what.
With this PR, running `bosh run-errand smoke-tests` will generate
an event with `bosh` as the user:
cf curl /v2/events\?q=type:audit.app.delete-request
...
"entity": {
"type": "audit.app.delete-request",
"actor": "ec5a6b63-27ba-4f3c-a33b-896d6b358dd7",
"actor_type": "user",
"actor_name": "bosh",
"actor_username": "bosh",

explicit 'bosh' cf/uaa admin user; so auditors look in bosh tasks

---

cf-deployment.yml

capi release contains a default value as of this commit: https://github.com/cloudfoundry/capi-release/commit/c686a4a27112eb0f9749210138e9b6fd5de427bd
Note: Do not merge this PR until cf-deployment bumps capi-release to version 1.45

Remove quota definitions

---

operations/addons/example-vars-files/vars-enable-component-syslog.yml
scripts/test-addons-ops.sh

I wanted a nice example to use as a vars file in CI,
(the cf-deployment-concourse-tasks require files,
not command line arguments)
but none existed.
Now one does!
Other interpolation tests use vars files,
and now this one does too!

Switch addon test to use example vars

---

operations/experimental/use-offline-windows2016fs.yml
operations/experimental/windows2016-cell.yml

These releases depend on a stemcell based on the windows server 2016 1709
release
Also adds additional logging for Garden image and network plugins

Update windows2016 releases for 1709 compatibility

---

cf-deployment.yml
operations/experimental/enable-oci-phase-1.yml

- These are now the default values in CAPI release and do not need to be
set explicitly
CAPI story: https://www.pivotaltracker.com/story/show/152623585
Wait until CAPI 1.46 to merge: https://www.pivotaltracker.com/story/show/152730060
Signed-off-by: Greg Cobb <gcobb@pivotal.io>

Stop setting temporary_* flags for bypassing bridge

---

deployment-guide.md

As of recent versions of bbl, some key elements of the bbl state, including terraform state, bosh state, and vars stores, have been broken out into separate files. Users need to persist these files as well as the `bbl-state.json` file.

Update deployment guide to mention bbl state dir

---

operations/scale-database-cluster.yml

- BOSH DNS polls for health every 20s based on the monit status of an
instance group. The proxy process should stay healthy for longer than it reports as healthy to
give it time to be removed from the DNS pool.
Signed-off-by: Nitya Dhanushkodi <ndhanushkodi@pivotal.io>

Introduce a shutdown delay when running in HA mode

---

operations/experimental/use-bosh-dns-for-windows2016-containers.yml

Windows server containers now use 172.30.0.1 as their DNS server instead of 169.254.0.2
This is to enable BOSH DNS for containers via PR: https://github.com/cloudfoundry/bosh-dns-release/pull/14

Use gateway for DNS server in windows2016 containers

---

operations/experimental/disable-consul.yml

Disabling consul for cf-mysql requires a few more changes. The base manifest [enables consul](https://github.com/cloudfoundry/cf-deployment/blob/43e9eb3fa9ab4f1e16659f6ec8f38811e12023a9/cf-deployment.yml#L212) for the mysql proxy, which we do not want in a deployment without consul.
This PR removes the consul specific properties from the proxy job.

cf-mysql consul properties

---

operations/experimental/enable-service-discovery.yml

Move the service-discovery-controller job from router vm to its own instance.
Also bumps cf-app-sd-release to the latest version.
[#154695524]

Move the service-discovery-controller job from router vm to its own

---

cf-deployment.yml

The `login.saml.serviceProviderKey` and
`login.saml.serviceProviderCertificate` properties are deprecated in
favor of `login.saml.keys`:
https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L1017-L1066.

Replace deprecated uaa saml properties.

---

operations/experimental/enable-service-discovery.yml

- only create a new release named cf-app-sd if one does
not already exist
[#154971628]
Signed-off-by: Amelia Downs <adowns@pivotal.io>

fix enable-service-discovery.yml

---

iaas-support/bosh-lite/cloud-config.yml

_As a PM working on a deployment that interacts with cf-deployment,_
_${PM_PERSONA_NAME} would like to be able to use bosh-lite for acceptance without extra steps_
_so that she can accept stories without spending time fixing her environment_
The bosh-lite cloud config [present](https://github.com/cloudfoundry/bosh-deployment/blob/master/warden/cloud-config.yml) in the bosh-deployment repo and specified in the bosh lite [docs](https://bosh.io/docs/bosh-lite) specifies a `default` VM and disk type. These are also present in the bbl cloud config, though cf-deployment doesn't use them.
This PR adds them here, so that work done targeting the default bosh-lite config can coexist on a bosh-lite with cf-d without additional steps on the part of the user.

Add VM type from bosh-deployment cloud config to bosh lite

---

operations/windows-cell.yml

In some scenarios where the size of the cell is small and there are
concurrent DNS resolutions happening (e.g., running WATS in parallel),
we've noticed that the file-server.cf.internal name was not getting
resolved in time, leading to failed DNS lookups. This fixes this
scenario by making DNS cache entries live longer during the CPU spikes.

Update consul service_ttl to keep positive DNS results longer

---

operations/addons/enable-component-syslog.yml

Uses stop instead of ~ because Discard(~) is deprecated. 
http://www.rsyslog.com/doc/master/compatibility/v7compatibility.html#omruleset-and-discard-action-are-deprecated
[#155194490]

Update vcap de-duplication rule

---

operations/experimental/windows2016-cell.yml

This PR updates the `windows2016-cell` to use `groot-windows` instead of the `winc-image` Garden image plugin (which no longer exists).

Use groot on windows

---

cf-deployment.yml

Dropped in diego-release v2.0.0. h/t @sharms

Drop deprecated `use_v2_tls` property on rep

---

deployment-guide.md

@genevieve mentioned on Slack that the correct way to do this is to follow the steps listed [here.](https://github.com/cloudfoundry/bosh-bootloader#generic-steps-for-cloud-foundry-deployment)

bbl create-lbs is not a valid command

---

operations/experimental/windows2016-cell.yml

Required with Diego v2.1.0 (https://www.pivotaltracker.com/story/show/154748808)

Use loggregator v2 api on windows2016

---

operations/experimental/disable-consul-bosh-lite.yml

This change alters the disable-consul/BOSH-Lite "cross-term" operations file to configure the ssh_proxy job not to register as a Consul service. This configuration is present in the disable-consul operations file but is lost when the bosh-lite operations file adds a separate copy of the ssh_proxy job to the router and removes it from the scheduler. When Consul is actually removed from the CF deployment, the ssh-proxy then logs frequently about its failure to register.

Configure ssh_proxy on BOSH-Lite to skip consul

---

iaas-support/softlayer/README.md
iaas-support/softlayer/add-system-domain-dns-alias.yml
scripts/test
scripts/test-iaas-ops.sh

In order to resolve a custom bosh-lite system domain - which is required
when deploying bosh-lite on Softlayer - this commit adds a additional
folder "softlayer" to "iaas-support". This includes the specific
ops and a README file with documentation on how to use the ops file and
why it is required.
Additionally, this commit adds interpolation tests for iaas-support ops
files (currently only the Softlayer specific ops file will be tested).
Signed-off-by: Norman Sutorius <norman.sutorius@de.ibm.com>

Add bosh-lite iaas-support ops file for softlayer

---

cf-deployment.yml

Enables grootfs' swanky new GC behaviour by default
See: https://github.com/cloudfoundry/garden-runc-release/releases/tag/v1.12.0
[#155934143]
Signed-off-by: Tom Godkin <tgodkin@pivotal.io>

Explicitly set default grootfs GC property

---

iaas-support/vsphere/cloud-config-vars.yml
iaas-support/vsphere/cloud-config.yml

As per: http://bosh.io/docs/vsphere-cpi.html#azs
- changed `resource-pool` to `resource_pool`
- added the required datacenter name field

Correct vsphere cloud config cloud_properties section

---

operations/windows-cell.yml

Now that loggregator v2 is enabled by default we can remove the ability to talk to metron via UDP. This change is only required for windows2012R2 as there is no network isolation between apps and BOSH jobs.

Disable incoming udp for windows2012R2 metron agent

---

operations/experimental/README.md
operations/experimental/migrate-cf-mysql-to-pxc.yml
operations/experimental/use-pxc.yml
scripts/test-experimental-ops.sh

* This is for a clean install case where cf-mysql-release was never
used. Ops files for upgrading from cf-mysql-release are coming soon.
[#156242645]
Signed-off-by: Joseph Palermo <jpalermo@pivotal.io>

Add experimental ops file to use pxc-release for a mysql database

---

operations/experimental/migrate-cf-mysql-to-pxc.yml
operations/experimental/use-pxc.yml

We realized that changing the link types in pxc to `mysql-clustered` caused those consuming those links to remap them using `provides` and `consumes` statements. This is undesirable in the long term so we've revered them back to types of `mysql`. This does mean we must remap the links during the migration do to the now ambiguous two links of type `mysql`. These changes are included in this PR.

Update pxc to v0.3.0

---

operations/README.md
operations/example-vars-files/vars-use-s3-custom-blobstore.yml
operations/use-s3-custom-blobstore.yml
scripts/test-standard-ops.sh

Can be used with non-AWS S3 providers such as minio. Based on operations/use-s3-blobstore.yml.

operations: Custom S3 provider for blobstore

---

operations/experimental/migrate-cf-mysql-to-pxc.yml
operations/experimental/use-pxc.yml

This makes the proxy dashboard available at `proxy.SYSTEM_DOMAIN` so operators can see the number of connections to the database.
There are also two fixes included:
- The `common_name` was not specified for the internal galera server certificate, which is needed when generated by credhub. 
- The `bootstrap` errand job needs the `mysql` link to be specified when performing the migration since there are two jobs that supply it.

pxc proxy dashboard and credhub fix

---

operations/experimental/bits-service.yml

This is the first step for the migration from bits-service.* URLs to bits.* and requires a recreation of the certificate.
For more context, see: https://github.com/cloudfoundry/cf-deployment/pull/475

Allow bits-service.* and bits.* for Bits-Service certificate

---

operations/experimental/bits-service-local.yml
operations/experimental/bits-service-s3.yml
operations/experimental/bits-service-webdav.yml
operations/experimental/bits-service.yml
operations/experimental/enable-bits-service-consul.yml
operations/experimental/use-bosh-dns-rename-network-and-deployment.yml
operations/experimental/use-bosh-dns.yml

As discussed with @dsabeti and @staylor14, we're trying to move the Bits-Service to a separate VM to see if memory constraints or similar cause the slow push times. Once we found the root cause, we will try to co-locate the Bits-Service again on `api`.

Move bits-service into a separate VM

---

cf-deployment.yml
operations/experimental/perm-service.yml

This is a resubmit of #495 but this time against the `develop` branch.
Bosh interpolate doesn't provide a great way to append to a string, so we'd like to ask to merge this scope in the mainline `cf-deployment.yml`
When https://github.com/cloudfoundry/uaa-release/pull/89 is merged and the new uaa release makes it into `cf-deployment`, we'll consider putting this into an opsfile.
[#157527204]
Signed-off-by: Nick Wei <nwei@pivotal.io>

Add perm.admin scope to the CF CLI admin user

---

operations/experimental/perm-service.yml

This version solves the incompatibility between perm-release and pxc-release 0.0.6.
NOTE:
- when redeploying this version of perm to an existing environment where perm deployment previously failed, one MUST first drop the "perm_migrations" table.

Bumped perm to version 0.0.7

---

operations/experimental/migrate-cf-mysql-to-pxc.yml
operations/experimental/use-pxc.yml

Enable Core CF components to talk to PXC using TLS
- Add addresses for cc, diego, routing, and uaa so that they use
hostnames which match the mysql_server_cert's common name
- Pass the pxc_server_ca to cc, diego, and routing via bosh properties
- Add the ca_certs job from os-conf release to the uaa instance group, and use that job to pass the pxc_server_ca to uaa
- Turn on DB TLS for components which require it to be explicitly
enabled
Note that this does not turn on TLS for cf-networking. The ability to pass cf-networking the DB CA is only enabled in cf-networking 2.0, which is not yet in cf-deployment.
UAA does not support passing the CA via a bosh property, and recommended using the os-conf release to pass the CA.

Add db tls for pxc

---

operations/experimental/migrate-cf-mysql-to-pxc.yml

The use-pxc ops file gets bumped by Rel Int CI, the migrate ops file does not.
Signed-off-by: Nitya Dhanushkodi <ndhanushkodi@pivotal.io>

Bump pxc release to 0.6.0 in migration ops file

---

operations/experimental/use-pxc.yml

We noticed that the `use-pxc.yml` file was using a different port than `cf-deployment.yml` and the `migrate-cf-mysql-to-pxc.yml` ops file.

Update pxc database ports to match cf-mysql port

---

operations/enable-nfs-volume-service.yml

The mapfs package used to be part of nfs-volume-release, but we started to use it in other contexts, so we factored it out into its own release.  As a result, the nfs ops file needs to pull in mapfs-release and deploy mapfs as a separate (do-nothing) job.  This is similar to the pattern we have already established in cf-cli-release
- modify enable-nfs-volume-service to use the latest nfs release and include the required mapfs job from mapfs-release [#157857957]

Include required mapfs job in enable nfs-volume-service.yml

---

operations/experimental/bits-service.yml
operations/experimental/enable-bits-service-consul.yml
operations/experimental/use-bosh-dns-rename-network-and-deployment.yml
operations/experimental/use-bosh-dns.yml

As discussed with @dsabeti  in https://github.com/cloudfoundry/cf-deployment/pull/475 and specifically in https://github.com/cloudfoundry/cf-deployment/pull/475#issuecomment-386092041, now that certificates allow both `bits.*` and `bits-service.*`, and operators should have re-created these certs as noted in [release notes 1.31.0](https://github.com/cloudfoundry/cf-deployment/releases/tag/v1.31.0), we can actually change the URLs.
@dsabeti I hope this is how you intended this to go. Otherwise, please advise.

 Rename URLs from bits-service.* to bits.*

---

operations/experimental/README.md
operations/experimental/use-garden-containerd.yml
scripts/test-experimental-ops.sh

Allows garden to use its experimental containerd mode. When enabled, Garden will create containers via containerd.

Allow garden to use containerd

---

operations/experimental/perm-service.yml

This bug prevents migrator from working because dashed-client-id does not match underscored_client_id in the other section of the manifest.
[#157952485]

Make the client id match its definition (dash/underscore)

---

operations/experimental/migrate-cf-mysql-to-pxc.yml
operations/experimental/perm-service-with-pxc-release.yml
operations/experimental/secure-service-credentials-with-pxc-release.yml
operations/experimental/use-pxc.yml

This PR renames the mysql job to pxc-mysql to match changes in pxc-release >= 0.8.0

upgrade pxc to 0.9.0

---

operations/experimental/perm-service.yml

This adds UAA client credentials for CC to make API calls to Perm service.

add cc to perm uaa credentials in perm service ops file

---

operations/experimental/perm-service.yml

In the future, we want to use these client creds to allow perm monitor to access the perm resource server.

added a perm monitor client to UAA

---

operations/use-external-dbs.yml

Under the latest version of bosh, setting a link that isn't specified in the job spec raises an error, like this: `Job 'locket' in instance group 'diego-api' specifies consumers in the manifest but the job does not define any consumers in the release spec`. This patch drops the unused database link from the locket job in the external database operations file.

Drop unused locket database link.

---

operations/experimental/use-log-cache.yml

Potential fix for https://github.com/cloudfoundry/cf-deployment/issues/520
SHA1 is from https://bosh.io/releases/github.com/cloudfoundry/log-cache-release?all=1

switch sha to sha1

---

cf-deployment.yml
operations/bosh-lite.yml

Starting with [Diego v2.5.0](https://github.com/cloudfoundry/diego-release/releases/tag/v2.5.0), the default value for this property is 8443, so this manifest property is now redundant.
[#155735780]

Remove redundant UAA port from Diego SSH-proxy job

---

operations/experimental/migrate-cf-mysql-to-pxc.yml
operations/experimental/use-pxc.yml

UAA v60 now supports accepting certs for TLS to the DB via a bosh property. This PR enables TLS from UAA to the mysql DB.
It also changes the mysql CA Cert to be referenced through the `mysql_server_certificate` variable's CA property. This is the same CA as the previous `pxc_server_ca` certificate property, but referenced in a way that enables easier CA rotation.

Add UAA TLS

---

operations/experimental/perm-service.yml

perm-release spec addresses UAA's ca certs by `uaa.tls.ca_certs`.
This fix will make the deployment with `auth` feature-flag succeed.
[#158535821]

Place the ca_certs property in the tls namespace

---

operations/use-bosh-dns-rename-network-and-deployment.yml

Looks like we missed the deployment name override for the uaa bosh dns alias.
cc @LinuxBozo

Override default deployment name in uaa dns alias.

---

cf-deployment.yml
operations/experimental/disable-consul.yml
operations/experimental/migrate-cf-mysql-to-pxc.yml
operations/experimental/use-pxc.yml

We are removing outdated consul code from the mysql proxy job. This PR changes cf-deployment to use regular consul service discovery for consul instead of the special code inside the proxy.
Update database proxy job to use consul service discovery in a way more consistent with other jobs.
No

mysql proxy job uses regular consul service discovery

---

operations/experimental/secure-service-credentials.yml

[#158431599] key_properties and connection_properties hashes are necessary
Moved the credhub.encryption.keys.encryption_password to be credhub.encryption.keys.key_properties.encryption_password.
This change is needed because Credhub has made the key_properties nested hash necessary.
https://www.pivotaltracker.com/story/show/158431599 
Credhub has made the key_properties nested hash necessary.
No
@mdelillo

Add key_properties nested hash to cf-deployment ops file

---

operations/test/add-datadog-firehose-nozzle.yml

_Describe the change and why it's needed._
Datadog now manages this release. 
Unaware
_Does this introduce changes that would require operators to take action in order to deploy without a failure?_
Examples of breaking changes:
- changes the name of a job or instance group
- deletes a job or instance group
- moves a job to a different instance group
- changes the name of a credential

please upgrade datadog nozzle version away from cf-attic

---

operations/experimental/migrate-cf-mysql-to-pxc.yml
operations/experimental/use-pxc.yml

This PR updates the PXC opsfiles to update policy-server and silk-controller to use TLS connections with PXC.
/cc @tylerschultz

Add cf networking components to pxc opsfiles

---

operations/experimental/enable-bpm.yml

For additional security benefits (running rootless), run the garden job in a container using BPM.
In order to run Garden in BPM containers Garden needs specific network
settings:
* Diego talks to Garden via a socket
* Garden talks to a networking server that runs outside the Garden
container over a dedicated socket
* The networking server invokes the external networker
Story in Garden team's backlog: https://www.pivotaltracker.com/story/show/158594265
Related PR in cf-networking release: https://github.com/cloudfoundry/cf-networking-release/pull/45
* Experimentally run Garden in BPM
No 
@danail-branekov @julz @BooleanCat

Experimentally enable BPM for Garden

---

operations/experimental/migrate-cf-mysql-to-pxc.yml
operations/experimental/use-pxc.yml

Upgrade pxc release to 0.11.0. This includes a large set of job and property refactorings.
This will probably be the final release before we ship pxc 1.0.0
pxc release upgraded from 0.10.0 to 0.11.0. Custom ops files that configure database properties will need to update their paths to match the new jobs and property names.
There are a good number of job and property changes. However, no action is required if the Operator is using manifests and ops files straight from cf-deployment. If they have custom ops files that change database properties, they may need to be updated.

Upgrade pxc to 0.11.0

---

cf-deployment.yml

- This change adds the new cc.database_encryption key properties in
addition to the legacy cc.db_encryption_key property to enable rotation
of these keys in the future
- The upcoming version of capi-release will ship with a BOSH errand that lets operators rotate all keys in their ccdb
- Currently it is required that the legacy `cc.db_encryption_key`
property also remain present until operators have updated all encrypted
values that were encrypted with this key
To better demonstrate this, the following database query shows some of the apps in a ccdb after this change. All five apps were pushed before deploying with these changes. After the deployment, I updated the app `static-1` and it's sensitive content was re-encrypted with the labeled key. All untouched apps are still encrypted with …

Add cc.database_encryption properties to Cloud Controller jobs

---

operations/addons/enable-component-syslog.yml
operations/addons/example-vars-files/vars-enable-component-syslog.yml

Consistency in variable names, and some other little cleanup.
Please note that, unfortunately, this is a breaking change. I recommend you go to 3.0 for just this, but hey, not my call.
When merging the branch to switch to TLS for syslog, the relint team discovered that permitted peer was necessary to work with Papertrail, and added a variable for it.
Cats don't test syslog, though, so.
- **BREAKING** we've corrected the `permitted_peer` variable used in the `enable-component-syslog.md` ops-file to `syslog_permitted_peer` for consistency with other variable names. You will need to manually move your variables to the new names in your credhub/vars-store.
**Yes.**
It's just me!
I don't like this form, it took longer to fill out than to make the change.

**BREAKING**: Improve syslog vars

---

cf-deployment.yml

Signed-off-by: Hunter Williams <huwilliams@pivotal.io>
This adds the missing log-cache-scheduler job back to the scheduler instance_group. This is needed for log cache to function correctly and was inadvertently missed in the original pull request.
Conversation with Gary Liu in Slack here:
https://pivotal.slack.com/archives/CBF2AU6A0/p1532984626000150
Add the log-cache-scheduler job to the scheduler instance_grou
No.
/cc @hdub2 @syslxg

Add the log-cache-scheduler job to the scheduler instance_group

---

cf-deployment.yml

The cloud controller now supports rotating its database keys by running
`bosh run-errand rotate-cc-database-key`. The CC team believes this 
should be a core feature in CF. This PR defines the errand only.
Tracker stories
- [Define the errand](https://www.pivotaltracker.com/story/show/158675271)
- [Key rotation support](https://www.pivotaltracker.com/story/show/157206210)
We are working on a [story to write the docs for this feature](https://www.pivotaltracker.com/story/show/158734896). The release notes should link to the detailed docs.
No.
@ericpromislow @dwfrank @zrob

Add a bosh errand to rotate cc encryption keys

---

operations/enable-nfs-ldap.yml

[#158704386](https://www.pivotaltracker.com/story/show/158704386)
Signed-off-by: Maria Shaldibina <mshaldibina@pivotal.io>
Change to the nfs ldap ops file in cf-deployment to disallow uid, gid for security purposes. 
[158704386](https://www.pivotaltracker.com/story/show/158704386)
NFS with LDAP is not being tested in cf-acceptance-tests in releng pipeline. It is tested in PATS acceptance tests in our pipeline though.
In order to be properly secured by ldap, nfsv3driver should disallow setting uid and gid in service bindings. That way, nobody can register a rogue broker that specifies a uid directly, and nfsv3driver will only use uids that have been resolved by ldap.
No this isn't a breaking …

Change to the nfs ldap ops file in cf-deployment to disallow uid, gid for security purposes. 

---

operations/test/add-persistent-isolation-segment-diego-cell-bosh-lite.yml
scripts/test-test-ops.sh

This change makes the `add-persistent-isolation-segment-diego-cell.yml` compatible with bosh-lite environments.
Diego's rep job was recently modified to use a `set-kernel-parameters` property to control whether or not it will try and manipulate certain kernel parameters. By default, that property is true. However, it does not work on bosh-lite and will prevent deploys from succeeding.
Adds a new ops file that can be used along with `add-persistent-isolation-segment-diego-cell.yml` to deploy an isolated diego cell on bosh-lite.
In fact, it fixes a breaking change (for bosh-lite, admittedly)
Neither?

add ops file for bosh-lite compatibility

---

operations/experimental/perm-service.yml

NOTE: this PR is a followup to 2 other PRs that have been closed: #578 #562
What is this change about?
Describe the change and why it's needed.
With this change PERM will start sending server-side metrics.
Please provide contextual information.
https://www.pivotaltracker.com/story/show/157413837
Has a cf-deployment including this change passed our cf-acceptance-tests?
[ X ] YES
NO
How should this change be described in cf-deployment release notes?
Something brief that conveys the change and is written with the Operator audience in mind.
See previous release notes for examples.
"Perm service now emits server-side metrics."
Does this PR introduce a breaking change?
Does this introduce changes that would require operators to take action in order to deploy without a failure?
NO
Examples of …

add statsd injector to the perm service

---

operations/disable-log-cache.yml

Remove log-cache-scheduler from the scheduler if disable-log-cache ops file is used

Remove log-cache-scheduler

---

cf-deployment.yml

These changes are required for compatibility with Log Cache 1.4.3
Export node health metrics for Log Cache 1.4.3
No.
/cc @hdub2 @attack @colins

Add Log Cache properties for 1.4.3

---

operations/experimental/README.md
operations/experimental/set-cpu-weight.yml
scripts/test-experimental-ops.sh

**Note** Please merge after cf-deployment is using Diego 2.16.0.
This ops file instructs diego to create garden containers whose CPU
shares are directly proportional to container memory.
Co-authored-by: Ed King <eking@pivotal.io>
This ops-file instructs diego to ignore cloud controller's CPU share calculation and make CPU shares for Garden containers directly proportional to the container's memory limit.
This is part of Garden's work to make CPU allocation and metrics better. [See doc here.](https://docs.google.com/document/d/16TvBsZSInjy7zoboSQWRJo30lmxr07tvd40_GzpfD3I/edit?usp=sharing)
App developers and operators shouldn't notice any difference after deploying with this feature enabled.
This may have undesirable side effects for staging containers, but our hypothesis is that nothing …

Add experimental use-cpu-weight ops file

---

operations/experimental/README.md
operations/experimental/use-logcache-for-cloud-controller-app-stats.yml
scripts/test-experimental-ops.sh

Cloud Controller typically uses Traffic Controller to get container metrics (cpu/disk/memory utilization) for running apps. Loggregator has introduced a new component, Log Cache, that they would like us to use instead. 
This ops file configures CC to use Log Cache instead of Traffic Controller, so we can start kicking the tyres on Log Cache for container metrics.
Here is the story in the CAPI backlog: https://www.pivotaltracker.com/story/show/159042437
We haven't run CATS against it yet, but we're working on it. 😄 
Adds a new experimental ops-file for using Log Cache to provide container metrics on the CC API.
Nope.
@Gerg @zrob @ericpromislow

Ops file for configuring CC to use Log Cache instead of Traffic Controller for app container metrics

---

operations/disable-log-cache.yml

Fix for https://github.com/cloudfoundry/cf-deployment/issues/602
`operations/disable-log-cache.yml` - Removes log-cache-expvar-forwarder job from the scheduler instance group.
No
Given it fixes a deployment error when using this ops file.

Fix disable-log-cache.yml to remove schedulers log-cache-expvar-forwarder job

---

cf-deployment.yml
operations/bosh-lite.yml

Fix errors and clean up redundancies after completion of [#159833429](https://www.pivotaltracker.com/story/show/159833429).
Ensure consistently human-readable log format for Diego components by default and remove unnecessary operations from cf-deployment repo.
Fix minor omissions in updating Diego log timestamps from unix epoch to the human readable rfc3339 format.
No.
@cloudfoundry/cf-diego

Fix Diego component logging configuration

---

operations/experimental/migrate-cf-mysql-to-pxc.yml

Now that Secure Service Credentials is default, the migrate-to-pxc ops
file needs to enable the credhub seeded database for the migration to
work with credhub.
[#160329126]
Add a seeded database for credhub to pxc in the migrate-from-cf-mysql-to-pxc ops file.
When the secure service credentials were made default, the contents of the operations/experimental/secure-service-credentials-with-pxc-release.yml ops file was moved into use-pxc.yml but was missed in the migrate-from-cf-mysql-to-pxc.yml ops file. This PR fixes that. See this commit: https://github.com/cloudfoundry/cf-deployment/commit/625d4b5cb7756ee3c89de74acdb39157cf19214a
Our pipeline is broken without this fix and we can't deploy without it, so we can't get to running cats. However, it's a very small, standard change to add a …

Add Credhub DB to PXC Migration Ops File

---

operations/enable-nfs-volume-service.yml

[#159639152](https://www.pivotaltracker.com/story/show/159639152)
Register NFS service broker in the same errand that is pushing the service broker instead of using separate`broker-registrar` errand from `broker-registrar` release.
https://www.pivotaltracker.com/story/show/159639152
It passed our PATS (persi acceptance tests).
Updated Ops-files
`operations/enable-nfs-volume-service.yml` - registers NFS service broker by default in the `nfsbrokerpush` errand, removes extra `nfs-broker-registrar` errand.
`nfs-broker-registrar` errand is now removed.
It will actually decrease VM footprint.
@julian-hj …

Register nfs broker in push errand, not separate errand

---

operations/test/add-persistent-isolation-segment-router.yml

This PR is to enable TLS from the gorouter to backends by default on the iso-seg router (this is already setup on the non-iso-seg router).
The routing team is working on a story to enable TLS by default, from the gorouter to the backends. This means that `router.ca_certs` is now required.
https://www.pivotaltracker.com/story/show/158512757
The iso-seg router now trusts the same CA certs as the non-iso-seg router, allowing TLS to backends to be enabled by default.
No. Without this PR, teams' CIs may break when the next routing-release is published.
@KauzClay @nhsieh

add `router.ca_certs` to iso-seg-router

---

operations/example-vars-files/vars-migrate-nfsbroker-mysql-to-credhub.yml
operations/experimental/README.md
operations/experimental/enable-nfs-volume-service-credhub.yml
operations/experimental/migrate-nfsbroker-mysql-to-credhub.yml
scripts/test-experimental-ops.sh

We've been using these ops-files in our CI along with the old `secure-service-credentials.yml` experimental ops-file to enable credhub support for NFS volume services.
Now that credhub is GA in v4.0.0, we want to add them to cf-d as experimental ops-files.
[#160035537](https://www.pivotaltracker.com/story/show/160035537)
New Ops-files
- operations/experimental/enable-nfs-volume-service-credhub.yml
- NFS volume release v1.4.0 introduces support for using CredHub instead of a SQL database to store state for nfs broker. CredHub has the advantage that it encrypts data at rest and is therefore a more secure store for service instance and service binding metadata. CredHub is required if you are using the LDAP integration, and you wish to specify user credentials at service instance creation …

Add ops-files to add credhub support to NFS volume services

---

cf-deployment.yml

Add the Reverse Log Proxy (RLP) Gateway to the log-api instance group.
This job exposes the Loggregator V2 API over Server Sent Events (SSE) via the go-router. This will provide users a more flexible API to stream logs and metrics.
* https://github.com/cloudfoundry/loggregator-release#rlp-gateway
* https://github.com/cloudfoundry/loggregator-release/blob/3a8f04a2e250ac6b15fcf8903cb5e0fe90fdac05/jobs/reverse_log_proxy_gateway/spec
Exposes the Loggregator V2 API via the go-router using JSON over Server Sent Events.
No. Loggregator V1 API will continue to work as normal.
@ahevenor @MasslessParticle

Add RLP Gateway to log-api

---

cf-deployment.yml
operations/disable-log-cache.yml

Signed-off-by: Mark Gangl <mgangl@pivotal.io>
We're removing the experimental group_reader feature, and so we're dropping it from cf-deployment.
The feature was unstable and addressing a problem for which we have not established much customer support.
Feel free to reach out to us in #cf-log-cache on the cloudfoundry slack. This should just remove one process from the set that runs on the doppler VM.
Log-cache is removing the experimental group_reader feature
No - it precludes it. `log-cache` v1.4.5 will no longer contain this job, so it needs to be dropped from the manifest before that version bump.
@hdub2 @attack @toddboom @cloudfoundry/cf-log-cache

remove log-cache group-reader job

---

operations/experimental/enable-smb-volume-service.yml

Register the SMB volume service broker when the azurefilebrokerpush errand is run.
This change mirrors a [recent change](https://github.com/cloudfoundry/cf-deployment/pull/592) to make the same change to the nfsbrokerpush errand configuration. It eliminates the need to either use a separate errand to do this, or to do it manually.
This should have been included in the [PR](https://github.com/cloudfoundry/cf-deployment/pull/593) that added this ops-file. See also the [corresponding PR](https://github.com/cloudfoundry/cf-deployment/pull/592) to change the nfsbrokerpush.
Updated Ops-files
operations/experimental/enable-smb-volume-service.yml - Register the SMB volume service broker when the azurefilebrokerpush errand is run.
@julian-hj @paulcwarren @mariash

Register SMB Volume Service Broker when the azurefilebrokerpush Errand is Run

---

operations/test/README.md
operations/test/add-oidc-provider.yml
scripts/test-test-ops.sh

Signed-off-by: Magesh Kumar Murali <mmurali@pivotal.io>
Co-authored-by: Ryan Tang  <rtang@pivotal.io>
This change allows for testing of a UAA with users authenticated with an OIDC provider.
We are trying to share some test Cloud Foundry environments with other teams. Both of our teams view cf-deployment as the canonical place for ops files.
We had a couple of in-person conversations. Happy to provide more written docs if that helps.
https://www.pivotaltracker.com/story/show/160692210
Should not affect cf-deployment release notes. Though we can say "added an ops file to help platform developers test their system" if we'd like.
No
- [X ] **Urgent** - unblocks current or future work
@ryantang  @tjvman @abbyachau

Add oidc provider ops file [#160692210]

---

cf-deployment.yml
operations/bosh-lite.yml

This configuration has the same effect as the operations at https://github.com/cloudfoundry/cf-deployment/blob/v4.5.0/operations/experimental/disable-consul.yml#L50-L67 and https://github.com/cloudfoundry/cf-deployment/blob/v4.5.0/operations/experimental/disable-consul-bosh-lite.yml#L4-L6, which were omitted in https://github.com/cloudfoundry/cf-deployment/commit/3cab0090afdfc9ec5e0f701800e24d3309d4051f when applying these operations to cf-deployment.yml.
Without opting these components out of maintaining their own service registrations, they produce a significant volume of logs about their failure to connect to a local Consul agent.
cf-deployment v5.0.0 removed Consul entirely.
Bug fix: Opt Diego components out of Consul service registration now that Consul has been removed.
No.
Given …

Disable components from registering as Consul services

---

cf-deployment.yml

This was removed from capi-release in v1.54.0
Removing an unused property.
The property is unused, so it's just cruft.
https://github.com/cloudfoundry/capi-release/releases/tag/1.54.0
I don't think it's worth mentioning.
Not unless people are still using really old capi-release versions somehow.
I think it's just me :)

Remove unused tps.listener_enabled property

---

cf-deployment.yml

Required for users to set network policies; without this, container
networking isn't usable. Note: we could drop this property if
https://github.com/cloudfoundry/uaa-release/pull/96 is merged.
Chatted on slack about this with @staylor14

Enable SpaceDeveloper self-service for network policies

---

cf-deployment.yml

_This adds new SLI metrics for log-cache's PromQL endpoints._
_log-cache allows users to subset the metrics that are forwarded from the component; we added these metrics in recent releases of log-cache, and need this manifest change for them to be visible._
_Export additional log-cache SLI metrics._
_Nope, just exports some gauges._
@jtuchscherer @toddboom @hdub2

Export new log-cache metrics

---

operations/experimental/README.md
operations/experimental/add-deployment-updater-external-db.yml
scripts/test-experimental.sh

Adds an experimental ops-file for beta users who wish to use the
cc_deployment_updater (enables usage of the experimental zero downtime
app deployment feature) component with an external database
The beta users that we expect to be trying out this feature use an external database for CCDB.
* https://www.pivotaltracker.com/story/show/161331073
* https://www.pivotaltracker.com/n/projects/2090335/stories/161233272
* https://github.com/cloudfoundry/cf-deployment/pull/630
Did not run CATS. I'm currently deploying an environment that uses an external Google Cloud SQL db and will test the zero downtime app push command explicitly.
**Edit:** Yep it works.
Same way you're describing https://github.com/cloudfoundry/cf-deployment/pull/630, but say it will enable the use of an external database.
No …

Add ops-file for using an external db with cc_deployment_updater

---

cf-deployment.yml
scripts/semantic-tests.sh

This change switches CA references introduced by #535 to be from their respective CA variables rather than certificate variables.
This reduces log availability downtime during CA rotation.
More information about why CAs need to be referenced this way is described in #305 
N/A
Switch log cache CA references to reduce log availability downtime during CA rotation.
No

Log cache certs reference variables from CA variables

---

operations/experimental/README.md
operations/experimental/enable-create-swap-delete.yml
scripts/test-experimental-ops.sh

This ops file changes the default `vm_strategy` for all instance groups in cf-deployment to use `create-swap-delete`, instead of the default `delete-create` strategy.
To allow users to experiment with the `create-swap-delete` feature and provide user feedback to the BOSH team.
https://www.pivotaltracker.com/story/show/160155346
**Note**: This change does not update the resulting deployment. Only the process by which instances are updated. This should not have any effect on the cf-acceptance-tests.
Add experimental operation file that configures the default [`vm_strategy`](https://bosh.io/docs/changing-deployment-vm-strategy/) to be `create-swap-delete`. This operations file requires BOSH director `v267.7+`
No.
The VM footprint will be temporarily increased during a deploy. This is due to …

Add enable-create-swap-delete ops file

---

deployment-guide.md
operations/use-offline-windows2016fs.yml

Deployment guide needs updating with regards to bosh-lite and credhub.
1.) I believe there are two credhubs, you must target the right one.
- in PCF
- in BOSH
credhub api --server api.bosh-lite.com - this goes to
Name:    api.bosh-lite.com
Address: 10.244.0.34
must use IP and correct port for local bosh-lite Director to target, e.g.
192.168.50.6:8844
2.) setting correct cert in the env var for credhub login, with a newline between certs
3.) to login to credhub you need to set
export CREDHUB_CLIENT=credhub-admin
4.) add some detail about logging in as cf admin
see above.
it's a doc only fix.
no
no urgency from my end
@emalm

fix bosh-lite directions for credhub

---

cf-deployment.yml

The loggregator agent has moved all its metrics to a health endpoint served up by the `expvar` package in the Golang stdlib. This PR adds a job to read the metrics from that endpoint and send them to the loggregator system.
This change requires `loggregator-agent-release` v3.0 which has not yet been cut. We will be cutting that release soon.
We believe that Loggregator component metrics should be accessible when there are issues with reading metrics from the firehose.
* https://www.pivotaltracker.com/story/show/161400481
* https://www.pivotaltracker.com/story/show/161236250
Metrics can be retrieved from the Loggregator Agent via HTTP by sending a `GET` request to `localhost:<PPROF_PORT>/debug/vars` from the local VM.
Yes and no, all the metrics should appear in the firehose as they were …

Add expvar forwarder job to loggregator-agent addon

---

operations/enable-nfs-volume-service.yml

This PR updates the `enable-nfs-volume-service.yml` ops-file to use UAA client credentials instead of the admin user.
Using username/password authentication in non-interactive clients like bosh errands means that it is not possible to turn on 2 factor authentication. This change helps pave the way for cf operators to enable 2 factor authentication.
[#159187003](https://www.pivotaltracker.com/story/show/159187003)
Maybe not at all? Once all errands are similarly modified, probably it would make sense to put a generic message in the release notes saying something like "Operators can now enable two factor authentication in CF without breaking errand execution" or something like that.
@julian-hj @paulcwarren @mariash 
Let us know if you have any questions.
Thanks,
Dave

Use Client Credentials in nfsbrokerpush Errand

---

operations/experimental/use-compiled-releases-windows.yml

The binary buildpack does not need to be overridden as a source release if you are using Windows cells with compiled releases for Linux cells as the buildpack packages do not get compiled on Windows vms.
It reduces the overhead in the `use-compiled-releases-windows.yml` opsfile and reduces the number of packages that need to be compiled from source if using compiled releases and Windows cells.
This change should not affect CATs, it is a deploy time change.
No

The binary buildpack does not get compiled on Windows vms

---

cf-deployment.yml
operations/experimental/README.md
operations/experimental/enable-bpm-garden.yml
operations/experimental/rootless-containers.yml
operations/experimental/use-garden-containerd.yml
operations/experimental/use-native-garden-runc-runner.yml
operations/test/add-persistent-isolation-segment-diego-cell.yml
scripts/test-experimental.sh

This will default the runtime wrapper in Garden to containerd.
Containerd has been running in PWS for some time and this is part of our plan to fully move this to be the default container lifecycle management.
https://www.pivotaltracker.com/story/show/161584005
Operators will likely not notice anything unless they are currently using the operations/experimental/use-garden-containerd.yml ops file.
Containerd is not yet compatible with garden bpm or rootless, so containerd will be disabled if either use-bpm-garden.yml or rootless-containers.yml is specified.
No
@BooleanCat

Default experimental_containerd_mode to true

---

interpolated
operations/test/add-persistent-isolation-segment-infrastructure-metrics.yml
operations/test/add-persistent-isolation-segment-logging-system.yml
operations/test/add-persistent-isolation-segment-syslog-drain.yml
operations/test/alter-router-for-log-agent.yml
scripts/test-test.sh

Add ops files to deploy an isolated Loggregator.
To enable isolated Loggregator
https://www.pivotaltracker.com/story/show/160112181
- Adds ops files to deploy isolated Loggregator and Syslog Drains
No
If the ops files are used, a whole isolated Loggregator will deployed
@MasslessParticle @jtuchscherer

Loggregator iso segments

---

cf-deployment.yml

[#162127063]
Signed-off-by: Todd Persen <tpersen@pivotal.io>
Log Cache v2.0.2 has a metrics forwarder that no longer writes directly back into Log Cache, but writes to the local Loggregator Agent instead. This change is necessary to make generated metrics pick up the same system-level tags as all other components.
This change creates a new certificate to be used when communicating to the local Loggregator Agent.
This feature was added in this story:
https://www.pivotaltracker.com/story/show/157580025
And the breaking change was discussed here:
https://pivotal.slack.com/archives/CBF2AU6A0/p1542756218138100
Adds Loggregator Agent certificate for Log Cache metrics forwarder
No.
/cc @jtuchscherer @pianohacker

Upgrade Log Cache to v2.0.2 and fix certificates

---

cf-deployment.yml

With commit https://github.com/cloudfoundry/routing-release/commit/50862b402322cf902d4784d675f8ea4fe2ca2fee (part of routing-release starting with version 0.181.0) the property `router.backends.enable_tls` has been removed (defaults to `true`).

Remove obsolete property router.backends.enable_tls

---

cf-deployment.yml

[#162317690]
We broke our metrics when we went to the expvar forwarder by not attaching origin tags
This ensures that the loggregator agent metrics don't change
https://www.pivotaltracker.com/story/show/162317690
Emit loggregator agent logs with origin tag.
No
@jtuchscherer

add origin to logging metrics

---

operations/windows1803-cell.yml
operations/windows2016-cell.yml

[#162249894](https://www.pivotaltracker.com/story/show/162249894)
Co-authored-by: Ben Fickes <bfickes@pivotal.io>
Adds the new 'windows' stack associated binary-buildpack and hwc-buildpack
To install the 'windows' stack associated buildpack on windows by default.
Installs the 'windows' stack associated binary-buildpack and hwc-buildpack
No

Add windows stack-associated hwc-buildpack and binary-buildpacks

---

cf-deployment.yml
operations/experimental/enable-bpm-garden.yml
operations/experimental/rootless-containers.yml
operations/experimental/use-native-garden-runc-runner.yml

Changes the property `experimental_containerd_mode` to `containerd_mode`.
The property `experimental_containerd_mode` is marked as deprecated since `garden-runc v1.17.1` (https://github.com/cloudfoundry/garden-runc-release/commit/49044b1135ba58c2b84145b6a20ff90d42526449) and for that a new property was introduced.
Switches deprecated property `experimental_containerd_mode` to `containerd_mode`.
No

Changes depricated experimental_containerd_mode property

---

operations/enable-nfs-ldap.yml
operations/enable-nfs-volume-service.yml
operations/experimental/enable-nfs-volume-service-credhub.yml
operations/experimental/enable-smb-volume-service.yml

This change configures TLS for NFS and SMB volume services.
As part of the `secure by default` policy, we have exposed the ability to configure the NFS and SMB drivers that run on the Diego cells to use mutual TLS when communicating with the rep process.
https://www.pivotaltracker.com/story/show/160036094
NFS and SMB volume services
- Communication between the `rep` and the NFS and SMB drivers is now secured  through mutual TLS.
@paulcwarren @julian-hj

Volume Services TLS Config

---

operations/experimental/enable-routing-integrity-windows1803.yml
operations/experimental/enable-routing-integrity-windows2016.yml

Now that envoy-release is on bosh.io, we should pull it from there instead of a github release.
bosh.io is the preferred place to pull releases from
While we do have a CF deployed with Envoy on Windows in our pipelines, and push apps to it regularly, we do not technically run CATS against this CF
N/A -- this feature is still very experimental
No

Pull envoy-release from bosh.io

---

cf-deployment.yml

- this can be expensive in certain IaaSs
- bbl version 7+ will only provision 10 ports for
TCP Router on AWS
Co-authored-by: Christopher Hunter <hunter.christopher@icloud.com>
Decreases the number of reservable ports to 10.
It can be expensive in some IaaSs to provision 100 ports.
bosh-bootloader version 7+ will only provision 10 ports for TCP Router on AWS
bosh-bootloader is decreasing the number of provisioned reservable ports for AWS.
TCP Router available reservable ports are now 1024-1033.
If a deployment is using any TCP Router port outside of 1024-1033 range it will break services on those ports.
@cloudfoundry/cf-infrastructure

Use 10 reservable ports instead of 100

---

cf-deployment.yml

~~**NOTE**: The release configuration will need be modified when 
https://github.com/bosh-io/releases/pull/71 is accepted to properly index this release~~(Merged)
Adds NGINX-buildpack-release for cflinuxfs3
To install NGINX-buildpack-release for cflinuxfs3 by default
https://www.pivotaltracker.com/story/show/159444595
~~Currently blocked waiting for bosh.io indexing 
https://github.com/bosh-io/releases/pull/71~~(This has been merged)
See [previous release …

Adds NGINX-buildpack-release and R-buildpack-release for cflinuxfs3

---

cf-deployment.yml
operations/experimental/use-native-garden-runc-runner.yml

This change is removeing the unneeded containerd job form the main cf manifest.
The containerd daemon is now part of the garden job. This is needed so that garden ca run with systemd.
https://www.pivotaltracker.com/story/show/162329293
This change depends on GRR release version greater than 1.17.2 that drops the containerd as a separate job
- operations/experimental/use-native-garden-runc-runner.yml
- no longer needs to remove the contianerd job
Yes it deletes the containerd job
@julz @yulianedyalkova

Remove unneeded containerd job from manifest

---

operations/bits-service/use-bits-service.yml

Don't use deprecated `secret` property in Bits-Service anymore. Instead, use new `active_signing_key`.
The Bits-Service is switching from a non-rotatable secret to a rotatable list of signing keys. The first step is to migrate away from the deprecated `secret` property.
Some context:
- https://docs.google.com/document/d/1jwDRdzJeLaDgJdqDdlI8f3X4Lr49uvUH5Zwa0tc9NJg/edit?disco=AAAACTZ8bqw
- https://www.pivotaltracker.com/story/show/161913277
> Don't use deprecated `secret` property in Bits-Service anymore. Instead, use new `active_signing_key`.
No.
@idev4u

Bits-Service: Use new active_signing_key instead of deprecated secret

---

operations/test/add-persistent-isolation-segment-diego-cell.yml

The experimental flag is deprecated and soon to be removed, I am not sure
how we missed this one when the others were PRed a while ago.
The changed file is under a `test` directory, so it is possible that nobody will notice this change, unless `test` means something else here.
Ensuring everything still works when we retire the old flag shortly.
https://www.pivotaltracker.com/story/show/163145141
https://github.com/cloudfoundry/cf-deployment/pull/680
No

Use correct containerd flag

---

cf-deployment.yml

These properties need to be specified otherwise the credhub link is unusable.
Note, in case you are wondering, because it is required by both the credhub-cli and the credhub Go library to authenticate with UAA, we included the UAA CA certificate.  
As credhub is becoming our default store, we now want to consume the credhub link to populate our brokers (and migrator). 
[#161974894](https://www.pivotaltracker.com/story/show/161974894)
No existing component (including credhub itself) currently uses the link so running CATS would be a no-op so we didn't do it.
Credhub link properties updated to make bosh link consumable.
No
@davewalter @julian-hj

Populate the credhub link properties

---

scripts/test

This PR adds a simple pass/fail message to the bottom of the script that runs the ops-file tests.
It is extremely annoying to have to scroll back through pages of output to verify that all tests have passed when working on a change to an ops-file. It is even more annoying to submit a PR, only to receive an automated response a few minutes later to tell you that one of the tests failed and asking you to fix the problem. Given that the script runs the tests in the background in parallel, failing instantly is out of the question. However, we do know whether all of the tests passed or not via the `$exit_code` variable. This PR simply checks that variable and outputs a simple pass/fail message.
The test script now outputs a simple pass/fail message at the bottom of its output to inform the …

Add Pass/Fail Indicator to "test" Script

---

cf-deployment.yml

[#164153522]
Yes
Getting a uptime metric scraped from log-cache so that it is visible in `cf tail`
Better blackbox testing against log cache an uptime metric that resets indicates it is restarting itself/dropping it's cache
https://www.pivotaltracker.com/story/show/164153522
Add scraping for log-cache uptime metric
No
/cc @toddboom @jtuchscherer

Add uptime metric to log-cache

---

cf-deployment.yml

[#164176942]
The RLP Gateway and the Loggregator Trafficcontroller now do ssl termination and register a secure route with the `route_registrar`
This change is made to increase security by making sure all endpoints are secured
A security review of loggregator surfaced that the external-facing endpoints from RLP Gateway and Trafficcontroller weren't secured.
- https://www.pivotaltracker.com/story/show/163887905
- https://www.pivotaltracker.com/story/show/163888064
_Something brief that conveys the change and is written with the Operator …

add ssl termination to log-api

---

operations/experimental/add-syslog-agent.yml

[#164346923]
Signed-off-by: Tom Chen <tochen@pivotal.io>
Yes.
We noticed that our syslog_agent job had some incorrect metrics. The ingress dropped metric was missing `metric_version` tag and that egress dropped was missing `direction: egress` tag.
To make the syslog_agent job metrics correct
https://www.pivotaltracker.com/story/show/164346923
Currently the syslog_agent job has some incorrect metrics. This change will add to the ingress dropped metric a `metric_version` tag and to the egress dropped a `direction: egress` tag. 
No
@jtuchscherer, @johncornish, @chentom88

syslog_agent: fix ingress dropped and egress dropped metrics

---

cf-deployment.yml

Support ServeTLS from auth proxy when log-cache-release is bumped.
Signed-off-by: Todd Persen <tpersen@pivotal.io>
Yes
Support ServeTLS from auth proxy when log-cache-release is bumped.
Otherwise it will break - security fix, we did not phase it.
Lock down log-cache-cf-auth-proxy to https
https://www.pivotaltracker.com/story/show/163887949
Restrict log-cache connections through gorouter to TLS only
_Does this introduce changes that would require operators to take action in order to deploy without a failure?_
No. But it is a requirement to support upcoming LogCache `2.2.0`
_It's helpful to tag a few …

Restrict log-cache-cf-auth-proxy to TLS only

---

operations/enable-nfs-volume-service.yml

Adds the seeded database back into the base enable-nfs-volume ops file.
Fixes [this issue](https://github.com/cloudfoundry/nfs-volume-release/issues/47). 
[#164438618](https://www.pivotaltracker.com/story/show/164438618)
No, but it has passed through the persi "heleus" pipeline that tests "first product install" (of the base nfs ops file) and also migration of service instances and bindings from a sql store to a credhub store. 
n/a
No
@davewalter @julian-hj

Add the nfs-broker seeded database back into the base nfs ops file

---

cf-deployment.yml

Yes.
This change adds the `clients.read` permission to the CF admin user.
The CF CLI has implemented (but not released) changes to the set-org-role and set-space-role commands that allow setting roles on clients. These changes include validation that a provided client actually exists in the UAA, which requires the logged-in user to have one of a set of specific scopes (one option is `clients.read`).
Relevant stories:
https://www.pivotaltracker.com/story/show/159967411
https://www.pivotaltracker.com/story/show/159969560
`clients.read` scope has been added to the CF Admin user's permissions. 
No.
@cloudfoundry/cf-cli

Add clients.read permissions to CF admin user

---

operations/windows1803-cell.yml

[#164081245]
Signed-off-by: Natalie Arellano <narellano@pivotal.io>
We created a new job `winc-network-hns-acls` that behaves identically to `winc-network-1803`. We want to be able to use the generically-named one in place of `winc-network-1803` for versions 1803 and above.
Now that we have Windows 2019, we would like to use a generic name for this job, rather than using the `winc-network-1803` name which can get confusing. Eventually, we would like to get rid of the `winc-network-1803` job all together, in favor of the generic version. …

Use winc-network-hns-acls in 1803

---

cf-deployment.yml

yup
Moving the `scheduler` instance group to immediately after the `cc-worker` instance group
The cloud_controller_ng job may run migrations against ccdb when it is deployed. This means that for a time the cloud_controller_clock and cloud_controller_worker are running older code against this newly migrated ccdb. This is typically fine, but if those jobs are stopped and restarted for any reason (monit restarts, someone inadvertently running bbr during the deploy), then they cannot come up successfully because their older code is out of date with the db.
To minimize the time between the cloud_controller_ng job deploying and the scheduler (with cloud_controller_clock job) deploying we should have them deploy immediately after cloud_controller.
Change deploy order of scheduler instance group …

Scheduler instance group deploys immediately after api

---

operations/experimental/README.md
operations/experimental/add-metric-store.yml
scripts/test-experimental.sh

[#164122999]
Signed-off-by: Johanna Ratliff <josmith@pivotal.io>
Add Metric Store as an option within CF.
Persistence and queryability (PromQL) of metrics downstream from Loggregator.
Add Metric Store - persistent storage for metrics downstream from Loggregator - as an experimental ops file.
N
/cc @toddboom @jtuchscherer

Add experimental option to have a metric store in CF

---

cf-deployment.yml
operations/bosh-lite.yml

This is a breaking change PR, intended for the next major release of cf-deployment
Yes
As a CF operator, I expect that cf-deployment disables the ssh-proxy HTTP healthcheck server by default. In the past, TCP load-balancers on GCP were requiring their backends to expose an HTTP health-check, so in order to be able to use one to load-balance across the Diego ssh-proxy instances we needed them to present such a health-check. TCP load-balancers on GCP haven't needed the HTTP healthcheck for a while now.
We no longer need to expose an insecure HTTP healthcheck for ssh-proxy. This make the the ecosystem more robust and secure.
Original Story to turn on HTTP Healthcheck: (https://www.pivotaltracker.com/story/show/130616967)
Removal of the HTTP healthcheck: …

Disable ssh-proxy HTTP healthcheck server

---

operations/experimental/add-metric-store.yml

Adding generation for new cert variables in the `add-metric-store.yml` ops file so that gateway can securely communicate with it's other localhost processes. 
Locking down everything to TLS for security purposes. This will also help in the future if the processes are split out onto different containers.
_Helpful Links_
https://www.pivotaltracker.com/story/show/165422726
Metric Store Gateway now requires TLS.
No - once the new ops file is used, the new properties that were added for metric-store will be automatically generated. 
Breaking change for metric store, not for CF.
/cc @jtuchscherer @colins @attack

Add certs to allow internal tls for metric-store-gateway job

---

cf-deployment.yml

Remove logging configuration that's no longer necessary
There is some logging config that's still in cf-deployment.yml that's not used by the release anymore.
This issue is related to this post https://www.pivotalk.io/t/voodoo-cf-deployments-shrinking-heads-with-bosh-interpolate/29085. This config created confusion about where the address comes from
Remove unnecessary logging configuration
NO
@hev

remove unnecessary config

---

operations/backup-and-restore/skip-backup-restore-droplets-and-packages.yml
operations/backup-and-restore/skip-backup-restore-droplets.yml

Yes
This is a follow up PR from https://github.com/cloudfoundry/cf-deployment/pull/694, in the latest capi-release https://github.com/cloudfoundry/capi-release/releases/tag/1.79.0 the job properties `directories_to_backup` was renamed to `select_directories_to_backup`, this PR updated the ops-files that set these properties to respect the renames.
Addressing property renames in the capi-release
Previous PR for this feature: https://github.com/cloudfoundry/cf-deployment/pull/694
Update BBR selective backup ops-files to accommodate property changes in the capi-release.
No
cc @cloudfoundry/bosh-backup-and-restore-team

Update skip droplets and packages ops files

---

cf-deployment.yml

Yes
Gorouter talks to UAA via SSL.
The next release of UAA will only accept SSL traffic
https://www.pivotaltracker.com/story/show/164837062
Configure Gorouter to talk to UAA via SSL
No -- change should not be externally visible
This will prevent the next release of UAA from causing CATs to fail in your pipelines
My pair is @shamus 
PMs @wc22222 @dbeneke

Gorouter talks to UAA via SSL.

---

operations/community/change-metron-agent-deployment.yml

Yes
Since the loggregator forwarder_agent is now GA in cf-deployment,
in order to set a custom deployment name for metrics, we'll have to
set the deployment name deployment/tag property in the loggr-forwarder-agent properties.
Without this change, customizing the deployment tag on envelopes emitted from your deployment is not possible.
Slack thread: https://cloudfoundry.slack.com/archives/C02HCCXV5/p1556733079023100
Updates `operations/community/change-metron-agent-deployment.yml` to properly change the loggregator agent deployment name.
No
@cf-diego

Set deployment name tag in loggr-forwarder-agent

---

cf-deployment.yml

Co-authored-by: Christopher Brown <cbrown@pivotal.io>
Yes
Enabling mTLS for routing api endpoint. 
We need this PR to get merged first before we cut our next Routing Release that will use these properties. Hopefully this will avoid breaking your pipelines if you pull in our new Routing Release automatically :)
One step in the effort to add mTLS everywhere in CF
[#165404264](https://www.pivotaltracker.com/story/show/165404264) for more detail.
Enabled mTLS endpoint for routing api service component
No
Not on fire, but need to add this with corresponding new Routing-Release version in order it continue work on Route-Emitter mTLS to Routing-API with Diego
@adobley @xoebus

Enable mTLS for routing api

---

operations/experimental/README.md
operations/experimental/enable-nginx-routing-integrity-windows2019.yml
scripts/test-experimental.sh
units/tests/experimental_test/operations_test.go

Yes
Experimental ops-file to enable route integrity using nginx on Windows 2019 cells.
Users want route integrity.
https://www.pivotaltracker.com/story/show/167029192
New experimental ops-file. Enable route integrity using nginx in place of envoy on Windows 2019 diego cells.
No
https://bosh.io/releases/github.com/cloudfoundry-incubator/envoy-nginx-release?all=1

Add ops-file for enabling route integrity with nginx on windows 2019.

---

operations/README.md
operations/example-vars-files/vars-use-alicloud-oss-blobstore-to-multi-bucket.yml
operations/use-alicloud-oss-blobstore-to-multi-bucket.yml
scripts/test-operations.sh
units/tests/standard_test/operations_test.go

This PR aims to expand the alibaba cloud oss blobstore bucket to multiple.
Enables fog aliyun to operate with multiple buckets as it has already done for bits aliyun.
Bits service for AliCloud utilizes multiple buckets to persist the files. This approach is totally different from fog configuration, which accepts a single bucket only to persist all kinds of resources. This PR aligns fog configuration with bits accepted configuration to enable a smooth transition from bits to fog adapter.
The reason for that is because the bits service is going to be in maintenance mode and deprecated from CF.
Alibaba Cloud

feat(alibaba cloud): add a new oss blobstore manifest for multi bucket

---

operations/test/add-datadog-firehose-nozzle.yml

Update `datadog-firehose-nozzle-release` to latest (version `74`). We saw metrics not being sent to DataDog with the `develop` and `release-candidate` branches of `cf-deployment.
- Diego backlog story: https://www.pivotaltracker.com/story/show/167622640
This change should be documented in the section of the release notes that notes down updated releases/stemcells.
@cloudfoundry/cf-diego

Update datadog-firehose-nozzle-release to latest

---

cf-deployment.yml
operations/backup-and-restore/skip-backup-restore-droplets-and-packages.yml
operations/backup-and-restore/skip-backup-restore-droplets.yml
scripts/test
scripts/test-backup-and-restore.sh
units/tests/backup_and_restore_test/operations_test.go

Yes
Fixing bug on our skipping droplets/packages ops file that template the `singleton-blobstore` instance group even when external blobstore is enabled. 
Will create extra VMs unnecessarily for user when using skip droplets/packages ops files
https://www.pivotaltracker.com/story/show/164664190
Fix bug that skipping droplets/packages for backup will always template singleton blobstore.
Nope
@gmrodgers
@glestaris 
@cloudfoundry/bosh-backup-and-restore-team

Selective backups bug fix internal

---

operations/backup-and-restore/enable-restore-smb-broker.yml

BOSH does not support using bosh links provided from a non-co-located errand.
Fix issue with consuming bosh links failing
As a Alana I can use the `enable-restore-smb-broker.yml` ops file to ensure my B+R solution works
It turns out that BOSH doesn't support consuming links from errands that ARENT co-located. So our current `enable-restore-smb-broker.yml` ops file is currently consuming bosh links from the non-co-located errand job. What this PR does is change it to consume from the co-located errand instead.
Fix issue where `enable-restore-smb-broker.yml` fails to consume bosh links 

Consume smbbrokerpush bosh links from co-located errand

---

cf-deployment.yml

As part of the initiative to encrypt all platform traffic we're adding TLS for the external policy server API. See [#167305073](https://www.pivotaltracker.com/story/show/167305073) for more details.
Networking Story: [#167305073](https://www.pivotaltracker.com/story/show/167305073)
It has passed the relevant networking acceptance tests.
Traffic between gorouter and the external policy server api is now over TLS by default
@angelachin @KauzClay @adobley @keshav-pivotal

Enable TLS to external policy server by default

---

cf-deployment.yml

Removing credhub.authentication.uaa.verification_key as it is obsolete and was removed over 1 year ago in credhub  https://github.com/pivotal-cf/credhub-release/commit/245fb799d137b170ffb45a04415e1351e56417ad
Cleanup for cf-deployment
as it is unused by credhub and just a leftover to clean up.
not needed
@philippthun

Removing credhub.authentication.uaa.verification_key

---

operations/experimental/README.md
operations/experimental/add-syslog-agent.yml

The add-syslog-agent ops file as it exists would lead to duplicate logs being sent to syslog drains. This changes that ops file to remove cf-syslog-drain release and its jobs so this doesn't happen.
Duplicated logs send to syslog drains
https://www.pivotaltracker.com/story/show/168468829
Changes the add-syslog-agent experimental ops file to do the following:
- remove the adapter instance group
- remove the scheduler job from the scheduler instance group
- remove the cf-syslog-drain release
- remove all variables associated with the removed jobs
- add-syslog-agent experimental ops file now removes cf-syslog-drain release
@MasslessParticle @pianohacker @mjseaman

Remove syslog drain release in add-syslog-agent ops file

---

operations/experimental/use-logcache-syslog-ingress-windows1803.yml
operations/experimental/use-logcache-syslog-ingress.yml

Signed-off-by: Caitlyn Yu <cyu@pivotal.io>
This change allows the syslog agent to securely communicate with the log-cache syslog server.
The user is now able to use syslog-log-cache without disabling tls validation
Update use-logcache-syslog-ingress ops files to enable secure communication between the syslog agent and the log cache syslog server.
@MasslessParticle @pianohacker @mjseaman

add drain_ca_cert to use-logcache-syslog-ingress ops files

---

PULL_REQUEST_TEMPLATE.md

Often times, I (PM) am unable to verify the changes in the acceptance environment. Because of the missing AC, either we accept the change in good faith or pair with devs to find the closest AC (which may or may not be true AC).
With this change, PR authors provide AC for their changes. The AC should be identical to AC they used in their own CI environment. In addition, it forces teams to think ahead on how-to verify changes using cli (or cats).
Furthermore, I removed redundant questions and questions that can be inferred by looking at the PR itself. E.g. ` Does this PR introduce a new BOSH release into the base cf-deployment.yml manifest or any ops-files` can be inferred by looking at the PR itself. There is no further action required by the author (On the contrary, RelInt will need to …

Add request for acceptance criteria to the PR template

---

operations/experimental/add-system-metrics-agent-windows1803.yml
operations/experimental/add-system-metrics-agent.yml

System Metrics Scraper and Agent now comes from its own release and remove the Leadership Election release.
This is a refactor of the releases.
* https://www.pivotaltracker.com/story/show/169020450
This change removes a release and adds a new release to opsfiles in `operations/experimental`
System metrics agent now comes from it's own release. Leadership Election release is removed.
This includes https://bosh.io/releases/github.com/cloudfoundry/system-metrics-release?all=1.
1. `bosh instances -p` and ensure that the `loggr-system-metrics-agent` is on all the VMs and that `loggr-system-metric-scraper` is on the Scheduler VMs. 
@MasslessParticle @pianohacker @mjseaman

Switch to system-metrics-release and update the scraper and agent

---

operations/experimental/use-logcache-syslog-ingress-windows1803.yml
operations/experimental/use-logcache-syslog-ingress.yml

[#168526399]
Update property name for aggregate drains in Syslog Agent
Alana is unclear what the `non_app_drains` property in Syslog Agent is.
https://www.pivotaltracker.com/story/show/169017178
`non_app_drains` property is now `aggregate_drains`. This is a name change to remove any confusion about what this property is, which is a single drain destination for all metrics and app logs. 
`bosh -d cf manifest` and see the new property name in Syslog Agent
slack: loggregator

Update syslog agent property name to aggregate_drains

---

cf-deployment.yml

Add metrics certs to rlp gateway so loggregator-release can be bumped
Metrics are securely emitted from RLP gateway
https://release-integration.ci.cf-app.com/teams/main/pipelines/update-releases/jobs/update-loggregator/builds/62
It's minor enough that it maybe shouldn't be but
- Add Metrics to RLP gateway
CF deploy succeeds with newest version of loggregator (106.2.0)
@MasslessParticle @mjseaman @pianohacker @chentom88 @heycait

add rlp metrics certs

---

operations/backup-and-restore/enable-restore-nfs-broker.yml
operations/enable-nfs-volume-service.yml

- the errand job does not always exist when the errand is not running
- prevents 'Can't generate network settings without an IP' error
[#169331853](https://www.pivotaltracker.com/story/show/169331853)
Co-authored-by: Dennis Leon <dleon@pivotal.io>
Co-authored-by: Lisa Cho <lcho@pivotal.io>
During a deploy (new & upgraded) that contains a `bbr-nfsbroker` job which consumes a link from the `nfsbroker` that lives in an `instance_group` of type `errand`, the bosh deploy fails with the following error message:
`Can't generate network settings without an IP`
have a successful deployment
https://www.pivotaltracker.com/story/show/169331853
- [ X ] YES
- [ X ] NO
> nfsbrokerpush provided link no longer causes …

Make sure that the bbr backup job uses the link on the colocated nfsbrokerpush job

---

operations/test/add-datadog-firehose-nozzle.yml

This fixes an issue where deploying metric-store along with older
versions of datadog-firehose-nozzle-release doesn't work. The issue has
been fixed in later versions.
Bump datadog-firehose-nozzle release to 77 which has a fix for metric store to work.
No customer. We are seeing an issue with metric store not working because it is not compatible with old datadog-firehose-nozzle release.
Update datadog-firehose-nozzle release to v77
Deploy metric-store with datadog using ops-files:
- operations/test/add-datadog-firehose-nozzle.yml
- operations/use-metric-store.yml
Metrics should appear in datadog.
@cf-diego

Update datadog release to latest (v77)

---

operations/use-metric-store.yml

The 2 properties described here are not valid in the metric-store
release and the intended values are the default values in metric-store
job. This causes the yaml parse failure when using this opsfile.
egress_port -> port
health_addr -> health_port
> Fix metric-store opsfile
Using the opsfile in cf-deployment should succeed. 
- [] **Urgent** - unblocks current or future work
@cf-diego

Fix metric-store opsfile to be a usable opsfile

---

cf-deployment.yml

This is to replace the old health_check script in the UAA release with the new path so both bosh_dns and route_registrar are using the same script.  In the future UAA will remove the bin/health_check script as they are identical
To make sure we have only a single script in sync between route_registrar and bosh_dns to ensure both paths to UAA is consistently applied as to the health of UAA.
https://github.com/cloudfoundry/uaa-release/pull/147
Was the PR to add the healthy script to UAA.  This "requires" UAA 74.11 where the new script exists.
- [] YES - please choose the category from below. Feel free to provide additional details.
The healthy check script in UAA for route_registry is in a new path.  In …

Use the same healthy script for route_registrar in UAA

---

cf-deployment.yml

> _Please describe the change._
Removing a vestigal password
Alana is confused why this unused property is generated.
Closing out old issues on the capi-release repo, we found this one: https://github.com/cloudfoundry/capi-release/issues/59
Remove `cc_internal_api_password` as mTLS is now used in its stead.
CATs is fine
@cloudfoundry/cf-capi

Capi remove internal api pw

---

operations/use-metric-store.yml

Add new certs and properties required by metric-store 1.3.0
https://cloudfoundry.slack.com/archives/CHB7BCZS8/p1582670875000300
Bump metric-store-release to v1.3.0
As CF admin user, this command:
```
curl -H "Authorization: $(cf oauth-token)" -sS -G https://metric-store.$SYSTEM_DOMAIN/api/v1/query --data-urlencode 'query=up'
```
should return json-encoded metrics (and not an error)
@heidmotron @attack @thepeterstone @josephgee

Update metric store release 1.3.0

---

cf-deployment.yml
scripts/fixtures/unit-test-vars-store.yml

found that there is an unused variable called "cf_bosh_password".  This is just removing that from the manifests.
Nothing really just cleaning up the manifest so there are no unused variables.
removed unused variable cf_bosh_password
`bosh variables | grep cf_bosh_password`  will return no variables.

Remove unused variable cf_bosh_password

---

cf-deployment.yml
scripts/fixtures/unit-test-vars-store.yml

Reverts cloudfoundry/cf-deployment#872
The change is a breaking change to the main manifest. We can put this in v13 backlog.

Revert "Remove unused variable cf_bosh_password"

---

cf-deployment.yml

Instead of using IPs as addresses for nats servers, use hostnames instead. This allows nats to take advantage of bosh dns, so that when instances roll, IP changes won't cause breaks in communication. This also lets us avoid nats split-brain problems by taking advantage of bosh dns to prefix hostnames with instance ids, so that each nats server can have a unique dns resolution.
Alana is able to roll NATS vms with minimal interruption to control plane communication.
This is more of an enhancement, though we did have a related inquiry recently that we happen to fix with this, we believe: https://cloudfoundry.slack.com/archives/CFX13JK7B/p1586368934041100
Mainly, this was done in response to a recent [failure](https://release-integration.ci.cf-app.com/teams/main/pipelines/update-releases/jobs/ …

Enhancement: NATS servers are now addressed with hostnames instead of IP addresses

---

cf-deployment.yml
operations/experimental/fast-deploy-with-downtime-and-danger.yml

***please do not merge until capi-release 1.93.0*** (wait for https://bosh.io/releases/github.com/cloudfoundry/capi-release?version=1.93.0 to resolve)
There was a bug in the ccng worker that made it not wait for migrations to finish running. We hotfixed that bug by setting the api to be serial: true in cfd, but have since made the worker block properly. 
properly fixes this issue:
https://github.com/cloudfoundry/capi-release/issues/165
[https://www.pivotaltracker.com/story/show/171394832]
Co-authored-by: Connor Braa <cbraa@pivotal.io>
Co-authored-by: Renee Chu <rchu@pivotal.io>
This fixes the issue linked above and speeds up all cf-d deployments.
allow api and worker instance groups to deploy in parallel
When I deploy a CFD, I can see the cc-worker and api vms deploying simultaneously. …

allow api and worker instance groups to deploy in parallel

---

operations/experimental/README.md
operations/experimental/disable-uaa-client-redirect-uri-legacy-matching-mode.yml
units/tests/experimental_test/operations.yml

This is an ops file we added to cf-deployment but it is
unlikely to ever be turned on.
[#167764897]
Signed-off-by: Joshua Casey <jcasey@pivotal.io>
Remove experimental ops file that is unused by UAA.
This is an ops file we added to cf-deployment but it is
unlikely to ever be turned on.
https://www.pivotaltracker.com/story/show/167764897
This is an ops file we added to cf-deployment but it is
unlikely to ever be turned on.
file is gone.
@joshuatcasey
@dbeneke

Remove experimental ops file that is unused by UAA.

---

cf-deployment.yml
operations/experimental/fast-deploy-with-downtime-and-danger.yml

> Remove extra `serial: true` statements to speed parallel deployment.
> deploy fast enough...   A test deployment I performed went from ~27 minutes to ~21 minutes. Actual deployment times gains will vary depending on instance counts and other included ops files.
The changes were successfully BOSH deployed. At that point all the components are working so there should be no reason for behavior to change.
> Better optimize deployment parallelization to speed the deployment processes.
> Behavior should remain the same. Deployment time should be reduced.

Optimize deployment parallelization

---

operations/experimental/use-logcache-syslog-ingress.yml

[#172918521]
This adds a more general BOSH DNS alternative name to allow access to logcache syslog server from service instances.
In a world where Loggregator v1/v2 firehose is disabled and the shared-nothing loggregator architecture is in place, service authors still want to expose metrics about their services. To do this, logcache must be set up as a syslog server and include a SAN for the BOSH dns query that is used to connect to the logcache syslog-server.
https://www.pivotaltracker.com/story/show/172918521
Service authors can send metrics to Logcache when Loggregator V1/V2 firehose is disabled. 
Confirm `log_cache_syslog_tls` certificate includes `q-s3.doppler.default.cf.bosh` in the SAN.
1. `credhub find -n log_cache_syslog_tls` then `credhub get -n ... -j | jq -r .value.certificate …

Add general BOSH dns query as SAN to logcache syslog server

---

operations/experimental/use-logcache-syslog-ingress.yml

[#172918521]
This is related to the previous PR here: https://github.com/cloudfoundry/cf-deployment/pull/887. 
We did some further testing and it appears we also have to add the Common Name to the Alternative Name list if you add the `alternative_names` field. This adds the original BOSH DNS alias as a SAN to continue to allow access to log-cache syslog server from within the CF deployment. 
In a world where Loggregator v1/v2 firehose is disabled and the shared-nothing loggregator architecture is in place, components still want to expose their metrics. To do this, logcache must be set up as a syslog server and include a SAN for the internal BOSH alias that is used to connect to the logcache syslog-server.
https://www.pivotaltracker.com/story/show/172918521
Service authors can send metrics …

Add CN to SAN for logcache syslog-server

---

operations/experimental/use-logcache-syslog-ingress-windows2019.yml
operations/experimental/use-logcache-syslog-ingress.yml

Update loggregator agent
- allow users to specify ssl ciphers for syslog and https drains
* update opsfile for log-cache to still use internal ciphers
- allow users to remove structured data from drains
- allow users to specify doppler address for forwarder agent
- Requested because strict ssl requirements don't allow syslog agents to communicate with servers without up to date ciphers.
- requested because syslog data size(cost) reduction can happen when removing structured data
- requested to fit in with unusual deployment configurations. 
- ~bump loggregator agent release to 6.1.0~ Set ssl-strict-internal to true for use-logcache ops files
@pianohacker @MasslessParticle

set ssl-strict-internal to true for use-logcache ops files

---

cf-deployment.yml

Reconcile a new requirement of the cf-smoke-tests instance group for the new major release of cf-smoke-tests. 
Alana is now able to run cf-smoke-tests with the latest supported cf cli.
N.A. this only affects the cf-smoke-tests instance group, which only tests a small base set of functionality.
cf-smoke-tests now runs with cf cli v7
cf-deployment continues to successfully deploy and `bosh run-errand smoke-tests` succeeds after the deploy
cc @jamespollard8 @cloudfoundry/cf-release-integration

Update cf smoke tests release 41.0.0

---

cf-deployment.yml

Even if you scale out CCDB with `operations/scale-database-cluster.yml`, cc_deployment_updater will always reference only CCDB with `index: 0`.
Therefore, cc_deployment_updater becomes down just by the appearance of `index: 0` in Percona XtraDB Cluster is down (Percona XtraDB Cluster is in a healthy state at this time).
This is due to the code below.
https://github.com/cloudfoundry/capi-release/blob/4899333c053273e8a24036c1f803adb70c67218f/jobs/cc_deployment_updater/templates/cloud_controller_ng.yml.erb#L49-L65
Changed cc_deployment_updater to refer to CCDB by ip address to use BOSH DNS record ( `sql-db.service.cf.internal` ).
Alana is now able to use cf even if `index: 0` of CCDB cluster goes down.
N/A
Fix cc_deployment_updater always refers to only one mysql instance even if ccdb is …

Fix cc_deployment_updater always refers to only one mysql instance even if ccdb is scaled out

---

operations/enable-nfs-volume-service.yml
operations/enable-smb-volume-service.yml

Switches the volume services ops files to use cf-cli-v7
Alana is able to deploy volume services without using v6 cli (in the bosh errand script)
https://www.pivotaltracker.com/story/show/173993501
https://www.pivotaltracker.com/story/show/173993537
release notes:
https://github.com/cloudfoundry/nfs-volume-release/releases/tag/v7.1.0
https://github.com/cloudfoundry/smb-volume-release/releases/tag/v3.1.0
Optional ops files for volume services use cf cli v7
1. Deploy cf-deployment with each of these ops files.
Run `bosh run-errand nfsbrokerpush` and `bosh run-errand smbbrokerpush`.
Verify from the errand logs that the errand is using cf cli v7.
@paulcwarren @julian-hj

Volume services ops files use cf-cli v7, bump releases

---

cf-deployment.yml
operations/windows2019-cell.yml

Reduce default configuration log load by increasing `scrape_interval` from the default value of 15s to 60s.
This reduces overall log volume by scraping ~1/4 as often.
https://pivotal-io.atlassian.net/browse/LOGG-44 
Decrease log volume by increasing scrape_interval for system-wide prom_scraper component.
`cf log-meta` should report longer cache duration for similar metrics counts.
@cloudfoundry/cf-loggregator

Set prom_scrape interval to 60s

---

cf-deployment.yml

We need to add a SAN to the `cc_tls` cert. This is so we can safely upgrade to Go 1.15 in `capi-release`. Without this, the cc_uploader will complain in Go 1.15 that CC's cert relies on the deprecated pattern of specifying a common name without a SAN.
This change allows `capi-release` developers to continue to auto-bump their Go dependency to 1.15+ (currently it is pinned at 1.14.x). If `capi-release` bumps Go without this change, the cc_uploader will fail to talk to CC, and `cf push`es will fail at the staging step (affecting Codys).
- Golang release notes describing this change: …

Add SAN to cc_tls certificate

---

cf-deployment.yml

Update the nats_server_cert to include a subject alternate name definition. Also add `update_mode: converge` to force recreation of the cert on upgrade.
This is required for Golang 1.15 clients to be able to validate the server certificate that is presented by the NATS server.
[#174887105](https://www.pivotaltracker.com/story/show/174887105)
This should be transparent to users.
Deploy and verify that the nats_server_cert has the correct SAN defined.
@ameowlia @jrussett

Add SAN to nats_server_cert

---

cf-deployment.yml
operations/experimental/add-system-metrics-agent.yml

Add alternatives names to all logging and metrics certificates. This is now required due to Golang 1.15. See similar changes from this PR: https://github.com/cloudfoundry/cf-deployment/pull/903
This will allow use of logging and metrics components that use Golang 1.15.
* https://cloudfoundry.slack.com/archives/C2U7KA7M4/p1600285368029400
* https://cloudfoundry.slack.com/archives/C2U7KA7M4/p1599754038020000
Add Subject Alternative Name (SAN) to all logging and metric certificates in preparation for update to Golang 1.15.
Pulled from linked PR:
This is the simplest varification but you can also provide additional commands to test that the variable holds the desired value.
`bosh ssh doppler`
`sudo su`
`openssl s_client -connect reverse-log-proxy.service.cf.internal:8082 | openssl x509 -noout …

Log metric certs

---

cf-deployment.yml

Enable mTLS between route_registrar (which publishes the route information about cf components) and NATS Server as default.
Securing the CF traffic with TLS
TLS for everything -> https://github.com/cloudfoundry/cf-deployment/issues/906
Manifest Update: Enables TLS between route_registrar (running as a job on api, singleton-blobstore, database, log-api, doppler and uaa instance_groups) and NATS.
After update the instance_groups like doppler, singleton-blobstore, uaa, log-api, database should be not failing as the route_registrar job can connect to the NATS TLS Server. 
Also the "login.((system_domain))" is available.

Enable TLS between route_registrar and NATS

---

cf-deployment.yml

* this is needed for an upcoming tcp_router bug fix
* it will help fix this bug with overlapping router group ports and system component ports: https://github.com/cloudfoundry/routing-release/issues/184
As an operator, Alana wants to know if there are any misconfigured router_groups that can cause a catastrophic bug at any time
* Issue that this will help fix: https://github.com/cloudfoundry/routing-release/issues/184
* The actual fix will be included in a upcoming routing-release
Add router_groups.read to tcp_router uaa client for upcoming tcp router fix
1. Get the bearer token for the tcp_router client
2. See that you can read router_groups
```
curl -vvv -H "Authorization: bearer [uaa token]" http://api.system-domain.com/routing/v1/router_groups
```
Team: @cloudfoundry/runtime

add router_groups.read to tcp router client

---

cf-deployment.yml
operations/experimental/use-logcache-syslog-ingress-windows2019.yml
operations/experimental/use-logcache-syslog-ingress.yml
operations/test/remove-logging-pipeline-with-danger-windows2019.yml
operations/test/remove-logging-pipeline-with-danger.yml

- this should speed up deploys considerably when the only change is a aggregate drain
- this should also make aggregate drains spread over deployments without a additional deploy
move aggregate drains to the loggr-syslog-binding-cache job
- this should speed up deploys considerably when the only change is a aggregate drain
- this should also make aggregate drains spread over deployments without a additional deploy if those other deployments also make this change
- aggregate drains require deploying every vm on the system
- operators can now change aggregate drains(if specified in the loggr-syslog-binding-cache job), on one vm rather then changing every vm
- cats succeeds when the opsfile to use syslog for log-cache is used

move aggregate drains to the loggr-syslog-binding-cache job

---

cf-deployment.yml

✅ We only accept PRs to develop branch.
As a compliance and security specialist, Alana is unable to report that their corporate CF deployments are using TLS for all traffic. This fails something that is largely an industry standard.
This PR and its accompanying PRs go a long way to solving the problem. Gorouter will talk to NATS over mTLS by default. It is possible there is future work to do (e.g. disabling non-TLS NATS to solve issues like https://github.com/cloudfoundry/routing-release/issues/185.)
* The issue where Gorouter talking to NATS over plaintext was highlighted: https://github.com/cloudfoundry/cf-deployment/issues/906
* An accompanying PR adding this feature to Gorouter: https://github.com/cloudfoundry/gorouter/pull/283
* A supporting PR to routing-release: …

Configure Gorouter to talk to NATS over mTLS

---

operations/test/add-persistent-isolation-segment-diego-cell.yml

Adds properties to support TCP routing in the route-emitter for isolation segment diego cells.
Allows developers to use the test opsfile for `add-persistent-isolation-segment-diego-cell.yml` in conjunction with TCP routing.
https://www.pivotaltracker.com/story/show/178937872
Given it's a test ops file, does it need to be?
```
bosh deploy cf-deplyoment.yml -o operations/test/add-persistent-isolation-segment-diego-cell.yml
bosh -d cf ssh isolated-diego-cell -c "grep 'enable_tcp_emitter\":true' /var/vcap/jobs/route_emitter/config/route_emitter.json"
```

Update route-emitter on isolation-segment ops files to support TCP routing

---

cf-deployment.yml

The official documentation states that this token is valid for "a minimum of" 20 minutes (https://docs.cloudfoundry.org/devguide/deploy-apps/large-app-deploy.html). The actual value in cf-deployment is 10 minutes.
The mismatch between the docs and the actual validity of the token is confusing for users, and results in an unexpected error for those pushing large apps with slower connections whose uploads take between 10 and 20 minutes.
See [here](https://cloudfoundry.slack.com/archives/C07C04W4Q/p1623772601090900) for some discussion of this issue in the #capi slack channel, and [here](https://cloudfoundry.slack.com/archives/C032824SM/p1622462442017900) for discussion in #cli.
Increases the access-token-validity for cf's UAA client from 600 to 1200 seconds, in line with current …

Increase cf.access-token-validity default to 20 minutes

---

cf-deployment.yml

Add a tls cert to the log-cache nozzle so that it can report metrics correctly to the system. 
https://github.com/cloudfoundry/log-cache-release/pull/53 Operators want to see metrics for log-cache nozzle to see that log-cache is ingesting all the metrics. Also not having metrics is just weird. 
https://github.com/cloudfoundry/log-cache-release/pull/53
> 6. requires out-of-band …

add tls for log-cache nozzle metrics

---

cf-deployment.yml

This commit removes the plaintext NATS nodes. All the software used in `cf-deployment` has been modified to handle this and use NATS over mTLS.
Without the `nats` job, and without the `nats` link, everything standard in `cf-deployment` will use the `nats-tls` job and link. Any users with custom components that still require plaintext NATS can re-enable it by keeping the plaintext NATS job.
Until now cf-deployment has deployed a NATS cluster that contained both plaintext and TLS nodes. Internal communication was over mTLS, but clients could choose to connect over plaintext.
Communicating over plaintext is undesirable, as discussed by many users in https://github.com/cloudfoundry/cf-deployment/issues/906. Previous work on this issue has stopped components relying on plaintext NATS, but we …

Remove plaintext NATS

---

cf-deployment.yml
operations/addons/enable-component-syslog.yml
operations/experimental/add-system-metrics-agent.yml
operations/experimental/infrastructure-metrics.yml

We'd like to prepare cf-deployment for the upcoming Ubuntu 22.04 Jammy Jellyfish stemcell, which we expect to be released sometime after April 2022.
To that end, we'd like the BOSH addons (e.g. BOSH DNS) to be deployable to the beta Jammy stemcells while we prepare the stemcell for release.
This commit should have no impact on existing deployments using Xenial or Bionic stemcells.
BOSH addons (e.g. BOSH DNS) are deployable to the beta Jammy stemcells.
> Alana can upgrade to the Jammy stemcell (based on Canonical's upcoming Ubuntu 22.04 Jammy
Jellyfish release) without worry because the developers of Cloud Foundry have had time to test their releases on cf-deployment with beta versions of the Jammy …

Deploy addons to upcoming Jammy Jellyfish stemcell

---

cf-deployment.yml

Support the upcoming changes to [nats-tls requiring it to have client-cert info](https://github.com/cloudfoundry/nats-release/pull/42) for health checks.
Allows nats-release v43 to be pushed out, resolving issues with never-ending streams of warnings in the nats-tls stderr logs.
https://github.com/cloudfoundry/nats-release/pull/42
https://github.com/cloudfoundry/nats-release/issues/32
> 4. modifies the name or deletes a property of a job or …

    Update cf-deployment for nats-tls client certs required in nats v42+

---

cf-deployment.yml

We cargo culted this from the ops file when we inlined it into
cf-deployment. It seems unnecessary since the default bosh dns strategy
is "smart" and clients should use the service alias.
The only consumers we expect this to affect would be someone who picked
this up in the last two weeks and started using the q-s3 domain instead
of the service alias, which we assume is a null set.
Removing alias that is not currently renamed by the "rename network" ops file so is kind of broken now.
Unable to rename the network using cf-deployment. 
https://cloudfoundry.slack.com/archives/C2U7KA7M4/p1646315931755709?thread_ts=1645812408.133929&cid=C2U7KA7M4
> 4. modifies the name or deletes a property of a ~~job or instance group~~ certificate in the main manifest
> …

Remove unused q-s3.log-cache.default.cf.bosh

---

operations/test/add-persistent-isolation-segment-diego-cell.yml

This PR updates the `operations/test/add-persistent-isolation-segment-diego-cell.yml` test ops-file used in CI to ignore the duplicate `iptables` BOSH link it introduces.
CI was failing after the bump to silk v3.0.0.
https://release-integration.ci.cf-app.com/teams/main/pipelines/cf-deployment/jobs/fresh-deploy/builds/3493
N/A (this is not a user-facing change)
It is possible to deploy with the `operations/test/add-persistent-isolation-segment-diego-cell.yml` test ops-file.

Update the test iso seg ops-file

---

cf-deployment.yml

Ensuring that operators who had previously used Log Cache syslog ingress continue to see logs following an upgrade to cf-deployment v18.0.0.
- In #949 Log Cache was split out from the doppler instance group to its own log-cache instance group
- Log Cache was also configured to use syslog ingress by default, rather than the previous behaviour which was to use the Reverse Log Proxy
- Operators who had previously used the experimental ops-file to opt into syslog ingress (operations/experimental/use-logcache-syslog-ingress.yml) would already have had the `log_cache_syslog_tls` credential in their CredHub
- When these operators attempted to upgrade to v18.0.0 the certificate was not re-generated by default, leading to a mismatch between the new service name and the existing certificate
- …

Converge log_cache_syslog_tls certificate

---

cf-deployment.yml
scripts/fixtures/unit-test-vars-store.yml

* has been removed with https://github.com/cloudfoundry/capi-release/releases/tag/1.100.0
Removed obsolete `cc_bulk_api_password` from cf manifest template and variable definition.
Removed an obsolete credential.
Credential was removed in capi-release 1.100.0: https://github.com/cloudfoundry/capi-release/releases/tag/1.100.0
Manual operator intervention may be necessary to delete the credential from a secure store.
Removed obsolete `cc_bulk_api_password`.
After successful deployment of cf, you can do
```
bosh -d cf variables | grep bulk
```
and verify that the output is empty.
@cloudfoundry/cf-capi
(no "App Runtime Deployments WG" team yet...)

Remove obsolete cc_bulk_api_password

---

cf-deployment.yml
operations/use-compiled-releases.yml

This PR reverts cf-networking-release and silk-release to v2.430.
There are bugs in v3.0.0 and v3.1.0 of cf-networking-release and silk-release that cause app deploys to fail on "large" deployments.
[Slack conversation with @ameowlia](https://cloudfoundry.slack.com/archives/C01ABMVNE9E/p1647038551593199)
> 5. changes the name of credentials in the …

Revert CF-Networking and Silk releases to v2.43.0

---

cf-deployment.yml

This change adds the `database_encryption` YAML block to the `cc_deployment_updater` job. This might not be required, but we're assuming that if you've configured encryption key rotation you should specify the `database_encryption` block. The spec in the `cc_deployment_updater` seems to suggest this can be configured:
https://github.com/cloudfoundry/capi-release/blob/develop/jobs/cc_deployment_updater/spec#L105-L110
And since this is configured for all other CC properties it seems sensible to maintain consistency.
We've added it to reduce any confusion surrounding the cc properties configuration within the deployment manifest. By aligned all sections which specify `cc.properties` it reduces any confusion when rotating encryption keys for the cloud controller database.
This change aligns …

Add database_encryption to cc_deployment_updater

---

operations/use-metric-store.yml

This PR updates the `use-metrics-store.yml` ops-file with the required NATS TLS configuration, now that NATS does not communicate over plaintext.
The [CI job](https://release-integration.ci.cf-app.com/teams/main/pipelines/update-releases/jobs/update-metric-store/builds/27) to bump the version of metric-store-release failed.
https://release-integration.ci.cf-app.com/teams/main/pipelines/update-releases/jobs/update-metric-store/builds/27
The CI job to bump the metric-store-release version should pass.
@ctlong

Update use-metrics-store.yml for NATS TLS

---

cf-deployment.yml

UAA needs a fair amount of CPU and memory, as a large java process. My goal here is to make all the "minimal" VMs able to run with 1-2 GB of memory and probably even a shared core, in prep for an upcoming PR to BBL to modernize the machine type.
UAA uses a fair amount of CPU and memory, it should be not labeled as "minimal" VM type.
Our IAAS costs for deploying CF-D are very high, and we're going to burn too much CFF budget. I'm going to make a change soon to make all the "minimal" VMs able to run with 1-2 GB of memory and probably even a shared core.
> 2. increases VM …

Make UAA use larger VM size

---

operations/experimental/README.md
operations/experimental/use-jammy.yml
units/tests/experimental_test/operations.yml

This is a PR to develop.
This expermental ops file will allow operators to use the jammy stemcell
when applied.
* Requires a jammy stemcell to have been uploaded to any given CF-D
environment.
* Will not work with compiled releases at present.
Operators and maintainers want to start testing CF-D with the Jammy stemcell.
#946
N/A
```
bosh deploy -d cf-deployment -o operations/experimental/use-jammy.yml -v system_domain="<system-domain>"
```
@cloudfoundry/app-runtime-deployments-wg-approvers

Feat: add ops file to use Jammy in CF-D

---

cf-deployment.yml

This commit adds the variable and manifest parameters that will be required for future consumption by code to support the `prom_scraper` Prometheus metrics scraper.
This PR is intended to support the work that will be merged in these two PRs: https://github.com/cloudfoundry/capi-release/pull/240 and https://github.com/cloudfoundry/cloud_controller_ng/pull/2781 . You probably should merge this PR _after_ those two get merged in to their primary branches, but it shouldn't cause any trouble if you merged this PR in before one or both of those got merged in.
I believe that it's true that most of the rest of CF uses prom_scraper to gather metrics and Cloud Controller / CAPI is one of the last holdouts. This work is required to support the changes made to CC / CAPI to eventually migrate from …

Adds support for cf-deployment Prometheus metrics

---

cf-deployment.yml

Signed-off-by: David Sabeti <sabetid@vmware.com>
An upcoming version of cf-networking-release (3.10.0) will introduce a communication path between the ASG syncer and the Cloud Controller. This communication happens over MTLS, so the asyc syncer needs a certificate signed by the same CA as the CC certificate. This change adds those certs for the ASG syncer.
The new communication path allows the ASG syncer to skip updates based on information from a new CAPI endpoint. So, operators will benefit from less unnecessary traffic to the CC.
- cf-networking PR: https://github.com/cloudfoundry/cf-networking-release/pull/158
(Some tests -- such as http2 tests -- were skipped because the environment available to us was not configurable (for example, we could not configure our LB to enable https.)
> …

Add certs for internal communication between CC and ASG Syncer

---

cf-deployment.yml

We are working on a partial username search feature for CAPI /v3/organizations/:guid/users, and we have to update the UAA scope to enable it.
Users can do a partial username search via CAPI by querying UAA https://docs.cloudfoundry.org/api/uaa/version/75.22.0/index.html#list-3
> _Please specify either bosh cli or cf cli commands for our team (and cf operators) to verify the changes._
For a PR with a partial username lookup in CAPI the `cloud_controller_username_lookup` UAA client is getting `scim.read` scope
@jdgonzaleza, @cloudfoundry/cf-cli

Expand Cloud Controller username lookup scope

---

cf-deployment.yml

Add an alternative_name to the automatically issued certificate for policy_server_asg_syncer_cc_client.
As-per https://github.com/alphagov/paas-cf/commit/f78080:
> In Go 1.15, treating the CommonName field of an x.509 certificate as a host name when no Subject Alternative Name is present is [deprecated](https://golang.org/doc/go1.15#commonname).
The certificates issued by `service_cf_internal_ca` for `policy_server_asg_syncer_cc_client` should have an alternative name
@alphagov

Add missing alternative_names option to `policy_server_asg_syncer_cc_client`

---

cf-deployment.yml
operations/README.md
operations/enable-cc-v2-rate-limiting.yml
units/tests/standard_test/operations.yml

- Refactor UAA client scopes to use a yaml list instead of single line strings. This will make it easier for ops files to manipulate scopes. This is allowed in uaa-release: https://github.com/cloudfoundry/uaa-release/pull/89
- Add new ops file `enable-cc-v2-rate-limiting.yml` to enable rate limiting for CC V2 API. The ops file is optional and not used per default. Same as for `enable-cc-rate-limiting.yml`
- Refactor UAA client scopes to use a yaml list instead of single line strings. **This can be a breaking change if cf-d consumers have ops-files which manipulate UAA scopes**
- Add new ops file `enable-cc-v2-rate-limiting.yml` to enable rate limiting for CC V2 API
No.
UAA should be deployed successfully and login with CF CLI should work
@jochenehret @philippthun @stephanme

Add Ops-File To Enable CC V2 API Rate Limit

---

ci/pipelines/cf-deployment.yml

Disables CF API v2 on the `hermione` test environment
This will validate that deployments can succeed using only the v3 API.
We recently discovered that disabling the v2 API would cause the [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests) to fail because two tests rely on a v2 endpoint that has not been ported to v3 (see [here](https://github.com/cloudfoundry/cloud_controller_ng/issues/2872) for more details). The endpoint in question is [/v2/service_instances/:guid/permissions](https://apidocs.cloudfoundry.org/16.22.0/service_instances/retrieving_permissions_on_a_service_instance.html), and PRs are now open to create an equivalent v3 endpoint.
The present PR depends on the following two PRs being merged first:
1. …

Disable v2 CF API on hermione

---

operations/enable-cpu-throttling.yml

⚠️ This is blocked on Garden 1.22.5 being included in cf-d ⚠️ 
GAing CPU throttling.
[Garden 1.22.5](https://github.com/cloudfoundry/garden-runc-release/releases/tag/v1.22.5) includes two new non-experimental properties.
* Add `garden.cpu_throttling` bosh property. If this property is set it will override `garden.experimental_cpu_throttling`.
* Add `garden.cpu_throttling_check_interval` bosh property. If this property is set it will override `garden.experimental_cpu_throttling_check_interval`.
* For backwards compatibility, the experimental properties are still respected if the non-experimental properties are not set.
* ⚠️ The experimental properties `garden.experimental_cpu_throttling` and `garden.experimental_cpu_throttling_check_interval` are now deprecated. They will be removed in  a …

ga cpu throttling

---

ci/pipelines/bionic-stemcell.md
ci/pipelines/bionic-stemcell.yml

This PR adds a pipeline to deploy & then run tests against the `bionic` stemcell, in the same way as is currently done for `jammy`.
- Adds a new pipeline for testing the `bionic` stemcell
1. Validate that the [bionic-stemcell pipeline](https://release-integration.ci.cf-app.com/teams/main/pipelines/bionic-stemcell) remains green (it uses the pipeline yml included in this PR) & is doing the intended work (testing the bionic stemcell).
@iaftab-alam

Add bionic stemcell validation pipeline

---

ci/pipelines/infrastructure.yml

* load on director is too high and we sometimes see timeoutes when connecting to "uaa" process
Scale up BOSH director VM to 4 core machine on "bbr" test environment.
"bbr-deploy" job often fails with timeouts: https://app-runtime-deployments.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/bbr-deploy/builds/117
PR for relint-envs: https://github.com/cloudfoundry/relint-envs/pull/4
N/A
PR is only for CI pipelines.
"bbr-deploy" job has less fails.

Scale up BOSH director VM in "bbr" env

---

ci/pipelines/infrastructure.yml

Enable bbl config for cedric/Windows environment to scale up BOSH director to 4 CPUs.
BOSH operations fail sporadically with timeouts because director is overloaded.
https://github.com/cloudfoundry/relint-envs/pull/5
"windows" jobs fail less often.

Enable bbl config option for "cedric" environment

---

operations/use-compiled-releases.yml

* reverting because of https://github.com/pivotal/credhub-release/issues/74
This reverts commit 0e788a1a5d7cb25df11f40b0730189fdb979253a.
Reverting credhub-release from 2.12.14 back to 2.12.13.
Release pipeline is blocked with 2.12.14.
https://github.com/pivotal/credhub-release/issues/74
Use release notes from Concourse job as usual.
"cf-deployment" pipeline succeeds.

Revert "Updated compiled releases with credhub 2.12.14"

---

cf-deployment.yml

* reverting because of https://github.com/pivotal/credhub-release/issues/74
This reverts commit 28110b3fabda6a79e495249ceeae5675e1b6f18b (credhub-release version in cf-deployment.yml)
Reverting credhub-release from 2.12.14 back to 2.12.13.
Release pipeline is blocked with 2.12.14.
https://github.com/pivotal/credhub-release/issues/74
Use release notes from Concourse job as usual.
"cf-deployment" pipeline succeeds.

Revert "Updated manifest with credhub-release 2.12.14"

---

ci/pipelines/cf-deployment.yml

Fix "experimental-ops-files" job: https://app-runtime-deployments.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/experimental-ops-files
"summarize-ops-files" task was broken: https://github.com/cloudfoundry/runtime-ci/tree/main/tasks/summarize-ops-files
Job is green and prints all experimental ops files used in the "experimental" deployment:
https://app-runtime-deployments.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/experimental-ops-files

Fix "experimental-ops-files" job

---

ci/input/inputs.yml
ci/pipelines/update-releases.yml

#1008 / #989  adds `cflinuxfs4` via an optional ops-file. This PR adds `cflinuxfs4` to the update releases pipeline so that we always use the latest version.
CI/Pipeline change only
- not relevant, CI only
`update-cflinuxfs4` job in update releases pipeline should be green
@jochenehret

Add cflinuxfs4 to update releases pipeline

---

cf-deployment.yml
operations/test/add-persistent-isolation-segment-router.yml

https://github.com/cloudfoundry/gorouter/pull/316 changes the CA list for gorouter (`router.ca_certs`) to an array. The intention is that then the CA list can be augmented via BOSH opsfile, as opsfiles can modify arrays but not concatenate strings.
We are unable to extend the router CA list with some additional custom CAs without repeating the CA list from the CF deployment, as opsfiles cannot concatenate strings.
Each entry in the array may still contain a string that includes multiple contatenated PEM certificates.
https://github.com/cloudfoundry/gorouter/pull/316
https://github.com/cloudfoundry/routing-release/pull/297
4. modifies the name or deletes a property of a …

Adapt gorouter ca_cert list to a list

---

operations/experimental/add-cflinuxfs4.yml

Add cflinuxfs4 package for golang-buildpack. Works with latest go-buildpack-release: 
https://github.com/cloudfoundry/go-buildpack-release/releases/tag/1.10.1
Support buildpacks with cflinuxfs4 stack.
cflinuxfs4 support for golang-buildpack added
CATs golang buildpack test passes for cflinuxfs4 stack

Add cflinuxfs4 package for golang-buildpack

---

ci/pipelines/cf-deployment.yml

Scale out from 3 to 6 Diego cells in experimental env to improve CATs performance and stability.
CATs for experimental deployments are somewhat unstable take rather long:
https://app-runtime-deployments.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/experimental-cats
https://app-runtime-deployments.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/experimental-cats-cflinuxfs4
Concourse "-cats" jobs listed above run smoother.

Scale out to 6 Diego cells for experimental env

---

operations/experimental/README.md
operations/experimental/use-trusted-ca-cert-for-apps-cflinuxfs4.yml
units/tests/experimental_test/operations.yml
units/tests/standard_test/operations.yml

Ops file to enable trusted ca for apps for cflinuxfs4, similar to existing ops file: https://github.com/cloudfoundry/cf-deployment/blob/main/operations/use-trusted-ca-cert-for-apps.yml
Enable secure app communication also on cflinuxfs4 stack.
Doesn't need explicit documentation.
For now, only unit tests must pass.

Add ops file for trusted ca certs for cflinuxfs4

---

operations/experimental/add-cflinuxfs4.yml

Add ruby and binary cflinuxfs4 buildpack support.
The ruby-buildpack and the binary-buildpack now support the cflinuxfs4 stack.
Buildpack tests pass: https://app-runtime-deployments.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/experimental-cats-cflinuxfs4

Add ruby and binary cflinuxfs4 buildpacks

---

ci/pipelines/cf-deployment.yml

* if this task fails in "upgrade-deploy" or "experimental-deploy", we have to start again from the beginning which takes very long (because first "bosh-deploy-cf-latest-release" is executed)

2 attempts for "bosh-deploy-cf-develop" tasks

---

cf-deployment.yml
scripts/fixtures/unit-test-vars-store.yml

Remove obsolete `internal_api_password` for internal CF API (Capi/ CCNG). Instead of basic auth with the `internal_api_password` mTLS is used (for a long time already).
In CAPI `internal_api_password` was removed with version 1.144.0.
Alana wants to get rid of unused/obsolete credentials
- cloudfoundry/capi-release/pull/286
- cloudfoundry/cloud_controller_ng/pull/3134
Remove `cc_internal_api_password` as mTLS is now used instead.
run CATS

Remove obsolete `internal_api_password`

---

ci/pipelines/cf-deployment.yml

Removes unused task `deliver-tracker-story` from cf-deployment pipeline. This task is an artifact of when the folks managing this repo used a public tracker project. We've since switched to using GH projects.
N/A - this is a CI-only change.
- [slack thread](https://cloudfoundry.slack.com/archives/C033ALST37V/p1675323741810389).
Shouldn't be described in the release notes.
- `fly` the changes to the cf-deployment pipeline.
- See the bless-manifest job complete successfully.
@jochenehret

CI: remove deliver tracker story task

---

operations/experimental/add-cflinuxfs4.yml

Add cflinuxfs4 support for r-buildpack.
r-buildpack v1.2.0 now supports cflinuxsfs4
Job "experimental-cats-cflinuxfs4" should show passing test:
`[detect] Buildpacks r when using cflinuxfs4 stack [It] makes the app reachable via its bound route`

Add r-buildpack for cflinuxfs4

---

ci/input/inputs.yml
ci/pipelines/update-releases.yml

This is a change to the `update-releases` pipeline to update the GitHub organization for pxc-release.
N/A
We haven't been includng bumps of pxc-release since v0.5.0.
> 7. modifies the ops-file path, changes the type, …

CI: Move pxc release to cloudfoundry GitHub org

---

operations/experimental/add-cflinuxfs4.yml

Add nginx-buildpack to cflinuxfs4 ops file. Latest release v1.2.0 supports cflinuxfs4:
https://github.com/cloudfoundry/nginx-buildpack/releases/tag/v1.2.0
One more buildpack for the cflinuxfs4 rollout.
The **nginx-buildpack** now supports cflinuxfs4: https://github.com/cloudfoundry/nginx-buildpack/releases/tag/v1.2.0
This test in "experimental-cats-cflinuxfs4" should pass:
```
[FAIL] [detect] Buildpacks nginx when using cflinuxfs4 stack [It] makes the app reachable via its bound route
/go/src/github.com/cloudfoundry/cf-acceptance-tests/detect/buildpacks.go:225
```
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/experimental-cats-cflinuxfs4

Add nginx-buildpack to cflinuxfs4 ops file

---

cf-deployment.yml
operations/experimental/README.md
operations/experimental/use-mysql-version-8.0.yml
units/tests/experimental_test/operations.yml

pxc-release 1.0.0 and greater have support for Percona 8.0. This is controlled by a new property mysql_version. An upgrade from Percona 5.7 to 8.0 will be performed. Also included an operations file to make the property mysql_version change from 5.7 to 8.0. The default continues to be Percona 5.7.
Co-authored-by: Colin Shield <cshield@vmware.com>
Co-authored-by: Andrew Garner <garnera@vmware.com>
Co-authored-by: Kevin Markwardt <kmarkwardt@vmware.com>
Bumping pxc-release to v1.0.7
This change introduces support for Percona 8.0. Releases of pxc-release prior to 1.0.0 only support Percona 5.7. Percona 5.7 has an EOL notice.
[Percona 5.7 will be EOL …

Bumping pxc-release to 1.0.7

---

ci/pipelines/cf-deployment.yml
operations/experimental/README.md

Test [operations/experimental/use-mysql-version-8.0.yml](https://github.com/cloudfoundry/cf-deployment/blob/develop/operations/experimental/use-mysql-version-8.0.yml) in experimental fan-out in CI
N/A
https://github.com/cloudfoundry/cf-deployment/pull/1049#discussion_r1107807061
N/A
Experimental fan-out in CI succeeds.
@davewalter

CI: add mysql 8 upgrade to experimental CI fan-out

---

ci/pipelines/cf-deployment.yml

Test [operations/experimental/use-mysql-version-8.0.yml](https://github.com/cloudfoundry/cf-deployment/blob/develop/operations/experimental/use-mysql-version-8.0.yml) in experimental fan-out in CI.
Previously, in #1053 I accidentally added this to the first deploy rather than the upgrade. That was a mistake that needed correcting.
N/A
* https://github.com/cloudfoundry/cf-deployment/pull/1049#discussion_r1107807061
* #1053 
N/A
Experimental fan-out in CI succeeds.
None

CI: add mysql 8 upgrade to experimental

---

operations/experimental/add-cflinuxfs4.yml

staticfile-buildpack v1.5.39 now supports cflinuxfs4
https://github.com/cloudfoundry/staticfile-buildpack-release/releases/tag/1.5.39
Build CF apps with staticfile-buildpack on cflinuxfs4 stack.
staticfile-buildpack now supports cflinuxfs4
Test "[detect] Buildpacks staticfile when using cflinuxfs4 stack [It] makes the app reachable via its bound route" should pass in "experimental-cats-cflinuxfs4" job:
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/experimental-cats-cflinuxfs4

Add staticfile-buildpack with cflinuxfs4 support

---

operations/experimental/add-cflinuxfs4.yml

Add cflinuxfs4 support for php-buildpack.
Build php applications on cflinuxfs4 stack.
php-buildpack 4.6.0 now supports cflinuxfs4: https://github.com/cloudfoundry/php-buildpack-release/releases/tag/4.6.0
"experimental-cats-cflinuxfs4" now must turn green: https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/experimental-cats-cflinuxfs4

Add cflinuxfs4 support for php-buildpack

---

ci/input/inputs.yml
ci/pipelines/update-releases.yml
ci/template/update-releases.yml

* ops file "operations/windows2019-cell.yml" was applied twice which didn't work
* and use greengrass key stored in credhub
Fix update-releases pipeline.

Fix update-windows-utilities job

---

ci/pipelines/cf-deployment.yml
ci/pipelines/infrastructure.yml
ci/pipelines/update-releases.yml
ci/template/update-releases.yml

Configure ARD WG GitBot for all bbl-up and bbl-destroy tasks. Default is:
```
GIT_COMMIT_EMAIL: "cf-release-integration@pivotal.io"
GIT_COMMIT_USERNAME: "CI Bot"
```
https://github.com/cloudfoundry/cf-deployment-concourse-tasks/blob/e53dae9558f879e992999b6241b70c2f2a154037/bbl-up/task.yml#L126
Also replace (already deleted) "cf_deployment_readwrite_deploy_key" with "ard_wg_gitbot_ssh_key".

Configure ARD WG GitBot for bbl tasks

---

ci/pipelines/jammy-stemcell.yml
ci/template/update-releases.yml

#1066 which also replaces  "cf_deployment_readwrite_deploy_key" with "ard_wg_gitbot_ssh_key". For these two files it was missing. This PR aims to to clean the leftovers from  #1066

clean leftovers from PR#1066

---

ci/pipelines/cf-deployment.yml

* CATs are still flakey because some test apps need too long to become healthy
"experimental-cats" fails very often
(not relevant)
"experimental-cats" job should succeed more often:
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/experimental-cats

Scale out Diego cells to 8 for experimental env

---

operations/test/add-persistent-isolation-segment-diego-cell.yml

Fix cflinuxfs4 setup for isolation segment ops file.
Make cflinuxfs4 the default stack.
https://github.com/cloudfoundry/cf-deployment/issues/1047
See main PR: https://github.com/cloudfoundry/cf-deployment/pull/1070
"fresh-deploy" job must become green again: https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/fresh-deploy

Add cflinuxfs4 to isolation segment ops file

---

ci/pipelines/cf-deployment.yml

Remove experimental CATS cflinuxfs4 Job. All the logic related cflinuxfsf4 are inlined into cf-deplyment and now it is the default stack.
[#1047](https://github.com/cloudfoundry/cf-deployment/issues/1047)
N/A
cf-deployment pipline stays green.

Remove experimental CATS cflinuxfs4 Job

---

ci/pipelines/cf-deployment.yml

Remove "experimental-cats-cflinuxfs4" job from "cf-deployment" pipeline. "cflinuxfs4" is now the default and a separate run of CATs is not necessary anymore.
(already done in https://github.com/cloudfoundry/cf-deployment/pull/1074, this PR just removes the obsolete "add-cflinuxfs4.yml" ops file)
Rollout of cflinuxfs4, step 1: https://github.com/cloudfoundry/cf-deployment/issues/1047
Job "experimental-cats-cflinuxfs4" is removed from https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment

Remove experimental-cats-cflinuxfs4 job

---

ci/pipelines/bionic-stemcell.yml

Set "cflinuxfs3" as the default stack for the Bionic validation pipeline:
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/bionic-stemcell-validation
Validate new ops file `operations/set-cflinuxfs3-default-stack.yml`.
https://github.com/cloudfoundry/cf-deployment/issues/1047
Not relevant for release.
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/bionic-stemcell-validation/jobs/deploy-cf passes and deploys CF with "cflinuxfs3" as default stack.

Set cflinuxfs3 as default for Bionic validation pipeline

---

ci/pipelines/infrastructure.yml

Yes
Updates the BBR group of the infrastructure pipeline:
* Removes the network-lb-gcp plan patch from baba-yaga-bbr.
* Updates the params passed to bbr-pool when acquiring the lock for setting up the env.
N/A
* https://cloudfoundry.slack.com/archives/C033ALST37V/p1683068678454979?thread_ts=1682676648.184329&cid=C033ALST37V
* https://github.com/cloudfoundry/relint-envs/issues/13
N/A
BBR fanout in cf-deployment pipeline succeeds.
None

CI: Fix baba-yaga-bbr env

---

ci/pipelines/infrastructure.yml

Yes
Updates the Bellatrix group of the infrastructure pipeline to remove the network-lb-gcp plan patch.
N/A
* https://cloudfoundry.slack.com/archives/C033ALST37V/p1683068678454979?thread_ts=1682676648.184329&cid=C033ALST37V
* https://github.com/cloudfoundry/relint-envs/issues/13
* https://github.com/cloudfoundry/bosh-bootloader/issues/562
bionic-stemcell validation succeeds.
None

CI: Fix bellatrix-stable env

---

ci/pipelines/cf-deployment.yml

Yes
The cf-deployment pipeline runs `bbl-up` again after snitch passes all the other jobs. bosh-bootloader v9.0.1 was released which includes the changes we need to recreate snitch regularly.
N/A
#1084
N/A
The snitch fanout in the cf-deployment pipeline goes green.
None

CI: Recreate snitch on success

---

operations/use-compiled-releases.yml

Remove cflinuxfs3 from compiled releases. Update job is currently failing: https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/update-releases/jobs/update-cflinuxfs3/builds/18
Part of cflinuxfs3 deprecation/removal story: https://github.com/cloudfoundry/cf-deployment/issues/1048
https://github.com/cloudfoundry/cf-deployment/issues/1048
Not relevant.
Update job passes again: https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/update-releases/jobs/update-cflinuxfs3

Remove cflinuxfs3 from compiled releases ops file

---

ci/pipelines/update-releases.yml
ci/template/update-releases.yml

CI change to use a new service account key for uploading to certain GCS buckets, which were moved to the ARD WG GCP project recently.
Note: we decided to use one bucket instead of multiple in the hope we can consolidate our service accounts down the line.
Note: the compiled-releases bucket is now based out of europe, which may affect latency for some CF-D operators.
N/A
None
N/A
CI remains green.
@davewalter

CI: use new svc account key for cf-deployment-compiled-releases bucket

---

ci/pipelines/cf-deployment.yml
operations/test/use-cflinuxfs4-compat-isolation-segment-diego-cell.yml
units/tests/test_test/operations.yml

Fix "fresh-deploy" validation setup. The test ops file `add-persistent-isolation-segment-diego-cell.yml` uses the "cflinuxfs4" release, so we must overwrite that with another ops file.
https://github.com/cloudfoundry/cflinuxfs4-compat-release/issues/1
https://github.com/cloudfoundry/cflinuxfs4-compat-release/issues/1
CI job https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/fresh-deploy must pass.

Fix cflinuxfs4-compat-release for fresh-deploy

---

cf-deployment.yml

Aggregate drains now uses mututal tls for log-cache connections
It makes log-cache more secure
Log cache continues to work

Feat: Send logs and metrics to Log Cache using mTLS

---

cf-deployment.yml

> Redis will be used for rate limiting and (at a later point in time) also for metrics. The `monit` process will only be started if either the Puma webserver is used or `cc.experimental.use_redis` is set to `true` (defaults to `false`). If Redis is used, the cloud controller config `redis.socket` is set; this switches the rate limit implementation from using in-memory counters to Redis.
> This is a prerequisite to eventually make Puma the default webserver used by cloud controller. And with Puma the overall request throughput will increase.
> Related PR in capi-release: https://github.com/cloudfoundry/capi-release/pull/322
❗ I'm going for a NO, although a new job will be added to the api VMs. Unless …

Add redis job to api vms

---

cf-deployment.yml

It is a fix for #1106 
In the current version of `cf-deployment` the `extended_key_usage` configuration is missing in the `cc_logcache_tls` certificate's options. Because of that, when the certificate is generated with BOSH interpolate, the `extended_key_usage` option was automatically added with `TLS Web Server Authentication` value only which is wrong in this case, as the certificate is used for client authentication. Therefore, it cannot be used for mutual TLS authentication between the cloud controller and log-cache. When one uses CredHub for managing the certificates, the `X509v3 Extended Key Usage` SSL extension is not configured at all an the certificate can be used without any problems.
This change defines the `extended_key_usage` option and adds `client_auth` value, so that the …

Add extended-key-usage for the cc_logcache_tls

---

operations/experimental/README.md
operations/experimental/add-otel-collector-windows.yml
operations/experimental/add-otel-collector.yml
units/tests/experimental_test/operations.yml

Makes the `otel-collector` and `otel-collector-windows` jobs in `loggregator-agent` release available via experimental ops files.
Alana is unable to egress metrics without using the firehose.
RFC: https://github.com/cloudfoundry/community/pull/641
CF-D deployed with these ops files successfully egresses metrics through the provided metric exporters to metric destinations.
@rroberts2222

feat(operations/experimental): add new ops files for the OTel Collector

---

operations/experimental/add-otel-collector-windows.yml
operations/experimental/add-otel-collector.yml
operations/experimental/example-vars-files/vars-override-otel-collector-exporters.yml
units/tests/experimental_test/operations.yml

- accept variable to make it easier to provide on the command line or vars file
- provide example vars file which exports metrics to a file on disk
CF Developers want to be able to set metrics exporters easily in pipelines
NA
``` bosh int /tmp/cf.yml -o ./operations/experimental/add-otel-collector.yml -l ./operations/example-vars-files/vars-override-otel-collector-exporters.yml```
Should result in a valid manifest with the file exporter configured

refactor add-otel-collector ops file

---

ci/pipelines/pull-requests.yml

We currently only use these PR resources to error if the main branch is the base branch of the PR. Since presence of a PR to main is all that we care about, and the contents of the PR are never examined, let alone run, we should be able to disregard the requirements for reviews in this case.
The two CI jobs using these resources exist for the sole purpose of alerting PR creators and approvers that a PR has been incorrectly made against main instead of develop. Currently, a PR approval is required to trigger the two jobs, which means that it's initially on approvers to catch the incorrect base branch. I've missed that mistake two or three times in the past two weeks, and it's been causing me frustration because, after approving a PR, I then have to go back and explain that the base branch …

ci(pull-requests): Don't require reviews to fail PRs made against main

---

ci/pipelines/pull-requests.yml

This should ensure that all approved PRs to CATs are run through unit tests, even if multiple were approved at once. Currently, if multiple are approved at once, only the latest PR will trigger the job.
Also, it's what we do for every other trigger resource in this pipeline.
ARD approvers might have to go re-run the pipeline manually after approving multiple CATs PRs at once.
None
Pipeline remains green. 
None

ci(pull-requests): Add `version: every` to CATs unit tests job

---

cf-deployment.yml

When the CAPI info fields are not set, the info endpoints (i.e. `API_URL/v2/info`, `API_URL/v3/info`) return empty results akin to the following:
```
$ cf curl /v3/info
{
"name": "",
"build": "",
"version": 0,
...
}
```
This sets those properties to appropriate values.
Persons interacting with a CF-D environment who cannot access its manifest are unable to determine the CF-D build and version info.
Closes #813 
On a CF-D environment with this change deployed, run `cf curl /v3/info` and `cf curl /v2/info` and validate that the returned response has values associated with `name`, `build`, and `version` that match up with the manifest inputs.
None

feat: Populate CAPI info

---

cf-deployment.yml

Removes the deprecated `windows2012R2` stack.
Alana should not be using the windows2012R2 stack.
Closes #1116.
Change goes through CI successfully.
N/A

Fix: Remove deprecated windows2012R2 stack

---

texts/versioning.md

As discussed in the ARD WG meeting from Sep 28th, we want to enhance the semantics of a major version update. No major version must be skipped when updating cf-deployment. Otherwise, a seamless update is no longer guaranteed.
We want to ensure that complex updates requiring multiple steps can be rolled out seamlessly by cf-deployment operators.

Enhance semantics of major version update

---

operations/add-persistent-isolation-segment-diego-cell.yml

Fix ops file `add-persistent-isolation-segment-diego-cell.yml`. The "loggregator" config properties are in the wrong place, resulting in "Failed to find variable" CredHub errors, see:
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/fresh-deploy/builds/696
Error was introduced with https://github.com/cloudfoundry/cf-deployment/pull/1109
For config parameter specification, see https://github.com/cloudfoundry/silk-release/blob/develop/jobs/vxlan-policy-agent/spec
See https://github.com/cloudfoundry/cf-deployment/pull/1109
Job "fresh-deploy" must succeed.

Fix vxlan-policy-agent job configuration

---

ci/pipelines/cf-deployment.yml

Fix ops file path for ops file `add-persistent-isolation-segment-diego-cell.yml`.
PR which introduced the ops files relocation: https://github.com/cloudfoundry/cf-deployment/pull/1109
N/A
Job "upgrade-deploy" must succeed. It's currently failing: https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/upgrade-deploy/builds/710

Fix ops file path for "upgrade-deploy" job

---

operations/use-offline-windows2019fs.yml
operations/use-online-windows2019fs.yml

Uses the same trusted certs as diego cells. Without these present, we missed catching the problem with winc-release 2.17.0 and the windows2019fs pre-start scripts.
CI missed catching a problem if this property is set to add custom trusted certs on the filesystem image.
> 6. requires …

Add trusted_certs for windows filesystem opsfiles

---

cf-deployment.yml
operations/experimental/README.md
operations/experimental/use-mysql-version-8.0.yml
units/tests/experimental_test/operations.yml

Promote the ops file to use MySQL version 8.0, inlining its contents into `cf-deployment.yml`.
Alana expects the default MySQL version used to be in-support.
* MySQL version 5.7 is EOL.
* https://github.com/cloudfoundry/cf-deployment/issues/1137
* The pxc release uses MySQL version 8.0 under-the-hood.
* New deployments work as expected.
* Old deployments upgrade seamlessly.
None

Fix: Use MySQL version 8.0 by default

---

ci/pipelines/cf-deployment.yml

The upcoming bbl release will contain a change that disables ephemeral external IPs in the GCP cloud config by default. Since v9.0.11, bbl deploys a cloud NAT gateway on GCP for outgoing traffic.
I've tested the change by manually disabling external IPs in the "fresh" and "upgrade" cloud-configs. For unknown reasons, the "fresh" isolation segment smoke tests now take longer and fail repeatedly. It's unclear why exactly. CATs succeed. Smoke tests and CATs on the "upgrade" environment succeed, too.
Using a NAT gateway avoids allocation of external IPs and the risk of leaving orphaned IPs behind (which incur additional cost).
Smoke test ops file: https://github.com/cloudfoundry/relint-envs/blob/main/environments/test/luna/smoke-tests-timeout-scale.yml
bbl PR: …

Set "fresh" smoke-tests timeout scale to 3.0

---

cf-deployment.yml

✅
Adds a cert + properties gorouter to enable an endpoint for LB health checks using TLS.
Being able to ensure all non-localhost endpoints in CF are protected by TLS encryption.
https://www.pivotaltracker.com/story/show/186470212
https://github.com/cloudfoundry/gorouter/pull/374
> 6. requires …

Add additional gorouter LB health endpoint with TLS

---

ci/pipelines/fips-stemcell.yml

New validation pipeline for the FIPS Jammy stemcell.
Alana wants to deploy CF on a FIPS compliant environment. CF shall be validated on a FIPS compliant stemcell.
Not relevant (new pipeline for CI infrastructure).
Pipeline can be uploaded and executed: https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/fips-stemcell

Validation pipeline for FIPS stemcell

---

cf-deployment.yml

The removal of the `metrics-discovery-release` was announced with [RFC-0022](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0022-deprecate-metrics-agent.md) and the job configuration was removed with [PR 1139](https://github.com/cloudfoundry/cf-deployment/pull/1139/files). This change removes the things we have missed in the previous one.
It is already mentioned in the v35.0.0 release
None. The certificate is not used anywhere
#wg-app-runtime-platform-logging-and-metrics-approvers

Remove leftovers from  metrics-discovery-release

---

ci/input/inputs.yml
ci/pipelines/update-releases.yml
operations/experimental/add-otel-collector-windows.yml
operations/experimental/add-otel-collector.yml
operations/experimental/example-vars-files/vars-override-otel-collector-exporters.yml

Also changing sample vars file path to be compatible with both windows and linux jobs
Moving otel-collector out to its own release.
Other deployments may wish to use otel-collector without using loggregator-agent.
otel-collector now comes from the otel-collector-release
`bosh releases` should show otel-collector-release is deployed
@ctlong

Use otel-collector-release for otel-collector

---

ci/pipelines/fips-stemcell.yml

Trigger the FIPS validation pipeline for the "release-candidate" branch instead of the "main" branch.
Alana wants to validate the FIPS stemcell before a cf-deployment release.
Pipeline configuration works: https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/fips-stemcell

Trigger FIPS validation for "release-candidate" branch

---

units/go.mod

Bumps the go module in units to require go1.21+.
N/A
None
Unit tests pass.
None

chore(units): Bump go version in go.mod to go1.21

---

cf-deployment.yml
ci/input/inputs.yml
ci/pipelines/update-releases.yml
operations/use-compiled-releases.yml

The `otel-collector` release was mistakenly added to the base releases section of the `update-releases` CI, causing it to be incorrectly added to `cf-deployment.yml` and `operations/use-compiled-releases.yml`.
This PR reverts those changes and corrects the `update-releases` CI.
N/A
https://github.com/cloudfoundry/cf-deployment/pull/1145
- CF-D no longer uploads `otel-collector` release by default
- CF-D with compiled releases still deploys correctly
- `update-otel-collector` job in `update-releases` pipeline is listed in the `update-ops-releases` group
None

Fix: Remove otel-collector from base cf-deployment.yml manifest

---

operations/add-persistent-isolation-segment-router.yml

Adds TLS settings for gorouter loadbalancer status checks on isolated gorouters.
Divergence of gorouter configs between cf-deployment.yml + the iso-seg-router VM.
Isolated gorouters now support TLS status checks from loadbalancers.
When the add-persistent-isolation-segment-router.yml ops file is deployed, gorouter responds to https://<ip>:8443/health
- [] **Slightly Less than Urgent**
Will unblock the routing-release pipeline.

Add TLS settings for isolated gorouter status checks

---

cf-deployment.yml

Adds certs + config to use certs for the new TLS health check for tcp-router 
Allows operators to have TLS based health checks on their tcp-router.
https://www.pivotaltracker.com/story/show/186471705
https://www.pivotaltracker.com/story/show/186497091
tcp-router now supports a TLS based healthcheck when queried from load-balancers, on port 443.
tcp-router responds to https://<ip>/health with a 200 (will require routing-release update before this is fully functional though)
@ameowlia

Add cert for TLS LB healthcheck endpoint for tcp-router

---

ci/pipelines/fips-stemcell.yml

Run tests in "try" block so that the deployment is always cleaned up and the pool is unclaimed.
Alana wants to execute the FIPS validation for each new commit or stemcell version without manually releasing the lock.
- [] YES
N/A
Pipeline is green and pool is automatically unclaimed even if tests fail:
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/fips-stemcell

FIPS validation: Ignore failing tests for now

---

units/tests/experimental_test/operations.yml

Add unit test for `fips-compliance.yml` ops file.
Alana wants all ops files to be tested.
https://github.com/cloudfoundry/cf-deployment/pull/1158
Not relevant.
Unit test job must succeed: https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/unit-test-golang-tests

Add missing unit test for fips-compliance ops file

---

cf-deployment.yml

> In order to switch from MD5 paths in the buildpack image layers to paths calculated using xxHash64, we need `capi-release` and `diego-release` to support both algorithms in parallel (which is the case in the `develop` branch) and then have two major cf-deployment releases; one that **enables** legacy MD5 buildpack paths and another one that **disables** them.
> FIPS compliance
> #1140
> 4. modifies the name or deletes a property of a job …

Enable legacy MD5 buildpack paths

---

ci/pipelines/fips-stemcell.yml

Use the new fips-compliance ops file for the FIPS validation: https://github.com/cloudfoundry/cf-deployment/blob/develop/operations/experimental/fips-compliance.yml
Remove the "try" block for the smoke tests. They have turned green and now we want to make regressions visible in the Concourse pipeline.
Alana wants a FIPS-compliant cf-deployment.
N/A
FIPS validation pipeline stays green: https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/fips-stemcell

Use fips-compliance ops file for FIPS validation

---

cf-deployment.yml
operations/use-external-blobstore.yml

This PR will add variables and certs to support Blobstore TLS.  TLS will not be registered until #1155 is merged.  We'd like to merge this first, so that when the new version of CAPI is released, this variables will already exist.
Alana wants all of her traffic to be encrypted.
#1155 
https://github.com/cloudfoundry/capi-release/pull/377
No release note.  We can add a release note when #1155 is merged
N/A
@ameowlia @dalvarado

Add variables and certs to support Blobstore TLS

---

ci/pipelines/fips-stemcell.yml

Remove "try" block from fips-cats Concourse job. We had the first passing job and from now on we want to make failures visible:
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/fips-stemcell/jobs/fips-cats/builds/57
Alana wants to ensure that cf-deployment is FIPS compliant.
N/A
Change has already been uploaded to Concourse.

Remove "try" block from fips-cats job

---

cf-deployment.yml

> After having a major release (v38) of cf-deployment with the legacy MD5 buildpack paths enabled, we can now switch them off as the buildpackapplifecycle supports both - legacy MD5 and xxhash64 - buildpack paths.
> FIPS compliance
> #1140, #1157
> 6. requires out-of-band manual intervention …

Disable legacy MD5 buildpack paths

---

ci/pipelines/fips-stemcell.yml
operations/experimental/README.md
operations/experimental/fips-compliance.yml
units/tests/experimental_test/operations.yml

Remove obsolete ops file. The default for the `legacy_md5_buildpack_paths_enabled` options is now `false`.
Alana wants to have a FIPS-compliant cf-deployment setup.
https://github.com/cloudfoundry/cf-deployment/pull/1166
Removes ops file `operations/experimental/fips-compliance.yml`.
Ops file `operations/experimental/fips-compliance.yml` has been removed. The default is now `false` in `cf-deployment.yml`.
> _Please specify either bosh cli or cf cli commands for our team (and cf operators) to verify the changes._
> _Few examples_
> 1. For a PR with a new job in the manifest, `bosh instances` can verify the job is running after upgrade. You can provide additional commands to verify the job is running as specified.
> 2. For a PR with …

Remove fips-compliance ops file

---

ci/pipelines/update-releases.yml
ci/template/update-releases.yml

Add timeout to pool acquire jobs in "update-releases" pipeline.
If an instance from the pool cannot be acquired over a longer time, something is broken and we should get notified.
The 4 instances from the update-releases pool were acquired for a longer time because some Concourse jobs were not properly triggered, e.g.: https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/update-releases/jobs/acquire-nats-pre-dev-lock/builds/20
(not relevant)
N/A
Update-releases pipeline is green (or acquire jobs turn red if there is a problem). Pipeline has already been uploaded.

Add 4h timeout to pool acquire jobs

---

ci/pipelines/cf-deployment.yml

* don't run the upgrade jobs two times as the second attempt is a BOSH no-op and will not measure anything meaningful
* configure stats check threshold (see https://github.com/cloudfoundry/uptimer/pull/115)
Alana wants to have a downtime validation when upgrading the cf-deployment version.
https://github.com/cloudfoundry/cf-deployment/issues/1176
N/A
N/A
The "bosh-deploy-cf-develop" tasks in the "upgrade-deploy" and "experimental-deploy" jobs are green and produce meaningful uptimer reports.

[Issue 1176] Fix uptimer setup

---

ci/pipelines/cf-deployment.yml

Stats availability check failed on some upgrade builds. Increase from 5 to 10.
Alana wants to measure the stats availability during a cf upgrade.
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/experimental-deploy/builds/1184
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/experimental-deploy/builds/1185
N/A
N/A
"experimental-deploy" jobs succeeds:
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/experimental-deploy

Increase stats availability threshold to 10

---

cf-deployment.yml

> Remove `legacy_md5_buildpack_paths_enabled: false` from `cf-deployment.yml` as [CAPI 1.182.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.182.0) changed the default value for this property to `false`.
> One line less in `cf-deployment.yml`...
> [PR #415](https://github.com/cloudfoundry/capi-release/pull/415) in capi-release.
> Not at all...
> n/a
> I guess this is not required for this small change...

Remove legacy_md5_buildpack_paths_enabled

---

operations/backup-and-restore/enable-backup-restore.yml

Update the cf-cli job in the `enable-backup-restore.yml` ops file.
Alana wants to have a working ops file for backup and restore.
The latest cf-cli release does not include v6 anymore:
https://github.com/cloudfoundry/bosh-package-cf-cli-release/releases/tag/v1.64.0
The `enable-backup-restore.yml` ops file now uses CF CLI v8.
The [bbr-deploy](https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/bbr-deploy) and [bbr-run-drats](https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/bbr-run-drats) jobs must succeed.

Update cf-cli job in bbr ops file

---

cf-deployment.yml

CAPI Release will switch Redis to Valkey as part of https://github.com/cloudfoundry/capi-release/pull/428 . This is due to Licensing changes in Redis.
Replace Redis with Valkey in API instance group
```console
bosh ssh api/123
ps -ef | grep valkey
/var/vcap/packages/valkey/valkey-cli -s /var/vcap/data/valkey/valkey.sock
valkey /var/vcap/data/valkey/valkey.sock> keys *
1) "metrics:cc.requests.outstanding.gauge"
```

Switch Redis to Valkey

---

ci/pipelines/cf-deployment.yml

CF CredHub deployment has been disabled for this environment, so we don't need the task that opens application security groups to CredHub.
See https://github.com/cloudfoundry/cf-deployment/pull/1179
See https://github.com/cloudfoundry/cf-deployment/pull/1179
N/A
Job "experimental-deploy" is green: https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/experimental-deploy
**Note**: Pipeline has already been updated with this change.

Remove "open-asgs-for-credhub" task for hermione/experimental

---

cf-deployment.yml

Updates tcp-router VMs to deploy serially, immediately after gorouters, so that they can finish being updated before the parallel block containing diego-cells run.
This allows us to ensure that all tcp-router related code + features are deployed and configured prior to updating diego-cells with code requesting those features via route-emitter.
We want tcp-router to deploy serially immediately after gorouter. This is a required pre-requisite before we can have users do a one stage deploy with no downtime to turn on a future TCP-router feature.
Currently during a deploy the tcp-router is updated in parallel to diego-cells. We think it deploys in this order because TCP-router is often an after thought and …

Update tcp-router to run serially

---

ci/pipelines/cf-deployment.yml

Enable the Cloud Native Buildpack flag on the fresh/luna environment. The CNB CATs suite is already enabled.
Alana wants to have the CNB feature validated in the cf-deployment pipeline.
https://github.com/cloudfoundry/community/pull/591
Feature is already released, this is just a configuration / feature flag update for the test environment.
The "fresh-cats" job must be green.

Enable the "diego_cnb" flag for "luna"

---

cf-deployment.yml

Due to the NATS v2 upgrade, the default size of the NATS vm should be increased.
Multiple customers have had issues with resource constraints since the NATS v2 upgrade.  Scaling up has been the recommendation for these issues.
Increase the default NATS vm size from `minimal` to `medium`
`bosh vms` should show `medium` under `VM Type` for the `nats` vm
@cloudfoundry/wg-app-runtime-platform

Increase default NATS vm size to medium

---

operations/bosh-lite.yml

Fix VM type for BOSH Lite. Known VM types are: "minimal", "small" and "small-highmem".
Make sure that NATs v2 runs stable on BOSH Lite.
Initial PR is https://github.com/cloudfoundry/cf-deployment/pull/1196
Increase the default NATS vm size from "minimal" to "medium" (on BOSH Lite, to "small").
The "lite-deploy" job succeeds: https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/lite-deploy

Fix NATs VM type for BOSH Lite

---

ci/pipelines/cf-deployment.yml

* isolation segment needs separate certificate for gorouter
Enable TLS validation for "luna" environment.
Alana wants to have proper TLS validation for a cf-d setup with isolation segments.
https://github.com/cloudfoundry/relint-envs/blob/main/environments/test/luna/README.md
N/A
Pipeline has already been uploaded and changes have been validated.

Enable TLS validation for "luna"/"fresh" env

---

operations/experimental/example-vars-files/vars-override-otel-collector-exporters.yml

- add file examples for each signal type
- comment out otlp examples as they are not valid unless updated with a real collector/backend to send to
Example otel collector vars file now has examples for all signal types

chore: update otel collector example vars file

---

ci/pipelines/cf-deployment.yml

Enable the NFS service for the "luna"/"fresh" environment.
Alana wants to have the NFS service validated.
Related CATs PR: https://github.com/cloudfoundry/cf-acceptance-tests/pull/1257
CATs config update: https://github.com/cloudfoundry/relint-envs/pull/46
⚠️ Prerequisite for this PR is a new nfs-volume-release with https://github.com/cloudfoundry/nfs-volume-release/pull/1038
N/A
"fresh-deploy" job must be green.

Enable NFS service for "luna"

---

ci/pipelines/cf-deployment.yml

Fix environment and deployment name for nfs-broker-push errand.
See https://github.com/cloudfoundry/cf-deployment/pull/1204
N/A
"run-nfs-broker-push-errand" task of "fresh-deploy" job must succeed. Pipeline has already been updated.
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/fresh-deploy

Fix nfs-broker-push errand for fresh env

---

iaas-support/bosh-lite/cloud-config.yml

Adds a medium VM type to the cloud-config so that base CF-D can deploy successfully. VM types in BOSH Lite don't matter, so this is trivial to add.
Alana is unable to deploy CF-D onto a BOSH Lite.
https://github.com/cloudfoundry/cf-deployment/issues/1202
Add `medium` VM type to BOSH Lite cloud-config.
Run through the [BOSH Lite deploy steps](https://github.com/cloudfoundry/cf-deployment/blob/main/iaas-support/bosh-lite/README.md) and see it succeed.
@tcdowney

Fix(iaas support/bosh lite): Add medium VM type to cloud-config

---

texts/on-cloud-configs.md

Reviewed the questions, but not going to answer each one  as this is a docs change.   the cloud configs are by defualt as follows, someone just put a zero in the wrong spot while writing the docs.
Checked the normal cloud configs my change matches the config.
```
- cloud_properties:
type: thin
disk_size: 102400
name: "102400"
```

Fixing typo in disk_types help documentation

---

ci/pipelines/cf-deployment.yml

This PR aim to change the [hardcoded](https://github.com/cloudfoundry/cf-deployment/blob/4167e5601b86ee9807c5a66a7845b40f8e613070/operations/test/enable-nfs-test-server.yml#L23) deployment name for luna environment. 
Alana wants to have the NFS service validated.
This PR aim to change the [hardcoded](https://github.com/cloudfoundry/cf-deployment/blob/4167e5601b86ee9807c5a66a7845b40f8e613070/operations/test/enable-nfs-test-server.yml#L23) deployment name for luna environment. The NFS service for "luna" was enabled using this [PR](https://github.com/cloudfoundry/cf-deployment/pull/1204), however as a result of a hardcoded deployment name, the fresh cats job was failing. The respective ops file to fix this issue is also contributed to https://github.com/cloudfoundry/relint-envs/pull/48.
N/A …

Change deployment name for NFS test server

---

iaas-support/alicloud/cloud-config.yml
iaas-support/openstack/cloud-config.yml
iaas-support/openstack/flavors.yml
iaas-support/vsphere/cloud-config.yml

Adds medium VM type to AliCloud, vSphere and OpensStack cloud-config.
cloud-config examples in https://github.com/cloudfoundry/cf-deployment/tree/main/iaas-support
https://github.com/cloudfoundry/cf-deployment/issues/1202
Adds medium VM type to AliCloud, vSphere and OpensStack cloud-config.

Add medium VM type to cloud-config

---

ci/pipelines/cf-deployment.yml

> This change will  disable the v2 api for all bbl environments used in the cf deployment pipeline.
> Alana want to safely remove CF API v2 from CAPI and cf-deployment.
> [Core of Phase 1 of RFC-00032: CF API v2 End of Life](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0032-cfapiv2-eol.md#proposal)
> 5. changes the name of …

Apply disable-v2-api ops file to all bbl envs used in cf-deployment validation

---

ci/pipelines/cf-deployment.yml

Add `aliases: true` to the `lint-cf-deployment-manifest` job in the cf-deployment pipeline. This allows that job to succeed when using the latest cf-d-c-t image, which now has ruby 3.1.x rather than ruby 2.7.x.
In ruby 2.7.x, the yaml library ran an unsafe load by default, which was okay with aliases, but in ruby 3.1.x it runs a safe load by default. We need to tell the safe load to explicitly allow aliases.
None.
- https://github.com/cloudfoundry/cf-deployment-concourse-tasks/pull/197
- https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/lint-cf-deployment-manifest/builds/2075
See the `lint-cf-deployment-manifest` job in the cf-deployment pipeline go green.
None

ci: Fix lint-cf-deployment-manifest job

---

operations/windows2019-cell.yml

Windows2019 v2019.79 seems to be broken. This PR aim to revert it to v2019.78
Alana is unable to deploy windows stemcell using the latest bumped version.
https://cloudfoundry.slack.com/archives/C02PW344Y/p1731604558431539
N/A
The windows-deploy job should be green.

rollback windows stemcell

---

operations/community/README.md
operations/community/add-blobstore-internal-network-allow-rule.yml

> _Please describe the change._
Per ticket #1216. An ops file to add custom internal network to the singleton blobstore allow list.
I'm developing a CPI that uses LXD. If people try this out in a clustered environment, it is very possible that they will be using the Ubuntu fan. The fan uses 240.0.0.0/8 as the default overlay network ("Future Use" range). It is possible that other people/organizations have other subnets as well.
#1216 
> …

Allow additional CIDR for the internal blobstore allow rules.

---

ci/pipelines/cf-deployment.yml

A race condition occurs during the stemcell updates via the automatic "[fast-lane](https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/update-releases?group=update-linux-stemcell)" stemcell release. This pipeline validates new stemcell versions and automatically creates releases, such as, [v44.6.0](https://github.com/cloudfoundry/cf-deployment/releases/tag/v44.6.0).
After a release, this stemcell update is merged back from the "main" to the "develop" branch. If the cf-deployment pipeline validates older "develop" revisions (e.g. if previous builds failed and new "develop" commits didn't make it past the "acquire-lock" jobs), it can happen that CF is deployed from the "main" branch (with a new stemcell version) and then upgraded to "develop" (still with the old stemcell …

Use generic stemcell versions task

---

ci/pipelines/pull-requests.yml

Removes the cats group from the pull-requests pipeline. I'm attempting to replace it with GH actions in the CATs repo.
None
cloudfoundry/cf-acceptance-tests#1372
N/A
When we fly the pipeline, the cf-deployment group continues to work, but the cats group goes away.
None

ci(pull-requests): Remove cats group

---

ci/pipelines/noble-stemcell.yml

This environment uses relint_ca as root CA, so we can enable TLS validation everywhere.
Alana wants to run the Noble stemcell validation on a TLS-enabled environment.
https://github.com/cloudfoundry/cf-deployment/issues/954
N/A
Noble validation pipeline eventually becomes green after resolving the remaining issues:
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/noble-stemcell-validation

Enable TLS for "bellatrix" environment

---

ci/input/inputs.yml
operations/enable-nfs-volume-service.yml

As of nfs-volume-release 7.18.0, map-fs job is included when nfsv3driver job is turned on. No need for the extra release to carry the code for mapfs.
As a developer, I'd like to consolidate my releases so that it consumes less resources and easier to manage
https://github.com/cloudfoundry/nfs-volume-release/pull/1046
> As a developer, I'd like to consolidate NFS-Volume-Release and Mapfs-Release into a single release so that it consumes less resources and easier to manage
Can be verified when running CATS with volume-services tag

Merge mapfs into nfs-volume-release

---

ci/pipelines/cf-deployment.yml
operations/experimental/README.md
operations/experimental/disable-v2-api.yml

API v2 is disabled by default, see https://github.com/cloudfoundry/capi-release/pull/503 and [RFC0032 - CF API v2 End of Life](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0032-cfapiv2-eol.md)
Since API v2 is disabled by default there is no need of experimental ops file disable-v2-api.
> removes ops-files from the following folders
>    - `./operations/experimental`
>    
> _Please specify either bosh cli or cf cli commands for our team (and cf operators) to verify the changes._
> _Few examples_
> 1. For a PR with a new job in the manifest, `bosh instances` can verify the job is running after upgrade. You can provide additional commands to verify the job is running as specified.
> 2. For a PR with new variables, `bosh variables | grep …

Remove experimental ops file disable-v2-api

---

units/tests/experimental_test/operations.yml

After removing the experimental ops file /operations/experimental/disable-v2-api.yml the unit tests started to fail.
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/unit-test-golang-tests/builds/2360
unit tests are failing: https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/unit-test-golang-tests/builds/2360 
unit-test-golang-tests in cf-deployment concourse pipeline should be green.

Replace disable-v2-api it with an empty ops interpolate test

---

texts/deployment-guide.md

Postgres 12 is out of maintenance: https://www.postgresql.org/support/versioning/
Documentation of supported PostgreSQL versions. PostgreSQL 12 is out of support.
https://cloudfoundry.slack.com/archives/C033ALST37V/p1741703433565859
Removed PostgreSQL 12 from the list of supported databases for CF.
n/a
@johha

Remove PostgreSQL 12 from supported DBs

---

ci/pipelines/ipv6-dual-stack-validation.md
ci/pipelines/ipv6-dual-stack-validation.yml

Setup a new bbl env and concourse job for IPv4/IPv6 dual stack validation. For more info see, https://github.com/cloudfoundry/community/pull/1077
Operators and maintainers want to start testing CF-Deployment with IPV4/IPV6 dual stack validation.
IPv6 Dual Stack Support for Cloud Foundry. You can see [the full RFC](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0038-ipv6-dual-stack-for-cf.md) .
N/A
Validating that the ipv6-dual-stack pipeline and it should remains green (it uses the pipeline yml included in this PR) and is doing the intended work to test the IPv6 dual stack validation.

Add new env dobby for ipv6 dual-stack validation

---

operations/windows2019-cell.yml

This reverts commit 50f87016740582da0f50ada94f2b5f41f15d962f.
windows2019.86 seems to be broken. This PR aim to revert it to v2019.85 to unblock the pipeline.
Alana is unable to deploy windows stemcell using the latest bumped version.
https://cloudfoundry.slack.com/archives/C02PW344Y/p1747666697658149
https://github.com/cloudfoundry/windows2019fs-release/issues/11
N/A
The windows-deploy job should be green after reverting to previous version.

Revert "windows2019 stemcell updated to 2019.86"

---

cf-deployment.yml

Manually merge "main" into "develop" because of failing "update-stemcell" job (failed because of github degradation):
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/update-releases/jobs/update-stemcell-minor/builds/68
Manually fix failed Concourse job.
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/update-releases/jobs/update-stemcell-minor/builds/68
Stemcell update release notes will be created manually.

Merge main into develop

---

cf-deployment.yml
operations/add-persistent-isolation-segment-diego-cell.yml
operations/bosh-lite.yml
operations/windows2019-cell.yml

Removing the obsolete logging timestamp format property
Alana no need to manage the logging timestamp format property as it is always rfc3339.
https://github.com/cloudfoundry/diego-release/pull/1016
Removing the obsolete logging timestamp format property
NA. Just removing the logging timestamp format property
@cloudfoundry/wg-app-runtime-platform-diego-approvers

cleanup time format property

---

ci/pipelines/ipv6-dual-stack-validation.yml
ci/pipelines/noble-stemcell.yml

Cost saving: Trigger validation pipelines only once per day.
Alana wants to reduce the infrastructure cost.
https://github.com/cloudfoundry/community/issues/1186
N/A
N/A
Pipelines run only once per day:
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/ipv6-dual-stack-validation
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/noble-stemcell-validation

Cost saving: Trigger IPv6 and Noble validation only once per day

---

cf-deployment.yml
operations/add-persistent-isolation-segment-diego-cell.yml
operations/windows2019-cell.yml

The property enable_consul_service_registration used to exist on many diego jobs. It was removed a long time ago. But references are still in cf-deployment. Remove all references in cf-deployment.
Alana no need to manage the enable_consul_service_registration property as it is unused.
https://github.com/cloudfoundry/diego-release/pull/656
NA. Just removing the unused property.
@cloudfoundry/wg-app-runtime-platform-diego-approvers

Remove old property referneces in cf-deployment: enable_consul_service

---

cf-deployment.yml

Removing the require_tls: true property as it will be set by default. 
Alana is no need to manage the require_tls property as it is always true.
https://github.com/cloudfoundry/diego-release/pull/1022
Released on tag: https://github.com/cloudfoundry/diego-release/releases/tag/v2.119.0
-  [x] NO
Alana is no need to manage the require_tls property as it is always true.
NA. Just removing the unused require_tls property.
@cloudfoundry/wg-app-runtime-platform-diego-approvers

cleanup rep require tls property
