cf-deployment.yml

Signed-off-by: JT Archie <jtarchie@gmail.com>

doppler announces as service on consul agent

---

README.md
opsfiles/bosh-lite.yml

Without these changes, I couldn't get the bosh-lite deploy to start.
Relatedly: It'd be awesome if you were running bosh-lite in your CI pipeline!

Bosh lite fixups

---

cf-deployment.yml

Signed-off-by: Derek Richard <drichard@pivotal.io>

Remove lots of unnecessary whitespace

---

opsfiles/windows-cell.yml

Update garden-windows-release to v0.2.0

Update garden-windows release to v0.2.0

---

cf-deployment.yml

Requirement for upcoming uaa release
[#139860837] https://www.pivotaltracker.com/story/show/139860837
Signed-off-by: Bharath Sekar <bharath.sekar@ge.com>

Fix authorized-grant-types for doppler client

---

cf-deployment.yml

This PR will enable routers to update serially and not in parallel. 
Regards
Shash

Update routers in serial

---

.gitignore

* deployment-vars.yml so that cf-deployment can serve as a local
env directory for bosh-lite

Add bosh lite deployment vars to gitignore

---

cf-deployment.yml

[#138084355]
Signed-off-by: Chris Piraino <cpiraino@pivotal.io>

route emitter consumes NATS link

---

operations/windows-cell.yml

Bump garden-windows and the hwc buildpack to the latest

bump windows releases

---

operations/test/add-persistent-isolation-segment-diego-cell.yml
operations/windows-cell.yml

* Updates ops files with changes made in
https://github.com/cloudfoundry/cf-deployment/pull/112
[finishes #141164981]

Switch rep server certs in ops files to use diego_rep_agent.

---

cf-deployment.yml

Signed-off-by: Joseph Palermo <jpalermo@pivotal.io>

Share the consul_server link

---

operations/experimental/locket.yml

[#143080755](https://www.pivotaltracker.com/story/show/143080755)
Signed by Luan Santos

Tps watcher locket

---

operations/experimental/locket.yml

This pr adds a new ops file to configure the cells to use locket for their cell presence instead of consul
[#142583213]
Signed-off-by: Swetha Repakula <srepaku@us.ibm.com>

Cell presence in locket

---

operations/windows-cell.yml

Bump the hwc buildpack release to the latest.

Bump hwc-buildpack-release

---

operations/experimental/enable-loggregator-v2-diego-cell.yml
operations/experimental/enable-loggregator-v2-windows-cell.yml

- `operations/experimental/enable-loggregator-v2-diego-cell.yml` is
independent of all other operation files
- `operations/experimental/enable-loggregator-v2-windows-cell.yml`
depends on the operation file `operations/windows-cell.yml`
[#140766309]

Add experimental operation files for using loggregator v2 API on cells

---

operations/experimental/locket.yml
operations/experimental/skip-consul-locks.yml

Also, add an opsfile to disable consul locks for routing-api
[#139885407](https://www.pivotaltracker.com/story/show/139885407)
Signed-off-by: Nino Kodabande <nkodabande@suse.com>

Add ops files to enable locket on routing-api

---

operations/community/README.md

It was noted to me that our company name actually is: `Stark & Wayne`.

Fix company name

---

operations/experimental/enable-loggregator-v2-diego-cell.yml
operations/experimental/enable-loggregator-v2-diego.yml

- experimental/enable-loggregator-v2-diego-cell.yml is renamed to
experimental/enable-loggregator-v2-diego.yml
[#148923981]
Signed-off-by: Swetha Repakula <srepaku@us.ibm.com>

Enable loggregator v2 ops file for bbs, rep &  auctioneer as well

---

operations/experimental/enable-iptables-logger.yml

[#149092065]
Signed-off-by: Jay Dunkelberger <ldunkelberger@pivotal.io>

Enabling iptables logging and add iptables-logger job to cell

---

operations/experimental/deploy-bosh-backup-restore.yml

[#149612273]
[#149706241]
[#149612281]
Signed-off-by: Joachim Valdez <valdezj@us.ibm.com>
cc @joachimvaldez

Add cf networking to backup restore VM

---

operations/disable-router-tls-termination.yml

otherwise bosh interpolate --var-errs-unused
will complain

Remove unused variables

---

cf-deployment.yml

This contains breaking changes required to upgrade to cf-networking-release v1.5.0. Do not merge until then.

Add new internal policy server job to api VM

---

cf-deployment.yml
operations/experimental/enable-iptables-logger.yml
operations/test/use-bosh-dns-for-containers.yml

This should not be merged until v1.6.0 is cut. We will bump this thread when that happens.
[#150179537]

Update path from silk-cni to cni

---

operations/scale-to-one-az.yml

Signed-off-by: Steffen Uhlig <Steffen.Uhlig@de.ibm.com>

Fix scaling down to one az for tcp-router instance group

---

operations/use-external-dbs.yml
scripts/fixtures/test-base-vars-store.yml

Signed-off-by: Nicholas Calugar <ncalugar@pivotal.io>

Remove variable that is no longer being used

---

cf-deployment.yml

[#151111701](https://www.pivotaltracker.com/story/show/151111701)
Matt & @tcdowney

Add UAA client "cc_service_key_client" for CC to talk to credhub

---

operations/experimental/bits-service-local.yml
operations/experimental/bits-service-s3.yml
operations/experimental/bits-service-webdav.yml
operations/experimental/bits-service.yml

[#151123319]
Signed-off-by: Norman Sutorius <norman.sutorius@de.ibm.com>

Colocate bits-service with CC

---

operations/experimental/README.md

Signed-off-by: Rob Dimsdale-Zucker <rdimsdale@pivotal.io>

Fix reference to locket operation file in README

---

README.md

Fix link to CI pipeline config

---

cf-deployment.yml

Move cf-networking-release out of cloudfoundry-incubator

---

cf-deployment.yml
operations/bosh-lite.yml

Signed-off-by: Lyle Franklin <lfranklin@pivotal.io>

Remove unused properties from cc clock

---

operations/experimental/README.md
operations/experimental/enable-instance-identity-credentials-windows2016.yml
scripts/test

[#152111630]
Signed-off-by: Sam Smith <sesmith177@gmail.com>

Add enable IIC opsfile for Windows 2016

---

operations/README.md
operations/example-vars-files/vars-use-swift-blobstore.yml
operations/use-swift-blobstore.yml
scripts/test

And add missing test and example vars file.

Fix use-swift-blobstore.yml ops file.

---

operations/experimental/enable-backup-restore.yml

[#152065802]
Signed-off-by: Aaron Hurley <ahurley@pivotal.io>

Add routing to bbr ops file

---

cf-deployment.yml

- [#105338348]
Signed-off-by: Lisa Cho <lcho@pivotal.io>

Remove redundant properties duplicated in capi-release defaults

---

operations/experimental/enable-prefer-declarative-healthchecks-windows2016.yml

Note that this PR depends on https://github.com/cloudfoundry/diego-release/pull/370
Signed-off-by: Sunjay Bhatia <sbhatia@pivotal.io>

Fix declarative healtheck on windows2016

---

iaas-support/bosh-lite/README.md

Update the vars-store filename to match the name given in the .gitignore.

Update README.md for bosh-lite

---

operations/scale-to-one-az.yml

Fixes commit 6b817d1012d522ea6fe860234a5bc7b9cb1a2915.

Fix: scale resource_group "adapter" to one az

---

operations/experimental/windows2016-cell.yml

Update to the latest: `v2.3.11`

Update hwc-buildpack-release to v2.3.11 in windows2016-cell opsfile

---

cf-deployment.yml

Fixes #347
Signed-off-by: Brady Love <blove@pivotal.io>

Remove consul on adapter advertising as doppler

---

README.md
operations/addons/README.md

- Clarify where rsyslog comes from
- Link to new docs regarding rsyslog custom rules
Signed-off-by: Milan Klanjsek <mklanjsek@pivotal.io>

Update notes on the syslog addon

---

operations/windows-cell.yml

https://github.com/cloudfoundry-incubator/consul-release/issues/83
https://www.pivotaltracker.com/story/show/153368219

Add 10s default ttl for consul dns.

---

README.md

I believe they call this an "[obvious fix](https://cla.pivotal.io/about#obvious-fixes)" ;)

spelling upgrade

---

iaas-support/alicloud/README.md
iaas-support/alicloud/cloud-config-vars.yml
iaas-support/alicloud/cloud-config.yml
iaas-support/alicloud/download-releases.sh
iaas-support/alicloud/stemcells.yml
iaas-support/alicloud/upload-releases.sh

The PR will support to deploy Cloud Foundry in Alibaba Cloud. It has one directory 'iaas-support/alicloud' that contains cloud-config and some scripts that can help user to deploy cloud foundry in China region.

[NEW PROVIDER] Support to deploy Cloud Foundry in Alibaba Cloud

---

operations/use-external-dbs.yml
scripts/fixtures/test-base-vars-store.yml

cc_database_password, diego_database_password & uaa_database_password are all not required when using external databases

Removing unused variables when using an external db

---

operations/experimental/README.md
operations/experimental/add-istio-release.yml
scripts/test-experimental-ops.sh

- Adds BPM because istio release requires it
- Add instance group for istio
- Enables communication between CC and istio copilot
Tracker story here: https://www.pivotaltracker.com/story/show/153187076

Add ops file for enabling istio release

---

deployment-guide.md

(With @patrick1378) Fix env vars in upload-stemcell command.
Replaces #438

Fix env vars in upload-stemcell command

---

cf-deployment.yml

[#157011310] https://www.pivotaltracker.com/story/show/157011310
Signed-off-by: Jaskanwal Pawar <jaskanwal.pawar@gmail.com>

Add new required encryption_keys property to uaa job

---

operations/experimental/use-log-cache.yml
scripts/semantic-tests.sh

Signed-off-by: Johanna Smith <josmith@pivotal.io>

Update use-log-cache.yml to collocate log-cache on doppler vms

---

operations/experimental/perm-service.yml

Fix perm-service.yml ops file

---

iaas-support/alicloud/stemcells.yml
operations/README.md
operations/example-vars-files/vars-use-alicloud-oss-blobstore.yml
operations/use-alicloud-oss-blobstore.yml
scripts/test-standard-ops.sh

This PR aims to support alibaba cloud oss blobstore and it has a pre-PR #531 .

Add support for alicloud blobstore

---

operations/experimental/README.md
operations/experimental/deploy-forwarder-agent.yml
scripts/test-experimental.sh

add forwarder agent and udp forwarder to cf-deployment
[#161354025]
Deploy forwarder agent and udp forwarder
Operators need an easy way to deploy the new forwarder agent with cf-deployment
Story: [https://www.pivotaltracker.com/story/show/161354025](https://www.pivotaltracker.com/story/show/161354025)
Operators can now deploy and test the new forwarder agent
It shouldn't
What is GA?
I soloed on this

operations/deploy-forwarder-agent:

---

cf-deployment.yml

[Finishes #163887340]
Signed-off-by: Andres Medina <amedina@pivotal.io>
_Does this introduce changes that would require operators to take action in order to deploy without a failure?_
**Examples of breaking changes:**
- changes the name of a job or instance group
- moves a job to a different instance group
- deletes a job or instance group
- changes …

Ensure the scheduler's `skip_cert_verify` is the same as others'

---

operations/experimental/deploy-forwarder-agent.yml

[#163917565]
This adds the existing UDP Forwarder to the router and tcp-router. It also disables UDP listening on the Loggregator Agent because everything should be going through the forwarder, now.
https://www.pivotaltracker.com/story/show/163917565
Disables UDP listening on Loggregator Agent and allows compatibility with the UDP Forwarder agent
_Does this introduce changes that would require operators to take action in order to deploy without a failure?_
**Examples of breaking changes:**
- changes the name of a job or instance group
- moves a job to a different instance group
- deletes a job or instance group
- changes the name of a credential
- …

Add UDP forwarder to router and disable Loggregator Agent UDP listening

---

ci/configure
ci/input/update-releases.yml
ci/pipelines/update-releases.yml
ci/template/update-releases.yml

Yes
Replacing `texplate` with `ytt`
`ytt` is a more poweful tool that allows easier generation and reusability/modularization of yaml templates.
[#164884020](https://www.pivotaltracker.com/story/show/164884020)
There's no need to be described in release notes. This is only pipeline changes.
No.
- [] GA'd feature/component

Use ytt for update-releases pipeline

---

operations/test/add-persistent-isolation-segment-infrastructure-metrics.yml
operations/test/add-persistent-isolation-segment-logging-system.yml
operations/test/add-persistent-isolation-segment-syslog-drain.yml
operations/test/alter-router-for-log-agent.yml
operations/test/isolated-logging-system-with-windows-cells.yml

Yes
Deprecate logging isolation segment ops-files
Isolated logging was only ever experimental. We no longer support them as they exist in these ops files.
https://www.pivotaltracker.com/story/show/165038981
_Something brief that conveys the change and is written with the Operator audience in mind.
Deprecate experimental isolated logging functionality.
_Does this introduce changes that would require operators to take action in order to deploy …

Deprecate logging isolation segments

---

cf-deployment.yml
operations/bits-service/use-bits-service.yml
operations/bosh-lite.yml
operations/enable-nfs-volume-service.yml
operations/enable-routing-integrity.yml
operations/enable-service-discovery.yml
operations/enable-smb-volume-service.yml
operations/experimental/add-metric-store.yml
operations/experimental/add-syslog-agent-windows1803.yml
operations/experimental/add-syslog-agent.yml
operations/experimental/enable-oci-phase-1.yml
operations/experimental/enable-routing-integrity-windows1803.yml
operations/experimental/enable-routing-integrity-windows2016.yml
operations/experimental/enable-tls-cloud-controller-postgres.yml
operations/test/add-oidc-provider.yml
operations/test/add-persistent-isolation-segment-diego-cell.yml
operations/test/add-persistent-isolation-segment-logging-system.yml
operations/test/add-persistent-isolation-segment-router.yml
operations/test/add-persistent-isolation-segment-syslog-drain.yml
operations/test/enable-nfs-test-ldapserver.yml
operations/use-haproxy.yml
operations/windows1803-cell.yml
operations/windows2012R2-cell.yml
operations/windows2016-cell.yml
operations/windows2019-cell.yml
scripts/semantic-tests.sh
units/test
units/tests/semantic_test/semantic_test.go

Yes.
Changing how CAs are referenced.
https://github.com/cloudfoundry/cf-deployment/issues/771 This issue was raised by CloudOps to allow them to use Credhub's new cert rotation which was introduced in [2.3.0](https://github.com/pivotal-cf/credhub-release/releases/tag/2.3.0) of Credhub.
See above.
N/A
Should mention that future references to CAs should be through their respective certificates. When someone upgrades to the cf-deployment including this change, there will be a very large diff in the bosh interpolate due to bosh not handling variable interpolation.
no
If you're promoting an experimental Ops-file (or removing one), Please follow the [Ops-file workflows](https://github.com/cloudfoundry/cf-deployment/blob/master/ops-file-promotion-workflow.md).
**Examples of breaking changes:** …

Reference the CA of each certificate

---

PULL_REQUEST_TEMPLATE.md

- Make it more readable by using block quotes
- Request submitters to describe customer problem from person pov (e.g. Alana, Cody)

Change instructions in PR template

---

texts/deployment-guide.md
texts/on-cloud-configs.md

When `deployment-guide.md` was moved below `/texts`, many of the relative links were broken when the markdown was rendered on GitHub, returning 404s when clicked.
This corrects the links so they render properly on GitHub. I chose to use absolute paths (i.e. begin with a "/"), but a relative path would have worked as well.
Two links are updated to use HTTPS instead of HTTP though this is more for consistency than security concerns.
Yes
Fix broken documentation links.
Documentation links were broken; now they are fixed.
Fix broken documentation links.
No.
If you're promoting an experimental Ops-file (or removing one), Please follow the [Ops-file workflows](https://github.com/cloudfoundry/cf-deployment/blob/master/ops-file-promotion-workflow.md).
**Examples of breaking changes:**
- changes …

Internal Markdown links resolve correctly on GitHub

---

cf-deployment.yml
operations/experimental/add-metric-store.yml
operations/test/add-persistent-isolation-segment-logging-system.yml
operations/windows1803-cell.yml
operations/windows2019-cell.yml

Removing a property that no longer exists in prom_scraper
https://www.pivotaltracker.com/story/show/167581372
> **Examples of breaking changes:**
> - **causes app or operator downtime**
> - modifies, deletes or moves the name of a job or instance group
> - changes the name of a credentials
> - requires out-of-band manual intervention on the part of the operator
> - removes Ops-file (e.g. from `./operations/` or `./operations/experimental` folders)
> _If you're promoting an experimental Ops-file (or removing one), Please follow the [Ops-file workflows](https://github.com/cloudfoundry/cf-deployment/blob/master/ops-file-promotion-workflow.md)._
Not sure it's needed in the release notes but
`Remove …

remove unused metrics_urls property from prom_scraper

---

operations/experimental/README.md
operations/experimental/enable-containerd-for-processes.yml
scripts/test-experimental.sh
units/tests/experimental_test/operations_test.go

This change adds an experimental ops file that allows garden to use containerd to run processes
https://www.pivotaltracker.com/story/show/162047473
New Ops-files -> operations/experimental/enable-containerd-for-processes.yml
Configure Garden to use containerd to run processes
@julz @danail-branekov @georgethebeatle

Add containerd for processes experimental ops file for garden

---

PULL_REQUEST_TEMPLATE.md
cf-deployment.yml
texts/versioning.md

- Add examples of breaking changes to the versioning doc.
- Update the PR template to include an example of a property change
Educate component teams on breaking changes.

add examples of breaking changes.

---

cf-deployment.yml
operations/test/add-persistent-isolation-segment-logging-system.yml

Log cache 2.4.0 removes the log-cache-scheduler. This PR makes sure CF-D won't fail with the new LogCache
Complexity has been removed from log-cache so it no longer requires the log-cache-scheduler job.
https://www.pivotaltracker.com/story/show/166749949
> **Examples of breaking changes:**
> - **causes app or operator downtime**
> - modifies, deletes or moves the name of a job or instance group
> - changes the name of a credentials
> - requires out-of-band manual intervention on the part of the operator
> - removes Ops-file (e.g. from `./operations/` or `./operations/experimental` folders)
> _If you're promoting an experimental Ops-file (or removing one), Please follow the [Ops-file …

log cache scheduler is not required as of log-cache 2.4.0

---

cf-deployment.yml
operations/experimental/add-syslog-agent.yml
operations/experimental/add-system-metrics-agent.yml
operations/experimental/use-logcache-syslog-ingress.yml

Add necessary properties to bump Loggregator Agent, Log Cache and Leadership Election releases.  
- Securing metrics and leadership-election endpoints with mTLS 
Breaking RelInt builds:
https://cloudfoundry.slack.com/archives/C02HCCXV5/p1568070806023600
https://cloudfoundry.slack.com/archives/C02HCCXV5/p1566343501016300
- Add mTLS to Leadership Election Release
- Add mTLS to metrics endpoints in Loggregator Agent and Log Cache
It does both since the bulk of Loggregator Agent and Log Cache is released but there
are also some experimental ops files that needed to change
@MasslessParticle @pianohacker @mjseaman

bump loggregator releases and add certs

---

README.md
units/README.md
units/helpers/check_interpolation.go
units/helpers/suite.go
units/tests/addons_test/operations.yml
units/tests/addons_test/operations_test.go
units/tests/backup_and_restore_test/operations.yml
units/tests/backup_and_restore_test/operations_test.go
units/tests/bits_service_test/operations.yml
units/tests/bits_service_test/operations_test.go
units/tests/experimental_test/operations.yml
units/tests/experimental_test/operations_test.go
units/tests/iaas_test/operations.yml
units/tests/iaas_test/operations_test.go
units/tests/standard_test/operations.yml
units/tests/standard_test/operations_test.go
units/tests/test_test/operations.yml
units/tests/test_test/operations_test.go

We want components to make changes to a YAML file rather than a Go struct when adding test coverage.
We don't want component teams to PR any complex tests besides our basic interpolation checks. Also the editing YAML might be easier than having to dive into a Go file.
Came from this story: https://www.pivotaltracker.com/story/show/168063414
Does not need to run CATs.
> 6. …

Use YAML configuration for interpolation unit tests

---

operations/experimental/README.md
operations/experimental/add-metrics-discovery-windows.yml
operations/experimental/add-metrics-discovery.yml
units/tests/experimental_test/operations.yml

Signed-off-by: Max Eshleman <meshleman@pivotal.io>
This change adds an experimental ops file to add metrics discovery registrar to VMs. Metrics discovery registrar is a component that registers scrapable metrics endpoints on the VM to NATs.
This change enables customers and component teams to discover scrapable metrics endpoints across their foundations. After this change, any interested component can subscribe to the NATS queue and discover metrics endpoints.
README explaining the new product:
https://github.com/cloudfoundry/metrics-discovery-release/blob/develop/README.md
Add ops files that will put the metrics discovery registrar job on all VMs to register scrape configurations with NATS. This allows any external metrics scraper to easily discover scrape endpoints on the platform …

add metrics discovery

---

operations/experimental/use-logcache-syslog-ingress.yml
operations/test/README.md
operations/test/remove-logging-pipeline-with-danger-windows1803.yml
operations/test/remove-logging-pipeline-with-danger-windows2019.yml
operations/test/remove-logging-pipeline-with-danger.yml
units/tests/test_test/operations.yml

Add ops files to disable the v2 logging pipeline jobs so users can prepare for it's eventual deprecation.
The v2 logging pipeline is going to be deprecated eventually. This is to prepare them for that deprecation.
https://www.pivotaltracker.com/story/show/169021301
This breaks some functionality in the CLI. However, they have stories to convert to using log-cache instead.
Introduce ops files to disable the v2 logging pipeline so teams can prepare for its eventual deprecation.
If these ops files are …

Add Ops Files to Disable v2 Logging Pipeline

---

operations/experimental/README.md
operations/experimental/enable-direct-io-grootfs.yml
units/tests/experimental_test/operations.yml

It enables direct IO on the loop device for the grootfs store mount.
Improves performance of grootfs store filesystem operations (creating/deleting rootfs/random access of files in the rootfs)
https://www.pivotaltracker.com/story/show/170178098
> 6. requires out-of-band manual intervention on the part of the operator 
> 7. modifies the ops-file path, changes the type, changes …

Add enable-direct-io-grootfs experimental flag

---

operations/experimental/README.md
operations/experimental/disable-v2-api.yml
units/tests/experimental_test/operations.yml

This PR introduces an ops file to allow operators to disable the v2 Cloud Controller API endpoints.
As the v2 API is close to being deprecated, Alana should be able to disable the v2 API. Once Codys have transitioned their use of the API, those endpoints are no longer necessary.
Slack discussion regarding Op file location and name: https://pivotal.slack.com/archives/C3LUD2L04/p1595009412053600
Introduce experimental `disable-v2-api.yaml` ops file that allows Alana to disable v2 Cloud Controller API endpoints.
1. If the ops file is enabled, the `cc.temporary_enable_v2` manifest property should be set to false, and requests to `/v2/apps` (or any v2 endpoint) should fail.
2. If not enabled, the `cc.temporary_enable_v2` manifest property should not be set, and requests to `/v2/apps` (or any …

Add ops file allowing operators to disable the v2 CC API

---

operations/experimental/README.md
operations/experimental/use-bionic-stemcell.yml
units/tests/experimental_test/operations.yml

This PR adds an experimental ops-file to deploy with the new bionic stemcell.
The current xenial stemcell is going to be deprecated next year. This allows users to start testing with the new bionic stemcell.
https://www.pivotaltracker.com/story/show/175620228
New use-bionic-stemcell.yml experimental ops-file
Deploy with the new stemcell. See the [bionic-stemcell pipeline](https://release-integration.ci.cf-app.com/teams/main/pipelines/bionic-stemcell) for details.

Add bionic stemcell ops file

---

README.md

Please also merge this into all relevant branches.
- CredHub Team

Update CredHub API doc URL

---

cf-deployment.yml

This PR adds the `cf-cli-8-linux` job to the `smoke-tests` instance group.
The latest version of cf-smoke-tests-release requires the `cf-cli-8-linux` package to be colocated on the VM.
> 6. …

Add cf-cli-8-linux to smoke-tests

---

iaas-support/bosh-lite/README.md
operations/experimental/README.md
operations/experimental/use-bionic-stemcell.yml
texts/deployment-guide.md
units/README.md
units/tests/experimental_test/operations.yml

This PR updates stemcell references in markdown docs from `xenial` to `bionic`.
> 6. requires …

Update docs to reference bionic stemcell instead of xenial

---

cf-deployment.yml

Add loggregator properties to vxlan-policy-agent job. This will allow vxlan-policy-agent to send app logs through loggregator when ASGs are updated. 
The feature will be released in the next silk and diego release and they should be auto-bumped in the cf-deployment. Having these properties in the manifest until then would not be a breaking change.
Customer wanted to get visibility into when ASGs are being updated for their applications.
* [Tracker story](https://www.pivotaltracker.com/story/show/181812241)
Manifest Updates
* vxlan-policy-agent sends an app log message whenever security groups are updated
* `cf push app-name`
* in a separate window tail app logs `cf logs app-name`
* `cf create-security-group sg-name /path/to/asg.json`
* `cf bind-security-group sg-name org-name --space …

Add loggregator client properties to vxlan-policy-agent

---

cf-deployment.yml

Signed-off-by: Renee Chu <reneec@vmware.com>
As a preparation for the next release of `nats` we are adding `ca` property to the client section. This property is used by nats post-start script to talk to nats migration server. We also switched `nats_client_cert` to `nats_server_cert` because this is the property under the server section. Technically they are the same, but just for the consistently would be better to use corresponding variable.
When new nats release comes out and cf-deployment picks it up automatically I don't want it to fail. My cf-deployment will have a required property.
[> _Include any links to other PRs, stories, slack discussions, etc... that will help establish context._ …

Add ca cert property to nats client

---

ci/pipelines/update-releases.yml
ci/template/update-releases.yml

Update the CI URL in the Update Releases Pipeline
N/A
> 7. modifies the ops-file path, changes the type, changes …

Update the CI URL in the Update Releases Pipeline

---

ci/pipelines/cf-deployment.yml

Fixing inputs of "bless-manifest" job in "cf-deployment" Concourse pipeline.
Failing smoke-tests jobs could be ignored when creating a new cf-deployment release.
N/A
No
No change in cf-deployment itself.
Green cf-deployment pipeline.
[wg-app-runtime-deployments](https://github.com/orgs/cloudfoundry/teams/wg-app-runtime-deployments)

Fix inputs of "bless-manifest" job

---

ci/pipelines/update-releases.yml
ci/template/update-releases.yml

Update "update-releases" pipeline to Jammy stemcell.
Majore stemcell update.
https://app-runtime-deployments.ci.cloudfoundry.org/teams/main/pipelines/update-releases/jobs/update-stemcell-and-recompile-releases/builds/3
Major stemcell update.
Updating stemcell from Bionic to Jammy 1.18.
Green "cf-deployment" pipeline: https://app-runtime-deployments.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment

Update update-releases pipeline to Jammy

---

ci/pipelines/cf-deployment.yml

* needs a fix in the AWS Jammy stemcell: https://github.com/cloudfoundry/bosh-linux-stemcell-builder/issues/241
The "experimental-deploy" is failing on Jammy because of https://github.com/cloudfoundry/silk-release/issues/67 and https://github.com/cloudfoundry/bosh-linux-stemcell-builder/issues/241.
Update to Jammy is blocked.
https://github.com/cloudfoundry/silk-release/issues/67
https://github.com/cloudfoundry/bosh-linux-stemcell-builder/issues/241
> Ops files changes in the following folders are considered as NON BREAKING CHANGES
> `./community`, `./example-vars-files`, `./test`
The …

Disable experimental/enable-iptables-logger for now

---

ci/pipelines/infrastructure.yml

Manage baba-yaga-bbr env in the ARD GCP project.
N/A
* https://cloudfoundry.slack.com/archives/C033ALST37V/p1666803496642499
N/A
cf-deployment pipeline's bbr fanout goes green.
@jochenehret

CI: migrate baba yaga bbr to ard gcp

---

ci/input/inputs.yml
ci/pipelines/update-releases.yml

Fix the `update-winc` job in the update-releases pipeline.
N/A
https://app-runtime-deployments.ci.cloudfoundry.org/teams/main/pipelines/update-releases/jobs/update-winc/builds/3
N/A
The update-winc job in the update-releases pipeline goes green.
N/A

CI: fix update-winc and update-hwc-buildpack jobs

---

ci/pipelines/infrastructure.yml

Move the bellatrix env to the ARD WG GCP project.
N/A
Part of an ongoing migration of environments.
N/A
Bellatrix jobs in the infrastructure pipeline go green
@iaftab-alam

CI: move bellatrix to ARD WG GCP project

---

operations/test/add-datadog-firehose-nozzle.yml
operations/test/add-oidc-provider.yml

Change uaa client "scope" configuration to yml array (as already done in other ops files and cf-deployment.yml).
Harmonizing yml structures.
Changed a "test" ops file that is not tested in cf-deployment pipeline.
> Ops files changes in the following folders are considered as NON BREAKING CHANGES
> `./community`, `./example-vars-files`, `./test`
Doesn't need to be mentioned in release notes.
Passing unit tests should be sufficient.

Change oidc scope list to yml array

---

operations/experimental/README.md
operations/experimental/add-cflinuxfs4.yml
units/tests/experimental_test/operations.yml

- Only adds cflinuxfs4 stack; does NOT make it the default stack
- Include buildpacks that currently support cflinuxfs4
- `cc/diego/droplet_destinations` and `cc/diego/lifecycle_bundles` both override default values from capi-release. In the long term, we should change those defaults in capi-release, rather than overriding in cf-deployment.
[#989]
> Add experimental ops file to add cflinuxfs4 stack
> App developers need to move off of cflinuxfs3 before the backing ubuntu version goes out of support. They can't start moving their apps until cflinuxfs4 is available.
> #989
> Add experimental ops file to add cflinuxfs4 stack
Adds [cflinuxfs4](https://bosh.io/releases/github.com/cloudfoundry/cflinuxfs4-release?all=1).
Using the python sample app from CATS:
```
$ cf push python -s cflinuxfs4 …
```

Add experimental ops file to add cflinuxfs4 stack

---

ci/pipelines/cf-deployment.yml
ci/pipelines/infrastructure.yml
ci/pipelines/update-releases.yml
ci/template/lib/manage-gcp-dns.lib.yml

Updating CI to reflect environments being migrated to the ARD GCP project.
N/A
https://github.com/cloudfoundry/relint-envs/issues/3
N/A
Pipelines remain green after this is merged and flown to concourse.
@jochenehret @davewalter

CI: update infrastructure pipeline to reflect environment migrations

---

.github/dependabot.yml
units/go.mod
units/vendor/gopkg.in/yaml.v2/go.mod
units/vendor/modules.txt

Configure dependabot to create PRs to bump the dependencies in the units module.
N/A
This is purely a CI change.
> 7. modifies the ops-file path, changes the type, changes the values or removes ops-files from the following folders
>    - `./operations/` or `./operations/experimental`
>    - `./addons`
> …

CI: add dependabot

---

README.md
ci/pipelines/cf-deployment.yml
ci/pipelines/infrastructure.yml

Messed up git history... I've pushed some pipeline changes directly to "main", but this breaks the release automation as it expects the same history in "main", "release-candiate" and "develop" (merge without rebase). Trying to fix this by merging the missing commits into "develop".

Merge pipeline commits from "main" into "develop"

---

ci/pipelines/update-releases.yml
ci/template/update-releases.yml

* and skip load balancer creation (we only need bosh in this environment)
* remove lb certificate (was expired anyway)

Migrate "greengrass" env to ARD WG account

---

ci/pipelines/cf-deployment.yml

Requires https://github.com/cloudfoundry/runtime-ci/pull/132

validate-certs job: Ignore "environments/ci/concourse/bbl-state/vars"

---

ci/pipelines/cf-deployment.yml

Yes
Temporarily comment out code related to recreating the snitch-lite BOSH director in the cf-deployment pipeline.
N/A
* https://github.com/cloudfoundry/bosh-bootloader/issues/567
* https://github.com/cloudfoundry/relint-envs/issues/13
N/A
lite-snitch fanout in cf-deployment pipeline goes green.
None

CI: Fix snitch-lite env

---

cf-deployment.yml

Makes sure silk app logs from dynamic ASG changes have correct application information.
- Silk logs are now updated with correct application tags.
Pre-requisite: a CF-D with dynamic ASGs turned on.
- Push an app
- Rename the app (do not restart!)
- See that logs are tagged with the correct name
- Add an ASG and apply it to the app
- See an app log line saying that the security group rules were changed that is tagged with the correct app name
None

add silk-datastore-syncer to diego cell

---

ci/pipelines/pull-requests.yml

Require at least one review approval for PRs
CI process. No change of cf-deployment content itself.
I impacts the CI flow.
n/a
n/a
@jochenehret

Require review approvals for PRs

---

operations/experimental/README.md
operations/experimental/fips-compliance.yml

> Configuration changes required to deploy and run cf-deployment on a FIPS stemcell are integrated into this experimental ops file.
> FIPS compliance
> #1140
> 7. modifies the ops-file path, changes the type, changes the …

Add experimental ops file for FIPS compliance

---

cf-deployment.yml

This change will allow operators to create ASGs with a _list_ of ips instead of just one ip or a cidr.
It is annoying to create multiple ASGs for each ip or cidr.
[CAPI PR (includes links to other PRs)](https://github.com/cloudfoundry/cloud_controller_ng/pulls?q=is%3Apr+comma)
[Docs PR](https://github.com/cloudfoundry/docs-cloudfoundry-concepts/pull/201)
Operators can create ASGs with comma-delimited destinations. For example, the following ASG definition is valid:
```
[
{
"protocol": "tcp",
"destination": "1.2.3.4,10.0.0.0/24,25.0.0.0-26.0.0.0",
"ports": "65432",
"description": "Valid comma delimited list of destinations"
}
]
```
It should pass this [CAT](https://github.com/cloudfoundry/cf-acceptance-tests/blob/main/security_groups/comma_delmited_asgs.go). You can run this cat by setting …

set enable_comma_delimited_destinations to true

---

operations/use-metric-store.yml

> Adding necessary otel certs to the metric store deployment
> 6. requires out-of-band manual …

Add otel certs to cf deployment

---

ci/pipelines/noble-stemcell.md
ci/pipelines/noble-stemcell.yml
operations/experimental/README.md
operations/experimental/use-noble-stemcell.yml
units/tests/experimental_test/operations.yml

This is a PR for "Noble" stemcell validation. Adds a pipeline to deploy and run tests against the "Noble" stemcell.
- Requires a noble stemcell to have been uploaded to any given CF-D
environment.
> _Please describe the change._
Operators and maintainers want to start testing CF-Deployment with the NOble stemcell.
N/A
> _Please specify either bosh cli or cf cli commands for our team (and cf operators) to verify the changes._
Validate that the noble-stemcell pipeline remains green (it uses the pipeline yml included in this PR) and is doing the intended work to test the noble stemcell.
> …

validation pipeline for the new beta Noble stemcell

---

ci/pipelines/noble-stemcell.yml

Use Postgres for the noble-stemcell-validation. MySQL currently doesn't compile.
Alana wants to validate the beta versions of the noble stemcell.
(issue will be raised on pxc-release project)
N/A
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/noble-stemcell-validation/jobs/deploy-cf should progress further.

Use Postgres for noble-stemcell-validation pipeline

---

operations/experimental/use-noble-stemcell.yml

Add "noble" to the list of stemcells in the BOSH "addons" section (otherwise we don't have bpm etc. on the VMs).
Alana wants to have a validation of the ubuntu-noble stemcell.
(no tracking issue for noble available yet)
N/A
The "deploy-cf" task should become green: https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/noble-stemcell-validation/jobs/deploy-cf

Add "noble" stemcell to BOSH addons

---

ci/pipelines/noble-stemcell.yml

Skip the deprecated "doppler" test in the Noble validation pipeline:
https://github.com/cloudfoundry/cf-acceptance-tests/blob/cb666e6c8d834ad369e55687a1ff62cfb131515c/apps/loggregator.go#L96
CATs test suite should only run tests for supported features.
https://github.com/cloudfoundry/cf-deployment/issues/1224
N/A
Test should be skipped: https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/noble-stemcell-validation/jobs/run-cats

Skip deprecated "logs and metrics" CAT on Noble environment

---

operations/experimental/use-noble-stemcell.yml

Fix for Noble stemcell BOSH DNS configuration.
Alana wants the CATs suite to pass on the new Noble stemcell.
https://github.com/cloudfoundry/diego-release/issues/987#issuecomment-2697164296
N/A
CATs are green (except for `container metrics [It] for memory usage` test)

Fix BOSH DNS config in Noble stemcell ops file

---

units/tests/experimental_test/operations.yml

This PR is pushed against develop branch.
Adding line in the experimental_test/operations.yml in order to fix the failure in the unit tests.
Missed the tests here:
https://github.com/cloudfoundry/cf-deployment/pull/1253 …

Fix failing unit tests for the new ipv6 ops file

---

operations/experimental/enable-ipv6-egress.yml

cc.enable_ipv6=true
Enable ipv6 in CC in ops file enable-ipv6-egress.yml
Should be mentioned only once all needed contributions to enable-ipv6-egress.yml have been collected (Diego, ASGs, whatever else is needed).
Eventually a green IPv6 validation pipeline. This change a contribution towards https://github.com/cloudfoundry/community/issues/1107

Configure CC in enable-ipv6-egress.yml

---

operations/experimental/enable-ipv6-egress.yml

Enable ipv6vin ops file `enable-ipv6-egress.yml`
This ops file results in the following config changes to the jobs in `diego-cell` instance group:
```diff
jobs:
- name: vxlan-policy-agent
properties:
+    ipv6:
+      enable: true
- name: silk-daemon
properties:
+    ipv6:
+      enable: true
+      prefix_network: default
- name: silk-cni
properties:
+    ipv6:
+      enable: true
```
And enables ipv6 on the cells:
```diff
instance_groups:
- name: diego-cell
env:
bosh:
+       ipv6:
+         enable: true
```
Should be mentioned only once all needed contributions to enable-ipv6-egress.yml have been collected (Diego, ASGs, whatever else is needed).
Eventually a green IPv6 validation pipeline. This change …

Add diego-cell specifics to the `enable-ipv6-egress.yml` ops file

---

ci/pipelines/ipv6-dual-stack-validation.yml

The PR is pushed against the develop branch 
Adding an opp file which consolidates all the changes related to IPv6 in the validation pipeline.  
The change is created for validation purposes.
> 7. modifies the ops-file path, changes the type, changes the values or removes ops-files from the following …

Add ipv6 ops file in the dualstack validation pipeline

---

ci/pipelines/cf-deployment.yml
ci/pipelines/update-releases.yml

to save costs on GCP
we migrated all bbl environments from europe-west3 to us-east1 to save costs related to GCP projects.
> 7. modifies the ops-file path, changes the type, changes the values or removes ops-files from …

Cost Saving:move bbl environments to us-east1

---

operations/windows2019-cell.yml

This reverts commit 79b4ccf463ea727c44f87f14c9d6737631844899.
This PR aim to revert it to v2019.90 to unblock the pipeline. Currently it is failing...
Alana is unable to deploy windows stemcell using the latest bumped version as it is failing with the following logs:
```
| L executing post-start: windows2019-cell/8393fe83-6c84-4203-a1d2-01e9365808bd (0) (canary) (00:22:16)
L Error: Action Failed get_task: Task 9c58b7fa-b0a7-4572-531b-8ce68e59a5d6 result: 1 of 3 post-start scripts failed. Failed Jobs: rep_windows. Successful Jobs: route_emitter_windows, bosh-dns-windows.
Task 3447 | 08:07:43 | Error: Action Failed get_task: Task 9c58b7fa-b0a7-4572-531b-8ce68e59a5d6 result: 1 of 3 post-start scripts failed. Failed Jobs: rep_windows. Successful Jobs: route_emitter_windows, bosh-dns-windows. …
```

Revert "windows2019 stemcell updated to 2019.90"
